# Project info
SetupGame( DEV_NAME "TLA"
    NICE_NAME "FOnline: The Life After"
    AUTHOR_NAME "MyCorpLtd"
    GAME_VERSION "0.1.0"
    SINGLEPLAYER NO
    ANGELSCRIPT_SCRIPTING YES
	NATIVE_SCRIPTING NO
	MONO_SCRIPTING NO )

# Content
AddContent( Maps )
AddContent( Critters Critters/Types )
AddContent( Items Items/Static Items/Custom )
AddContent( Dialogs )
AddContent( Texts )

# Scripts
AddEngineSource( SERVER Scripts/Extension/ServerExtension.cpp )
AddEngineSource( SERVER Scripts/Extension/CritterTimeEvents.cpp )
# AddAngelScriptExtensionSource( Scripts/AngelScriptExtension.cpp )
# AddAngelScriptExtensionEntry( InitAngelScriptExtension )
AddAngelScriptSource( Scripts/*.fos )
AddAngelScriptSource( Scripts/Json/*.fos )

# Resources
AddResources( FOnline Resources/FOnline )
AddResources( FOArt Resources/DataPacks/fo_art.zip Resources/DataPacks/fo_art_critters_h.zip )
AddResources( FOArt Resources/DataPacks/fo_art_critters_m.zip Resources/DataPacks/fo_art_critters_n.zip )
AddResources( BlackCombatArmor Resources/DataPacks/cablack.dat )
AddResources( Lieutenant Resources/DataPacks/lieutenant.dat )
AddResources( LongHairDude Resources/DataPacks/longhairdude.dat )
AddResources( FTRobots Resources/DataPacks/ftrobots.bos )
AddResources( FOSound Resources/DataPacks/fo_sound.zip )
AddResources( Music Resources/FOnlineMusic )
AddResources( Video Resources/FOnlineVideo )
# AddResources( Mapper Resources/Mapper )
# AddResources( VanBuren Resources/VanBuren )
# AddRawResources( Resources/Mapper )

# Configs
CreateConfig( Default "" )
TweakConfig( Enable3dRendering False )
TweakConfig( WindowName "The Life After" )
TweakConfig( ListenPort 4008 )
TweakConfig( AdminPanelPort 0 )
TweakConfig( GameSleep 10 )
TweakConfig( MemoryDebugLevel 1 )
TweakConfig( Logging True )
TweakConfig( LoggingDebugOutput False )
TweakConfig( LoggingTime True )
TweakConfig( LoggingThread False )
TweakConfig( ProfilerMode 0 )
TweakConfig( ProfilerSampleInterval 50 )
TweakConfig( Language_0 engl )
TweakConfig( Language_1 russ )
TweakConfig( Access_client "000000 00000000" )
TweakConfig( Access_tester "" )
TweakConfig( Access_moder "" )
TweakConfig( Access_admin "admin admin" )
TweakConfig( AccessNames_admin "" )
TweakConfig( Language engl )
TweakConfig( ServerHost localhost )
TweakConfig( ServerPort 4008 )
TweakConfig( UpdateServerHost "" )
TweakConfig( UpdateServerPort "" )
TweakConfig( ProxyType 0 )
TweakConfig( ProxyHost localhost )
TweakConfig( ProxyPort 1080 )
TweakConfig( ProxyUser "" )
TweakConfig( ProxyPass "" )
TweakConfig( MusicVolume 100 )
TweakConfig( SoundVolume 100 )
TweakConfig( ScreenWidth 1024 )
TweakConfig( ScreenHeight 768 )
TweakConfig( FullScreen False )
TweakConfig( AlwaysOnTop False )
TweakConfig( FixedFPS 100 )
TweakConfig( VSync False )
TweakConfig( MapHexagonal true )
TweakConfig( MapHexWidth 32 )
TweakConfig( MapHexHeight 16 )
TweakConfig( MapHexLineHeight 12 )
TweakConfig( MapTileOffsX -8 )
TweakConfig( MapTileOffsY 34 )
TweakConfig( MapTileStep 2 )
TweakConfig( MapRoofOffsX -8 )
TweakConfig( MapRoofOffsY -64 )
TweakConfig( MapRoofSkipSize 2 )
TweakConfig( MapCameraAngle 25.7f )
TweakConfig( MapSmoothPath True )
TweakConfig( MapDataPrefix "art/geometry/fallout_" )

CreateConfig( LocalTest Default )
TweakConfig( ServerHost localhost )
TweakConfig( ServerPort 4008 )
CreateConfig( LocalTest1 LocalTest )
CreateConfig( LocalTest2 LocalTest )
CreateConfig( LocalTest3 LocalTest )
CreateConfig( LocalTest4 LocalTest )
CreateConfig( LocalTest5 LocalTest )

CreateConfig( PublicGame Default )
TweakConfig( ServerHost 111.222.111.222 )
TweakConfig( ServerPort 9999 )

CreateConfig( Mapper Default )
TweakConfig( RoofAlpha 200 )
TweakConfig( SpritesZoomMax 10.0f )
TweakConfig( SpritesZoomMin 0.2f )
TweakConfig( Anim2CombatBegin Anim2Actions::BeginCombat )
TweakConfig( Anim2CombatIdle Anim2Actions::IdleCombat )
TweakConfig( Anim2CombatEnd Anim2Actions::EndCombat )
TweakConfig( SplitTilesCollection True )
TweakConfig( ConsoleHistorySize 100 )

# Test builds
CreatePackage( Tests LocalTest YES )
AddToPackage( Tests Client Windows win32 Raw )
AddToPackage( Tests Server Windows win64 Raw LocalTest1 )
AddToPackage( Tests Server Windows win64 Raw LocalTest2 )
AddToPackage( Tests Server Windows win64 Raw LocalTest3 )
AddToPackage( Tests Server Windows win64 Raw LocalTest4 )
AddToPackage( Tests Server Windows win64 Raw LocalTest5 )

# Production builds
CreatePackage( Production PublicGame NO )
AddToPackage( Production Client Windows win32+win64 Raw )
AddToPackage( Production Client Windows win32+win64 Wix )
AddToPackage( Production Client Windows win32 Zip )
AddToPackage( Production Client Android arm+arm64+x86 Apk )
AddToPackage( Production Client Web wasm Raw )
AddToPackage( Production Client macOS x64 Bundle )
AddToPackage( Production Client iOS arm64 Bundle )
AddToPackage( Production Client Linux x64 AppImage )
AddToPackage( Production Server Windows win64 Raw )
AddToPackage( Production Server Windows win64 Zip )
AddToPackage( Production Server Linux x64 Raw )
AddToPackage( Production Server Linux x64 Tar )
AddToPackage( Production Server Linux x64 AppImage )
