# Project info
SetupGame( DEV_NAME "TLA"
    NICE_NAME "FOnline: The Life After"
    COMPANY_NAME "MyCorpLtd"
    GAME_VERSION "0.1.0"
    MULTIPLAYER_SCRIPTING YES
    SINGLEPLAYER_SCRIPTING NO
    ANGELSCRIPT_SCRIPTING YES 
	NATIVE_SCRIPTING NO 
	MONO_SCRIPTING NO )

# Content
AddContent( Maps )
AddContent( Critters )
AddContent( Critters/Types )
AddContent( Items )
AddContent( Items/Static )
AddContent( Items/Custom )
AddContent( Dialogs )
AddContent( Texts )

# Scripts
AddEngineSource( SERVER Scripts/Extension/ServerExtension.cpp )
AddEngineSource( SERVER Scripts/Extension/CritterTimeEvents.cpp )
# AddAngelScriptExtensionSource( Scripts/AngelScriptExtension.cpp )
# AddAngelScriptExtensionEntry( InitAngelScriptExtension )
AddAngelScriptSource( Scripts/*.fos )
AddAngelScriptSource( Scripts/Json/*.fos )

# Resources
AddResources( Base Resources/FOnline )
AddResources( Music Resources/FOnlineMusic )
AddResources( Video Resources/FOnlineVideo )
AddResources( Mapper Resources/Mapper )
AddResources( VanBuren Resources/VanBuren )
AddRawResources( Resources/Mapper )

# Configs
CreateConfig( Default "" )

TweakConfig( Enable3dRendering False )
TweakConfig( WindowName "The Life After" )
TweakConfig( ListenPort 4008 )
TweakConfig( AdminPanelPort 0 )
TweakConfig( GameSleep 10 )
TweakConfig( MemoryDebugLevel 1 )
TweakConfig( Logging True )
TweakConfig( LoggingDebugOutput False )
TweakConfig( LoggingTime True )
TweakConfig( LoggingThread False )
TweakConfig( ProfilerMode 0 )
TweakConfig( ProfilerSampleInterval 50 )
TweakConfig( Language_0 engl )
TweakConfig( Language_1 russ )
TweakConfig( Access_client "000000 00000000" )
TweakConfig( Access_tester "" )
TweakConfig( Access_moder "" )
TweakConfig( Access_admin "admin admin" )
TweakConfig( AccessNames_admin "" )
TweakConfig( Language engl )
TweakConfig( RemoteHost localhost )
TweakConfig( RemotePort 4008 )
TweakConfig( UpdateServerHost "" )
TweakConfig( UpdateServerPort "" )
TweakConfig( ProxyType 0 )
TweakConfig( ProxyHost localhost )
TweakConfig( ProxyPort 1080 )
TweakConfig( ProxyUser "" )
TweakConfig( ProxyPass "" )
TweakConfig( MusicVolume 100 )
TweakConfig( SoundVolume 100 )
TweakConfig( ScreenWidth 1024 )
TweakConfig( ScreenHeight 768 )
TweakConfig( FullScreen False )
TweakConfig( AlwaysOnTop False )
TweakConfig( FixedFPS 100 )
TweakConfig( VSync False )
TweakConfig( MapHexagonal true )
TweakConfig( MapHexWidth 32 )
TweakConfig( MapHexHeight 16 )
TweakConfig( MapHexLineHeight 12 )
TweakConfig( MapTileOffsX -8 )
TweakConfig( MapTileOffsY 34 )
TweakConfig( MapTileStep 2 )
TweakConfig( MapRoofOffsX -8 )
TweakConfig( MapRoofOffsY -64 )
TweakConfig( MapRoofSkipSize 2 )
TweakConfig( MapCameraAngle 25.7f )
TweakConfig( MapSmoothPath True )
TweakConfig( MapDataPrefix "art/geometry/fallout_" )

CreateConfig( Mapper Default )
TweakConfig( RoofAlpha 200 )
TweakConfig( SpritesZoomMax 10.0f )
TweakConfig( SpritesZoomMin 0.2f )
TweakConfig( Anim2CombatBegin Anim2Actions::BeginCombat )
TweakConfig( Anim2CombatIdle Anim2Actions::IdleCombat )
TweakConfig( Anim2CombatEnd Anim2Actions::EndCombat )
TweakConfig( SplitTilesCollection True )
TweakConfig( ConsoleHistorySize 100 )

CreateConfig( Multiplayer Default )
CreateConfig( Singleplayer Default )

# Test builds
CreatePackage( "Test" "LocalTest" YES )
AddToPackage( "Test" "Client" "Windows" "win32" "Raw" )
AddToPackage( "Test" "Client" "Web" "wasm" "Raw" "LocalWebTest" )
AddToPackage( "Test" "Server" "Windows" "win64" "Raw" )
CreatePackage( "ProductionTest" "LocalTest" NO )
AddToPackage( "ProductionTest" "Client" "Windows" "win32" "Raw" )
AddToPackage( "ProductionTest" "Client" "Web" "wasm" "Raw" "LocalWebTest" )
AddToPackage( "ProductionTest" "Server" "Windows" "win64" "Raw" )
AddToPackage( "Test" "Single" "Windows" "win32" "Raw" )

# Production builds
CreatePackage( "Production" Default NO )
AddToPackage( "Production" "Client" "Windows" "win32+win64" "Raw" )
AddToPackage( "Production" "Client" "Windows" "win32+win64" "Wix" )
AddToPackage( "Production" "Client" "Windows" "win32" "Zip" )
AddToPackage( "Production" "Client" "Android" "arm+arm64+x86" "Apk" )
AddToPackage( "Production" "Client" "Web" "wasm" "Raw" )
AddToPackage( "Production" "Client" "macOS" "x64" "Bundle" )
AddToPackage( "Production" "Client" "iOS" "arm64" "Bundle" )
AddToPackage( "Production" "Client" "Linux" "x64" "AppImage" )
AddToPackage( "Production" "Server" "Windows" "win64" "Raw" )
AddToPackage( "Production" "Server" "Windows" "win64" "Zip" )
AddToPackage( "Production" "Server" "Linux" "x64" "Raw" )
AddToPackage( "Production" "Server" "Linux" "x64" "Tar" )
AddToPackage( "Production" "Server" "Linux" "x64" "AppImage" )
