#
# Worldmap Encounter messages
#

{10000010}{}{Вы наткнулись на @lex who@.}
{10000011}{}{Вы наткнулись на @lex who@ и @lex player@.}
{10000012}{}{Вы наткнулись на @lex who@ и банду @lex player@.}
{10000013}{}{Вы наткнулись на @lex player@.}
{10000014}{}{Вы наткнулись на банду @lex player@.}
{10000020}{}{Вы хотите увидеть @lex who@?}
{10000021}{}{Вы хотите увидеть @lex who@ и @lex player@?}
{10000022}{}{Вы хотите увидеть @lex who@ и банду @lex player@?}
{10000023}{}{Вы хотите увидеть @lex player@?}
{10000024}{}{Вы хотите увидеть банду @lex player@?}

# Encounter Table 0 (Fallout 1 + FOnline global table)
{10030000}{}{банду рейдеров}
{10030010}{}{несколько рад-скорпионов}
{10030020}{}{больших крысомутантов}
{10030030}{}{группу торговцев}
{10030040}{}{<Особое>}
{10030050}{}{кого-то неизвестного}
{10030060}{}{Церковь Брока и Зандера}
{10030070}{}{путешественника}
{10030080}{}{головорезов из банды Шакалы Карлоса}

# Encounter Table 1
{10030500}{}{банду рейдеров}
{10030510}{}{несколько мантисов}
{10030520}{}{группу ящеров}
{10030530}{}{кучку кротов-гризли}
{10030540}{}{стайку рад-скорпионов}
{10030550}{}{стаю гигантских крысомутантов}
{10030560}{}{группу торговцев}
{10030570}{}{<Особое>}

# Encounter Table 2
{10031000}{}{банду рейдеров}
{10031010}{}{стайку рад-скорпионов}
{10031020}{}{стаю гигантских крысомутантов}
{10031030}{}{группу торговцев}
{10031040}{}{<Особое>}

# Encounter Table 3
{10031500}{}{банду рейдеров}

# Encounter Table 4
{10032000}{}{банду рейдеров}

# Encounter Table 5
{10032500}{}{банду рейдеров}

# Encounter Table 6
{10032990}{}{патрульных Арройо}
{10033000}{}{отряд солдат}
{10033010}{}{стадо каннибалов}
{10033020}{}{заросли хищных цветков и несколько серебряных ящеров}
{10033030}{}{группу серебряных ящеров}
{10033040}{}{охотников за бандитами}
{10033050}{}{охотников за бандитами}
{10033060}{}{охотников за бандитами}
{10033070}{}{охотников за бандитами}
{10033080}{}{охотников за бандитами}
{10033090}{}{охотников за бандитами}
{10033100}{}{охотников за бандитами}
{10033110}{}{охотников за бандитами}
{10033120}{}{толпу отщепенцев с братом Мортона во главе}
{10033130}{}{несколько скорпионов}
{10033140}{}{несколько хищных цветков}
{10033150}{}{группу крысо-кабанов}
{10033160}{}{стайку грызунов}
{10033170}{}{отряд охотников, бьющийся с каннибалами}
{10033180}{}{кучку муравьев}
{10033190}{}{отряд охотников, сражающийся со скорпионами}
{10033200}{}{небольшую стаю крысо-кабанов}
{10033210}{}{маленькую группку рад-скорпионов}
{10033220}{}{совсем немного муравьев}
{10033230}{}{отряд охотников}
{10033240}{}{становье кочевников}
{10033250}{}{человека, охраняющего мост}
{10033260}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 7 
{10033490}{}{патрульных Арройо}
{10033500}{}{помойку ядовитых отбросов}
{10033510}{}{странную одинокую собаку}
{10033520}{}{стадо браминов}
{10033530}{}{отряд солдат}
{10033540}{}{охотников за бандитами}
{10033550}{}{охотников за бандитами}
{10033560}{}{охотников за бандитами}
{10033570}{}{охотников за бандитами}
{10033580}{}{охотников за бандитами}
{10033590}{}{охотников за бандитами}
{10033600}{}{охотников за бандитами}
{10033610}{}{охотников за бандитами}
{10033620}{}{толпу отщепенцев с братом Мортона  во главе}
{10033630}{}{группу каннибалов}
{10033640}{}{заросли хищных цветков и несколько серебряных ящеров}
{10033650}{}{группу серебряных ящеров}
{10033660}{}{стайку скорпионов}
{10033670}{}{несколько хищных цветков}
{10033680}{}{группу крысо-кабанов}
{10033690}{}{стаю грызунов}
{10033700}{}{отряд охотников, бьющийся с каннибалами}
{10033710}{}{кучку муравьев}
{10033720}{}{отряд охотников, сражающийся со скорпионами}
{10033730}{}{небольшую стаю крысо-кабанов}
{10033740}{}{маленькую группку рад-скорпионов}
{10033750}{}{совсем немного муравьев}
{10033760}{}{отряд охотников}
{10033770}{}{становье кочевников}
{10033780}{}{останки белого кита}
{10033790}{}{большую каменную голову}
{10033800}{}{разбившийся шаттл}
{10033810}{}{Портал Хранителя}
{10033820}{}{рыцарей короля Артура}
{10033830}{}{железного дровосека}
{10033840}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 8
{10033990}{}{патрульных Арройо}
{10034000}{}{отряд солдат}
{10034010}{}{группу каннибалов}
{10034020}{}{заросли хищных цветков и несколько серебряных ящеров}
{10034030}{}{группу серебряных ящеров}
{10034040}{}{охотников за бандитами}
{10034050}{}{охотников за бандитами}
{10034060}{}{охотников за бандитами}
{10034070}{}{охотников за бандитами}
{10034080}{}{охотников за бандитами}
{10034090}{}{охотников за бандитами}
{10034100}{}{охотников за бандитами}
{10034110}{}{охотников за бандитами}
{10034120}{}{толпу отщепенцев с братом Мортона  во главе}
{10034130}{}{группу скорпионов}
{10034140}{}{несколько хищных цветков}
{10034150}{}{стаю крысо-кабанов}
{10034160}{}{несколько грызунов}
{10034170}{}{отряд охотников, бьющийся с каннибалами}
{10034180}{}{несколько муравьев}
{10034190}{}{отряд охотников, сражающийся со скорпионами}
{10034200}{}{небольшую стаю крысо-кабанов}
{10034210}{}{маленькую группку рад-скорпионов}
{10034220}{}{совсем немного муравьев}
{10034230}{}{отряд охотников}
{10034240}{}{группу кочевников}

# Encounter Table 9
{10034500}{}{помойку ядовитых отбросов}
{10034510}{}{странную одинокую собаку}
{10034520}{}{стадо браминов}
{10034530}{}{банду изгоев}
{10034540}{}{охотников за бандитами}
{10034550}{}{охотников за бандитами}
{10034560}{}{охотников за бандитами}
{10034570}{}{охотников за бандитами}
{10034580}{}{охотников за бандитами}
{10034590}{}{охотников за бандитами}
{10034600}{}{охотников за бандитами}
{10034610}{}{охотников за бандитами}
{10034620}{}{толпу отщепенцев с братом Мортона  во главе}
{10034630}{}{несколько святых людей}
{10034640}{}{стайку ящеров и кротов-гризли}
{10034650}{}{немного ящеров}
{10034660}{}{группу рад-скорпионов, прячущихся между хищных цветков}
{10034670}{}{отдельные хищные цветки}
{10034680}{}{семейку рад-скорпионов}
{10034690}{}{группу кротов-гризли}
{10034700}{}{группу святых людей, отбивающихся от воинской команды}
{10034710}{}{отряд кочевников}
{10034720}{}{останки белого кита}
{10034730}{}{большую каменную голову}
{10034740}{}{разбившийся шаттл}
{10034750}{}{Портал Хранителя}
{10034760}{}{рыцарей короля Артура}
{10034770}{}{железного дровосека}
{10034780}{}{немытых крестьян, гоняющихся за бродягой}
{10034790}{}{Пристанище Детей Пустоши}
{10034800}{}{заброшенный аванпост Рыцарей Пустоши}
{10034810}{}{пещеру}
{10034820}{}{заброшенную деревеньку. Даже с расстояния ощущается зло, исходящее от нее}
{10034830}{}{заброшенный склад пончиков}

# Encounter Table 10
{10035000}{}{нескольких изгоев}
{10035010}{}{компанию святых людей}
{10035020}{}{охотников за бандитами}
{10035030}{}{охотников за бандитами}
{10035040}{}{охотников за бандитами}
{10035050}{}{охотников за бандитами}
{10035060}{}{охотников за бандитами}
{10035070}{}{охотников за бандитами}
{10035080}{}{охотников за бандитами}
{10035090}{}{охотников за бандитами}
{10035100}{}{толпу отщепенцев с братом Мортона  во главе}
{10035110}{}{заросли хищных цветков и несколько серебряных ящеров}
{10035120}{}{несколько ящеров}
{10035130}{}{группу рад-скорпионов, прячущихся между хищных цветков}
{10035140}{}{хищные цветки}
{10035150}{}{небольшой отряд рад-скорпионов}
{10035160}{}{кучку кротов-гризли}
{10035170}{}{группу святых людей, отбивающихся от воинской команды}
{10035180}{}{банду кочевников}
{10035190}{}{человека, охраняющего мост}
{10035200}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 11
{10035500}{}{химические отбросы}
{10035510}{}{странную одинокую собаку}
{10035520}{}{стадо браминов}
{10035530}{}{целую стаю золотых ящеров и большое семейство рад-скорпионов}
{10035540}{}{группу бандитов}
{10035550}{}{несколько бездомных бродяг}
{10035560}{}{стаю золотых ящеров}
{10035570}{}{охотников за бандитами}
{10035580}{}{охотников за бандитами}
{10035590}{}{охотников за бандитами}
{10035600}{}{охотников за бандитами}
{10035610}{}{охотников за бандитами}
{10035620}{}{охотников за бандитами}
{10035630}{}{охотников за бандитами}
{10035640}{}{охотников за бандитами}
{10035650}{}{толпу отщепенцев с братом Мортона  во главе}
{10035660}{}{целое семейство рад-скорпионов}
{10035670}{}{хищные цветки}
{10035680}{}{отряд бандитов, атакованный стадом золотых ящеров}
{10035690}{}{крестьян, обороняющихся от нападения злых ящеров}
{10035700}{}{крестьян, схватившихся в бою с золотыми ящерами}
{10035710}{}{группу трапперов, загнавших стаю золотых ящеров}
{10035720}{}{трапперов, отбивающихся от местных бандитов}
{10035730}{}{группу трапперов, окружающих стадо ящеров}
{10035740}{}{бандитов, устроивших засаду на нескольких бездомных бродяг}
{10035750}{}{вооруженных бродяг, пытающихся вырезать группу крестьян}
{10035760}{}{местных бандитов, напавших на крестьян}
{10035770}{}{крестьян, сражающихся с ужасными скорпионами}
{10035780}{}{трапперов, пытающихся спастись от скорпионов}
{10035790}{}{группу трапперов, атакующих стадо кротов-гризли}
{10035800}{}{нескольких крестьян, разделывающих на мясо группу кротов-гризли}
{10035810}{}{группу крестьян}
{10035820}{}{отряд трапперов}
{10035830}{}{останки белого кита}
{10035840}{}{большую каменную голову}
{10035850}{}{разбившийся шаттл}
{10035860}{}{Портал Хранителя}
{10035870}{}{рыцарей короля Артура}
{10035880}{}{железного дровосека}
{10035890}{}{немытых крестьян, гоняющихся за бродягой}
{10035900}{}{Пристанище Детей Пустоши}
{10035910}{}{заброшенный аванпост Рыцарей Пустоши}
{10035920}{}{заброшенную деревеньку. Даже с расстояния ощущается зло, исходящее от нее}
{10035930}{}{заброшенный склад пончиков}

# Encounter Table 12
{10036000}{}{целую стаю золотых ящеров и большое семейство рад-скорпионов}
{10036010}{}{отряд бандитов}
{10036020}{}{большую группу бездомных людей}
{10036030}{}{стайку золотых ящеров}
{10036040}{}{охотников за бандитами}
{10036050}{}{охотников за бандитами}
{10036060}{}{охотников за бандитами}
{10036070}{}{охотников за бандитами}
{10036080}{}{охотников за бандитами}
{10036090}{}{охотников за бандитами}
{10036100}{}{охотников за бандитами}
{10036110}{}{охотников за бандитами}
{10036120}{}{толпу отщепенцев с братом Мортона  во главе}
{10036130}{}{крупное семейство рад-скорпионов}
{10036140}{}{хищные цветки}
{10036150}{}{отряд бандитов, атакованный стадом золотых ящеров}
{10036160}{}{крестьян, обороняющихся от нападения злых ящеров}
{10036170}{}{крестьян, схватившихся в бою с золотыми ящерами}
{10036180}{}{группу трапперов, загнавших стаю золотых ящеров}
{10036190}{}{трапперов, отбивающихся от местных бандитов}
{10036200}{}{группу трапперов, окружающих стадо ящеров}
{10036210}{}{бандитов, устроивших засаду на нескольких бездомных бродяг}
{10036220}{}{вооруженных бродяг, пытающихся вырезать группу крестьян}
{10036230}{}{местных бандитов, напавших на крестьян}
{10036240}{}{крестьян, сражающихся с ужасными скорпионами}
{10036250}{}{трапперов, пытающихся спастись от скорпионов}
{10036260}{}{группу трапперов, атакующих стадо кротов-гризли}
{10036270}{}{нескольких крестьян, разделывающих на мясо группу кротов-гризли}
{10036280}{}{группу крестьян}
{10036290}{}{отряд трапперов}
{10036300}{}{человека, охраняющего мост}
{10036310}{}{рыцарей короля Артура, воюющих с грызуном}
{10036320}{}{заброшенный склад пончиков}

# Encounter Table 13
{10036500}{}{помойку химикатов}
{10036510}{}{странную одинокую собаку}
{10036520}{}{стадо браминов}
{10036530}{}{торговца и его охранников}
{10036540}{}{охотников за бандитами}
{10036550}{}{охотников за бандитами}
{10036560}{}{охотников за бандитами}
{10036570}{}{охотников за бандитами}
{10036580}{}{охотников за бандитами}
{10036590}{}{охотников за бандитами}
{10036600}{}{охотников за бандитами}
{10036610}{}{охотников за бандитами}
{10036620}{}{толпу отщепенцев с братом Мортона  во главе}
{10036630}{}{отряд трапперов}
{10036640}{}{бандитов, напавших на охраняемый торговый караван}
{10036650}{}{бандитов, из засады атаковавших группу трапперов}
{10036660}{}{большое стадо рад-скорпионов, напавших на торговый караван}
{10036670}{}{группу трапперов, пытающихся отловить рад-скорпионов}
{10036680}{}{несколько рад-скорпионов}
{10036690}{}{семейство кротов-гризли}
{10036700}{}{группу бандитов}
{10036710}{}{отряд трапперов, старающихся изловить и ободрать золотых ящеров}
{10036720}{}{ужасных скорпионов, пытающихся сожрать золотых ящеров}
{10036730}{}{скорпионов, обнаруживших поживу - крысо-кабанов и кротов-гризли}
{10036740}{}{группу трапперов и торговцев из каравана, бьющихся с бандитами}
{10036750}{}{золотых ящеров}
{10036760}{}{нескольких трапперов, истребляющих крысо-кабанов и кротов-гризли}
{10036770}{}{торговцев из каравана, отражающих нападение крысо-кабанов и кротов-гризли}
{10036780}{}{останки белого кита}
{10036790}{}{большую каменную голову}
{10036800}{}{разбившийся шаттл}
{10036810}{}{Портал Хранителя}
{10036820}{}{рыцарей короля Артура}
{10036830}{}{железного дровосека}
{10036840}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 14
{10037000}{}{ядовитые отбросы}
{10037010}{}{странную одинокую собаку}
{10037020}{}{стадо браминов}
{10037030}{}{банду разбойников}
{10037040}{}{охотников за бандитами}
{10037050}{}{охотников за бандитами}
{10037060}{}{охотников за бандитами}
{10037070}{}{охотников за бандитами}
{10037080}{}{охотников за бандитами}
{10037090}{}{охотников за бандитами}
{10037100}{}{охотников за бандитами}
{10037110}{}{охотников за бандитами}
{10037120}{}{толпу отщепенцев с братом Мортона  во главе}
{10037130}{}{банду грабителей}
{10037140}{}{большой отряд грабителей и разбойников}
{10037150}{}{группу золотых ящеров и нескольких рад-скорпионов}
{10037160}{}{семейство золотых ящеров}
{10037170}{}{семейство кротов-гризли}
{10037180}{}{большую группу рад-скорпионов}
{10037190}{}{целые заросли отвратительных хищных цветков}
{10037200}{}{банду грабителей, внезапно напавших на разбойничью шайку}
{10037210}{}{торговый караван, отбивающийся от атак разбойников}
{10037220}{}{группу торговцев, сражающихся с грабителями}
{10037230}{}{торговый караван, отражающий нападение рад-скорпионов}
{10037240}{}{стаю золотых ящеров, бьющихся с мерзкими рад-скорпионами}
{10037250}{}{торговца и его охранников}
{10037260}{}{останки белого кита}
{10037270}{}{большую каменную голову}
{10037280}{}{разбившийся шаттл}
{10037290}{}{Портал Хранителя}
{10037300}{}{рыцарей короля Артура}
{10037310}{}{железного дровосека}
{10037320}{}{немытых крестьян, гоняющихся за бродягой}
{10037330}{}{развалины дома}
{10037331}{}{странную пещеру}

# Encounter Table 15
{10037500}{}{шайку разбойников}
{10037510}{}{банду грабителей}
{10037520}{}{смешанную толпу грабителей и разбойников}
{10037530}{}{несколько золотых ящеров и группу рад-скорпионов}
{10037540}{}{охотников за бандитами}
{10037550}{}{охотников за бандитами}
{10037560}{}{охотников за бандитами}
{10037570}{}{охотников за бандитами}
{10037580}{}{охотников за бандитами}
{10037590}{}{охотников за бандитами}
{10037600}{}{охотников за бандитами}
{10037610}{}{охотников за бандитами}
{10037620}{}{толпу отщепенцев с братом Мортона  во главе}
{10037630}{}{семейство золотых ящеров}
{10037640}{}{семейство кротов-гризли}
{10037650}{}{большую группу рад-скорпионов}
{10037660}{}{целые заросли отвратительных хищных цветков}
{10037670}{}{банду грабителей, внезапно напавших на разбойничью шайку}
{10037680}{}{торговый караван, отбивающийся от атак разбойников}
{10037690}{}{группу торговцев, сражающихся с грабителями}
{10037700}{}{торговый караван, отражающий нападение рад-скорпионов}
{10037710}{}{стаю золотых ящеров, бьющихся с мерзкими рад-скорпионами}
{10037720}{}{торговца и его охранников}
{10037730}{}{человека, охраняющего мост}
{10037740}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 16
{10038000}{}{свалку ядовитых отбросов}
{10038010}{}{странную одинокую собаку}
{10038020}{}{стадо браминов}
{10038030}{}{группу рабов и работорговцев}
{10038040}{}{охотников за бандитами}
{10038050}{}{охотников за бандитами}
{10038060}{}{охотников за бандитами}
{10038070}{}{охотников за бандитами}
{10038080}{}{охотников за бандитами}
{10038090}{}{охотников за бандитами}
{10038100}{}{охотников за бандитами}
{10038110}{}{охотников за бандитами}
{10038120}{}{толпу отщепенцев с братом Мортона  во главе}
{10038130}{}{разбойничью шайку}
{10038140}{}{банду грабителей}
{10038150}{}{хитрых золотых ящеров, укрывающихся среди зарослей хищных цветков}
{10038160}{}{стаю рад-скорпионов и несколько кротов-гризли}
{10038170}{}{стайку рад-скорпионов}
{10038180}{}{группу кротов-гризли}
{10038190}{}{банду грабителей, атаковавшую из засады разбойничью шайку}
{10038200}{}{нескольких мерзавцев, пытающихся обратить людей в рабство}
{10038210}{}{работорговцев с товаром, подвергшихся нападению разбойников}
{10038220}{}{рабов и работорговцев, отбивающихся от голодных золотых ящеров}
{10038230}{}{каких-то людей, бьющихся с рад-скорпионами}
{10038240}{}{какой-то отряд}
{10038250}{}{останки белого кита}
{10038260}{}{большую каменную голову}
{10038270}{}{разбившийся шаттл}
{10038280}{}{Портал Хранителя}
{10038290}{}{рыцарей короля Артура}
{10038300}{}{железного дровосека}
{10038310}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 17
{10038500}{}{группу рабов и работорговцев}
{10038510}{}{разбойничью шайку}
{10038520}{}{банду грабителей}
{10038530}{}{хитрых золотых ящеров, укрывающихся среди зарослей хищных цветков}
{10038540}{}{охотников за бандитами}
{10038550}{}{охотников за бандитами}
{10038560}{}{охотников за бандитами}
{10038570}{}{охотников за бандитами}
{10038580}{}{охотников за бандитами}
{10038590}{}{охотников за бандитами}
{10038600}{}{охотников за бандитами}
{10038610}{}{охотников за бандитами}
{10038620}{}{толпу отщепенцев с братом Мортона  во главе}
{10038630}{}{стаю рад-скорпионов и несколько кротов-гризли}
{10038640}{}{стайку рад-скорпионов}
{10038650}{}{группу кротов-гризли}
{10038660}{}{банду грабителей, атаковавшую из засады разбойничью шайку}
{10038670}{}{нескольких мерзавцев, пытающихся обратить людей в рабство}
{10038680}{}{работорговцев с товаром, подвергшихся нападению разбойников}
{10038690}{}{рабов и работорговцев, отбивающихся от голодных золотых ящеров}
{10038700}{}{человека, охраняющего мост}
{10038710}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 18
{10039000}{}{нескольких грабителей и разбойников}
{10039010}{}{разбойничью шайку}
{10039020}{}{огромное стадо золотых ящеров}
{10039030}{}{несколько скорпионов, прячущихся среди хищных цветков}
{10039040}{}{охотников за бандитами}
{10039050}{}{охотников за бандитами}
{10039060}{}{охотников за бандитами}
{10039070}{}{охотников за бандитами}
{10039080}{}{охотников за бандитами}
{10039090}{}{охотников за бандитами}
{10039100}{}{охотников за бандитами}
{10039110}{}{охотников за бандитами}
{10039120}{}{толпу отщепенцев с братом Мортона  во главе}
{10039130}{}{разбойников, сражающихся со скорпионами}
{10039140}{}{отряд грабителей}
{10039150}{}{атакованный разбойниками торговый караван}
{10039160}{}{попавший в засаду бандитов торговый караван}
{10039170}{}{разбойников, оказавшихся в зарослях хищных цветков}
{10039180}{}{торговый караван}
{10039190}{}{человека, охраняющего мост}
{10039200}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 19
{10039500}{}{разбойничью шайку}
{10039510}{}{отряд грабителей}
{10039520}{}{группу бездомных бродяг}
{10039530}{}{несколько мантисов и золотых ящеров}
{10039540}{}{охотников за бандитами}
{10039550}{}{охотников за бандитами}
{10039560}{}{охотников за бандитами}
{10039570}{}{охотников за бандитами}
{10039580}{}{охотников за бандитами}
{10039590}{}{охотников за бандитами}
{10039600}{}{охотников за бандитами}
{10039610}{}{охотников за бандитами}
{10039620}{}{толпу отщепенцев с братом Мортона  во главе}
{10039630}{}{отбившихся от стада браминов}
{10039640}{}{группу скорпионов}
{10039650}{}{ватагу самогонщиков, сражающихся с разбойничьей шайкой}
{10039660}{}{нескольких разбойников, напавших на бездомных бродяг}
{10039670}{}{группу крестьян и самогонщиков}
{10039680}{}{мантисов, пытающихся навредить крестьянам}
{10039690}{}{самогонщиков, ввязавшихся в драку с крестьянами}
{10039700}{}{браминов, пытающихся отбиться от мантисов}
{10039710}{}{группу мантисов, атаковавших кротов-гризли}
{10039720}{}{ватагу самогонщиков}
{10039730}{}{нескольких крестьян}
{10039740}{}{стадо браминов}
{10039750}{}{человека, охраняющего мост}
{10039760}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 20
{10040000}{}{разбойников, идущих по чьему-то следу с собаками}
{10040010}{}{банду грабителей с обученными собаками}
{10040020}{}{отряд грабителей}
{10040030}{}{разбойничью шайку}
{10040040}{}{охотников за бандитами}
{10040050}{}{охотников за бандитами}
{10040060}{}{охотников за бандитами}
{10040070}{}{охотников за бандитами}
{10040080}{}{охотников за бандитами}
{10040090}{}{охотников за бандитами}
{10040100}{}{охотников за бандитами}
{10040110}{}{охотников за бандитами}
{10040120}{}{толпу отщепенцев с братом Мортона  во главе}
{10040130}{}{большую кучу мантисов, собравшуюся среди хищных цветков}
{10040140}{}{стаю одичавших собак, бродящую в зарослях хищных цветков}
{10040150}{}{целую тучу мантисов}
{10040160}{}{большую стаю диких собак}
{10040170}{}{грабителей, на которых напала собачья стая}
{10040180}{}{караван, атакованный одичавшими собаками}
{10040190}{}{караван, попавший в засаду грабителей}
{10040200}{}{караван, попавший в засаду разбойников}
{10040210}{}{караван}
{10040220}{}{человека, охраняющего мост}
{10040230}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 21
{10040500}{}{свалку ядовитых отбросов}
{10040510}{}{странную одинокую собаку}
{10040520}{}{стадо браминов}
{10040530}{}{разбойников, идущих по чьему-то следу с собаками}
{10040540}{}{охотников за бандитами}
{10040550}{}{охотников за бандитами}
{10040560}{}{охотников за бандитами}
{10040570}{}{охотников за бандитами}
{10040580}{}{охотников за бандитами}
{10040590}{}{охотников за бандитами}
{10040600}{}{охотников за бандитами}
{10040610}{}{охотников за бандитами}
{10040620}{}{толпу отщепенцев с братом Мортона  во главе}
{10040630}{}{банду грабителей с обученными собаками}
{10040640}{}{банду грабителей}
{10040650}{}{разбойничью шайку}
{10040660}{}{большую кучу мантисов, собравшуюся среди хищных цветков}
{10040670}{}{стаю одичавших собак, бродящую в зарослях хищных цветков}
{10040680}{}{целую тучу мантисов}
{10040690}{}{большую стаю диких собак}
{10040700}{}{грабителей, на которых напала собачья стая}
{10040710}{}{караван, атакованный одичавшими собаками}
{10040720}{}{караван, попавший в засаду грабителей}
{10040730}{}{караван, попавший в засаду разбойников}
{10040740}{}{караван}
{10040750}{}{останки белого кита}
{10040760}{}{большую каменную голову}
{10040770}{}{разбившийся шаттл}
{10040780}{}{Портал Хранителя}
{10040790}{}{рыцарей короля Артура}
{10040800}{}{железного дровосека}
{10040810}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 22
{10041000}{}{немного золотых ящеров}
{10041010}{}{целую тучу мантисов}
{10041020}{}{несколько рад-скорпионов}
{10041030}{}{отбившихся от стада браминов}
{10041040}{}{охотников за бандитами}
{10041050}{}{охотников за бандитами}
{10041060}{}{охотников за бандитами}
{10041070}{}{охотников за бандитами}
{10041080}{}{охотников за бандитами}
{10041090}{}{охотников за бандитами}
{10041100}{}{охотников за бандитами}
{10041110}{}{охотников за бандитами}
{10041120}{}{толпу отщепенцев с братом Мортона  во главе}
{10041130}{}{торговца и его охранников, бьющихся с золотыми ящерами}
{10041140}{}{огромные тучи мантисов, окруживших торговый караван}
{10041150}{}{отвратительных мантисов, напавших на диких браминов}
{10041160}{}{рад-скорпионов, решивших поживиться мантисами}
{10041170}{}{несколько рад-скорпионов, убивающих одичавших браминов}
{10041180}{}{торговца и его охранников}
{10041190}{}{человека, охраняющего мост}
{10041200}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 23
{10041500}{}{свалку ядовитых отбросов}
{10041510}{}{странную одинокую собаку}
{10041520}{}{стадо браминов}
{10041530}{}{немного золотых ящеров}
{10041540}{}{охотников за бандитами}
{10041550}{}{охотников за бандитами}
{10041560}{}{охотников за бандитами}
{10041570}{}{охотников за бандитами}
{10041580}{}{охотников за бандитами}
{10041590}{}{охотников за бандитами}
{10041600}{}{охотников за бандитами}
{10041610}{}{охотников за бандитами}
{10041620}{}{толпу отщепенцев с братом Мортона  во главе}
{10041630}{}{целую тучу мантисов}
{10041640}{}{немного рад-скорпионов}
{10041650}{}{одичавших браминов}
{10041660}{}{торговца и его охранников, воюющих с золотыми ящерами}
{10041670}{}{огромные тучи мантисов, окруживших торговый караван}
{10041680}{}{отвратительных мантисов, напавших на диких браминов}
{10041690}{}{рад-скорпионов, решивших поживиться мантисами}
{10041700}{}{несколько рад-скорпионов, убивающих одичавших браминов}
{10041710}{}{торговца и его охранников}
{10041720}{}{останки белого кита}
{10041730}{}{большую каменную голову}
{10041740}{}{разбившийся шаттл}
{10041750}{}{Портал Хранителя}
{10041760}{}{рыцарей короля Артура}
{10041770}{}{железного дровосека}
{10041780}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 24
{10042000}{}{свалку ядовитых отбросов}
{10042010}{}{странную одинокую собаку}
{10042020}{}{стадо браминов}
{10042030}{}{мутировавших кротов-гризли}
{10042040}{}{охотников за бандитами}
{10042050}{}{охотников за бандитами}
{10042060}{}{охотников за бандитами}
{10042070}{}{охотников за бандитами}
{10042080}{}{охотников за бандитами}
{10042090}{}{охотников за бандитами}
{10042100}{}{охотников за бандитами}
{10042110}{}{охотников за бандитами}
{10042120}{}{толпу отщепенцев с братом Мортона  во главе}
{10042130}{}{мутировавших крысо-кабанов}
{10042140}{}{несколько хищных цветков}
{10042150}{}{отшельника и его собак, бьющихся с мутировавшими кротами-гризли}
{10042160}{}{отшельника, сражающегося с дикими собаками}
{10042170}{}{отшельника, схватившегося с мутировавшими крысо-кабанами}
{10042180}{}{отшельника и собак, бьющихся с мутировавшими кротами-гризли}
{10042190}{}{мутировавших кротов-гризли, напавших на таких же крысо-кабанов}
{10042200}{}{мутировавших кротов-гризли, воюющих с хищными цветками}
{10042210}{}{мутировавших крысо-кабанов, отбивающихся от диких собак}
{10042220}{}{отшельника}
{10042230}{}{останки белого кита}
{10042240}{}{большую каменную голову}
{10042250}{}{разбившийся шаттл}
{10042260}{}{Портал Хранителя}
{10042270}{}{рыцарей короля Артура}
{10042280}{}{железного дровосека}
{10042290}{}{немытых крестьян, гоняющихся за бродягой}
{10042300}{}{секретное логово супермутантов}

# Encounter Table 25
{10042500}{}{мутировавших кротов-гризли}
{10042510}{}{мутировавших крысо-кабанов}
{10042520}{}{несколько хищных цветков}
{10042530}{}{отшельника и собак, бьющихся с мутировавшими кротами-гризли}
{10042540}{}{охотников за бандитами}
{10042550}{}{охотников за бандитами}
{10042560}{}{охотников за бандитами}
{10042570}{}{охотников за бандитами}
{10042580}{}{охотников за бандитами}
{10042590}{}{охотников за бандитами}
{10042600}{}{охотников за бандитами}
{10042610}{}{охотников за бандитами}
{10042620}{}{толпу отщепенцев с братом Мортона  во главе}
{10042630}{}{отшельника, сражающегося с дикими собаками}
{10042640}{}{отшельника, схватившегося с мутировавшими крысо-кабанами}
{10042650}{}{отшельника и собак, бьющихся с мутировавшими кротами-гризли}
{10042660}{}{мутировавших кротов-гризли, напавших на таких же крысо-кабанов}
{10042670}{}{мутировавших кротов-гризли, воюющих с хищными цветками}
{10042680}{}{мутировавших крысо-кабанов, отбивающихся от диких собак}
{10042690}{}{отшельника}
{10042700}{}{человека, охраняющего мост}
{10042710}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 26
{10043000}{}{команду работорговцев с собаками}
{10043010}{}{банду работорговцев}
{10043020}{}{несколько золотых ящеров}
{10043030}{}{большую стаю диких собак}
{10043040}{}{охотников за бандитами}
{10043050}{}{охотников за бандитами}
{10043060}{}{охотников за бандитами}
{10043070}{}{охотников за бандитами}
{10043080}{}{охотников за бандитами}
{10043090}{}{охотников за бандитами}
{10043100}{}{охотников за бандитами}
{10043110}{}{охотников за бандитами}
{10043120}{}{толпу отщепенцев с братом Мортона  во главе}
{10043130}{}{патрульный отряд с собаками, гоняющий работорговцев}
{10043140}{}{банду работорговцев, отбивающихся от золотых ящеров}
{10043150}{}{солдат патруля, сражающихся с работорговцами}
{10043160}{}{патрульную команду, воюющую с золотыми ящерами}
{10043170}{}{патруль, отражающий нападение диких собак}
{10043180}{}{патрульный отряд}
{10043190}{}{человека, охраняющего мост}
{10043200}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 27
{10043500}{}{свалку ядовитых отходов}
{10043510}{}{странную одинокую собаку}
{10043520}{}{стадо браминов}
{10043530}{}{команду работорговцев с собаками}
{10043540}{}{охотников за бандитами}
{10043550}{}{охотников за бандитами}
{10043560}{}{охотников за бандитами}
{10043570}{}{охотников за бандитами}
{10043580}{}{охотников за бандитами}
{10043590}{}{охотников за бандитами}
{10043600}{}{охотников за бандитами}
{10043610}{}{охотников за бандитами}
{10043620}{}{толпу отщепенцев с братом Мортона  во главе}
{10043630}{}{банду работорговцев}
{10043640}{}{несколько золотых ящеров}
{10043650}{}{большую стаю диких собак}
{10043660}{}{патрульный отряд с собаками, гоняющий работорговцев}
{10043670}{}{банду работорговцев, отбивающихся от золотых ящеров}
{10043680}{}{солдат патруля, сражающихся с работорговцами}
{10043690}{}{патрульную команду, воюющую с золотыми ящерами}
{10043700}{}{патруль, отражающий нападение диких собак}
{10043710}{}{патрульный отряд}
{10043720}{}{останки белого кита}
{10043730}{}{большую каменную голову}
{10043740}{}{разбившийся шаттл}
{10043750}{}{Портал Хранителя}
{10043760}{}{рыцарей короля Артура}
{10043770}{}{железного дровосека}
{10043780}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 28
{10044000}{}{кучку жалких побирушек}
{10044010}{}{несколько призраков-побирушек}
{10044020}{}{большую толпу бесноватых}
{10044030}{}{немного бесноватых призраков}
{10044040}{}{охотников за бандитами}
{10044050}{}{охотников за бандитами}
{10044060}{}{охотников за бандитами}
{10044070}{}{охотников за бандитами}
{10044080}{}{охотников за бандитами}
{10044090}{}{охотников за бандитами}
{10044100}{}{охотников за бандитами}
{10044110}{}{охотников за бандитами}
{10044120}{}{толпу отщепенцев с братом Мортона  во главе}
{10044130}{}{кучку ящеров}
{10044140}{}{стаю одичавших собак}
{10044150}{}{большое семейство рад-скорпионов}
{10044160}{}{стадо мутировавших крысо-кабанов}
{10044170}{}{стадо мутировавших грызунов}
{10044180}{}{группу ничтожных побирушек, дерущуюся с бесноватыми}
{10044190}{}{несколько призраков-побирушек, бьющихся с бесноватыми}
{10044200}{}{группу ящеров, пытающихся пообедать бесноватыми}
{10044210}{}{мутировавших грызунов, мешающих существовать призракам}
{10044220}{}{человека, охраняющего мост}
{10044230}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 29
{10044500}{}{свалку токсичных отходов}
{10044510}{}{странную одинокую собаку}
{10044520}{}{стадо браминов}
{10044530}{}{кучку жалких побирушек}
{10044540}{}{охотников за бандитами}
{10044550}{}{охотников за бандитами}
{10044560}{}{охотников за бандитами}
{10044570}{}{охотников за бандитами}
{10044580}{}{охотников за бандитами}
{10044590}{}{охотников за бандитами}
{10044600}{}{охотников за бандитами}
{10044610}{}{охотников за бандитами}
{10044620}{}{толпу отщепенцев с братом Мортона  во главе}
{10044630}{}{несколько призраков-побирушек}
{10044640}{}{большую толпу бесноватых}
{10044650}{}{немного бесноватых призраков}
{10044660}{}{несколько ящеров}
{10044670}{}{большую стаю диких собак}
{10044680}{}{крупное семейство рад-скорпионов}
{10044690}{}{целую стаю мутировавших крысо-кабанов}
{10044700}{}{стадо мутировавших грызунов}
{10044710}{}{группу ничтожных побирушек, дерущуюся с бесноватыми}
{10044720}{}{несколько призраков-побирушек, бьющихся с бесноватыми}
{10044730}{}{группу ящеров, пытающихся пообедать бесноватыми}
{10044740}{}{мутировавших грызунов, мешающих существовать призракам}
{10044750}{}{останки белого кита}
{10044760}{}{большую каменную голову}
{10044770}{}{разбившийся шаттл}
{10044780}{}{Портал Хранителя}
{10044790}{}{рыцарей короля Артура}
{10044800}{}{железного дровосека}
{10044810}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 30
{10045000}{}{несколько каннибалов}
{10045010}{}{немного дикарей}
{10045020}{}{группу воинов}
{10045030}{}{небольшую кучку изгоев}
{10045040}{}{охотников за бандитами}
{10045050}{}{охотников за бандитами}
{10045060}{}{охотников за бандитами}
{10045070}{}{охотников за бандитами}
{10045080}{}{охотников за бандитами}
{10045090}{}{охотников за бандитами}
{10045100}{}{охотников за бандитами}
{10045110}{}{охотников за бандитами}
{10045120}{}{толпу отщепенцев с братом Мортона  во главе}
{10045130}{}{крупное семейство рад-скорпионов}
{10045140}{}{несколько кротов-гризли}
{10045150}{}{группу рыбаков, пытающихся отогнать каннибалов}
{10045160}{}{нескольких каннибалов, сражающихся с дикарями}
{10045170}{}{стайку рад-скорпионов, жаждущих мяса дикарей}
{10045180}{}{местных рыбаков}

# Encounter Table 31
{10045500}{}{свалку ядовитых отходов}
{10045510}{}{странную одинокую собаку}
{10045520}{}{стадо браминов}
{10045530}{}{несколько каннибалов}
{10045540}{}{охотников за бандитами}
{10045550}{}{охотников за бандитами}
{10045560}{}{охотников за бандитами}
{10045570}{}{охотников за бандитами}
{10045580}{}{охотников за бандитами}
{10045590}{}{охотников за бандитами}
{10045600}{}{охотников за бандитами}
{10045610}{}{охотников за бандитами}
{10045620}{}{толпу отщепенцев с братом Мортона  во главе}
{10045630}{}{отбросы общества}
{10045640}{}{группу дикарей}
{10045650}{}{отряд воинов}
{10045660}{}{кучку ящеров, прячущихся среди хищных цветков}
{10045670}{}{каких-то ящеров и несколько рад-скорпионов}
{10045680}{}{стайку ящеров}
{10045690}{}{рад-скорпионов, скрывающихся от правосудия среди хищных цветков}
{10045700}{}{группу скорпионов}
{10045710}{}{ящеров, напавших на оборванных бродяг}
{10045720}{}{дикарей, сражающихся со злобными ящерами}
{10045730}{}{каннибалов, пытающихся отведать мясца рад-скорпионов}
{10045740}{}{рад-скорпионов, напавших на местного отшельника}
{10045750}{}{отшельника}
{10045760}{}{останки белого кита}
{10045770}{}{большую каменную голову}
{10045780}{}{разбившийся шаттл}
{10045790}{}{Портал Хранителя}
{10045800}{}{рыцарей короля Артура}
{10045810}{}{железного дровосека}
{10045820}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 32
{10046000}{}{группу каннибалов}
{10046010}{}{несколько изгоев}
{10046020}{}{отряд дикарей}
{10046030}{}{местных воителей}
{10046040}{}{охотников за бандитами}
{10046050}{}{охотников за бандитами}
{10046060}{}{охотников за бандитами}
{10046070}{}{охотников за бандитами}
{10046080}{}{охотников за бандитами}
{10046090}{}{охотников за бандитами}
{10046100}{}{охотников за бандитами}
{10046110}{}{охотников за бандитами}
{10046120}{}{толпу отщепенцев с братом Мортона  во главе}
{10046130}{}{кучку ящеров, прячущихся среди хищных цветков}
{10046140}{}{каких-то ящеров и несколько рад-скорпионов}
{10046150}{}{стайку ящеров}
{10046160}{}{рад-скорпионов, скрывающихся от правосудия среди хищных цветков}
{10046170}{}{группу скорпионов}
{10046180}{}{ящеров, напавших на оборванных бродяг}
{10046190}{}{дикарей, сражающихся со злобными ящерами}
{10046200}{}{каннибалов, пытающихся отведать мясца рад-скорпионов}
{10046210}{}{рад-скорпионов, напавших на местного отшельника}
{10046220}{}{отшельника}
{10046230}{}{человека, охраняющего мост}
{10046240}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 33
{10046500}{}{свалку ядовитых отходов}
{10046510}{}{странную одинокую собаку}
{10046520}{}{стадо браминов}
{10046530}{}{караван из Ямы}
{10046540}{}{охотников за бандитами}
{10046550}{}{охотников за бандитами}
{10046560}{}{охотников за бандитами}
{10046570}{}{охотников за бандитами}
{10046580}{}{охотников за бандитами}
{10046590}{}{охотников за бандитами}
{10046600}{}{охотников за бандитами}
{10046610}{}{охотников за бандитами}
{10046620}{}{толпу отщепенцев с братом Мортона  во главе}
{10046630}{}{большой отряд грабителей и бандитов}
{10046640}{}{несколько грабителей}
{10046650}{}{группу бандитов}
{10046660}{}{караван из Реддинга, отбивающийся от атаки бандитов}
{10046670}{}{караван из Нью-Рено, обороняющийся от грабителей}
{10046680}{}{караван из Ямы, попавший в бандитскую засаду}
{10046690}{}{разбойничий налет на какой-то караван}
{10046700}{}{торговцев из Ямы, желающих поживиться за счет Города}
{10046710}{}{междоусобную разборку бандитов и грабителей}
{10046720}{}{торговый караван из Города}
{10046730}{}{торговцев из Ямы}
{10046740}{}{останки белого кита}
{10046750}{}{большую каменную голову}
{10046760}{}{разбившийся шаттл}
{10046770}{}{Портал Хранителя}
{10046780}{}{рыцарей короля Артура}
{10046790}{}{железного дровосека}
{10046800}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 34
{10047000}{}{торговцев из Ямы}
{10047010}{}{целую кучу грабителей и бандитов}
{10047020}{}{разбойничью шайку}
{10047030}{}{бандитскую группу}
{10047040}{}{охотников за бандитами}
{10047050}{}{охотников за бандитами}
{10047060}{}{охотников за бандитами}
{10047070}{}{охотников за бандитами}
{10047080}{}{охотников за бандитами}
{10047090}{}{охотников за бандитами}
{10047100}{}{охотников за бандитами}
{10047110}{}{охотников за бандитами}
{10047120}{}{толпу отщепенцев с братом Мортона  во главе}
{10047130}{}{караван из Реддинга, отбивающийся от атаки бандитов}
{10047140}{}{караван из Нью-Рено, обороняющийся от грабителей}
{10047150}{}{караван из Ямы, попавший в бандитскую засаду}
{10047160}{}{разбойничий налет на какой-то караван}
{10047170}{}{торговцев из Ямы, желающих поживиться за счет Города}
{10047180}{}{междоусобную разборку бандитов и грабителей}
{10047190}{}{торговый караван из Города}
{10047200}{}{торговцев из Ямы}
{10047210}{}{человека, охраняющего мост}
{10047220}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 35
{10047500}{}{свалку ядовитых отходов}
{10047510}{}{странную одинокую собаку}
{10047520}{}{стадо браминов}
{10047530}{}{кучку ящеров и некоторое количество волков}
{10047540}{}{охотников за бандитами}
{10047550}{}{охотников за бандитами}
{10047560}{}{охотников за бандитами}
{10047570}{}{охотников за бандитами}
{10047580}{}{охотников за бандитами}
{10047590}{}{охотников за бандитами}
{10047600}{}{охотников за бандитами}
{10047610}{}{охотников за бандитами}
{10047620}{}{толпу отщепенцев с братом Мортона  во главе}
{10047630}{}{сообщество мародеров}
{10047640}{}{опасную волчью стаю}
{10047650}{}{мерзостных ящеров}
{10047660}{}{артель рудокопов, не поделивших территорию с мародерами}
{10047670}{}{трапперов, решивших ободрать парочку ящеров}
{10047680}{}{напавшую на спиртоносов стаю голодных волков}
{10047690}{}{поселенцев, охраняющих свои земли от шайки мародеров}
{10047700}{}{местных жителей, вставших на пути волчьей стаи}
{10047710}{}{несколько спиртоносов}
{10047720}{}{отряд трапперов}
{10047730}{}{артель рудокопов}
{10047740}{}{останки белого кита}
{10047750}{}{большую каменную голову}
{10047760}{}{разбившийся шаттл}
{10047770}{}{Портал Хранителя}
{10047780}{}{рыцарей короля Артура}
{10047790}{}{железного дровосека}
{10047800}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 36
{10048000}{}{кучку ящеров и некоторое количество волков}
{10048010}{}{сообщество мародеров}
{10048020}{}{опасную волчью стаю}
{10048030}{}{несколько ящеров}
{10048040}{}{охотников за бандитами}
{10048050}{}{охотников за бандитами}
{10048060}{}{охотников за бандитами}
{10048070}{}{охотников за бандитами}
{10048080}{}{охотников за бандитами}
{10048090}{}{охотников за бандитами}
{10048100}{}{охотников за бандитами}
{10048110}{}{охотников за бандитами}
{10048120}{}{толпу отщепенцев с братом Мортона  во главе}
{10048130}{}{артель рудокопов, не поделивших территорию с мародерами}
{10048140}{}{трапперов, решивших ободрать парочку ящеров}
{10048150}{}{напавшую на спиртоносов стаю голодных волков}
{10048160}{}{поселенцев, охраняющих свои земли от шайки мародеров}
{10048170}{}{местных жителей, вставших на пути волчьей стаи}
{10048180}{}{группу спиртоносов}
{10048190}{}{несколько трапперов}
{10048200}{}{артель старателей}
{10048210}{}{человека, охраняющего мост}
{10048220}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 37
{10048500}{}{волчью стаю, усиленную голодными кротами-гризли}
{10048510}{}{несколько рад-скорпионов и кучку волков}
{10048520}{}{мутировавших кротов-гризли и беснующихся рад-скорпионов}
{10048530}{}{стайку каких-то ящеров}
{10048540}{}{охотников за бандитами}
{10048550}{}{охотников за бандитами}
{10048560}{}{охотников за бандитами}
{10048570}{}{охотников за бандитами}
{10048580}{}{охотников за бандитами}
{10048590}{}{охотников за бандитами}
{10048600}{}{охотников за бандитами}
{10048610}{}{охотников за бандитами}
{10048620}{}{толпу отщепенцев с братом Мортона  во главе}
{10048630}{}{опасную волчью стаю}
{10048640}{}{мутировавших и отощавших кротов-гризли}
{10048650}{}{большую кучу рад-скорпионов}
{10048660}{}{охотящихся на кого-то волков и ящеров}
{10048670}{}{мутировавших кротов-гризли, дерущихся с ящерами}
{10048680}{}{рад-скорпионов, пытающихся сожрать кротов-гризли}
{10048690}{}{человека, охраняющего мост}
{10048700}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 38
{10049000}{}{разбойничью шайку}
{10049010}{}{волчью стаю}
{10049020}{}{караван, наткнувшийся на банду грабителей}
{10049030}{}{караван, наткнувшийся на банду грабителей}
{10049040}{}{охотников за бандитами}
{10049050}{}{охотников за бандитами}
{10049060}{}{охотников за бандитами}
{10049070}{}{охотников за бандитами}
{10049080}{}{охотников за бандитами}
{10049090}{}{охотников за бандитами}
{10049100}{}{охотников за бандитами}
{10049110}{}{охотников за бандитами}
{10049120}{}{толпу отщепенцев с братом Мортона  во главе}
{10049130}{}{караван, наткнувшийся на банду грабителей}
{10049140}{}{караван, наткнувшийся на банду грабителей}
{10049150}{}{караван}
{10049160}{}{караван}
{10049170}{}{караван}
{10049180}{}{караван}
{10049190}{}{человека, охраняющего мост}
{10049200}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 39
{10049500}{}{свалку ядовитых отбросов}
{10049510}{}{странную одинокую собаку}
{10049520}{}{стадо браминов}
{10049530}{}{разбойничью шайку}
{10049540}{}{охотников за бандитами}
{10049550}{}{охотников за бандитами}
{10049560}{}{охотников за бандитами}
{10049570}{}{охотников за бандитами}
{10049580}{}{охотников за бандитами}
{10049590}{}{охотников за бандитами}
{10049600}{}{охотников за бандитами}
{10049610}{}{охотников за бандитами}
{10049620}{}{толпу отщепенцев с братом Мортона  во главе}
{10049630}{}{волчью стаю}
{10049640}{}{караван, наткнувшийся на банду грабителей}
{10049650}{}{караван, наткнувшийся на банду грабителей}
{10049660}{}{караван, наткнувшийся на банду грабителей}
{10049670}{}{караван, наткнувшийся на банду грабителей}
{10049680}{}{караван}
{10049690}{}{караван}
{10049700}{}{караван}
{10049710}{}{караван}
{10049720}{}{останки белого кита}
{10049730}{}{большую каменную голову}
{10049740}{}{разбившийся шаттл}
{10049750}{}{Портал Хранителя}
{10049760}{}{рыцарей короля Артура}
{10049770}{}{железного дровосека}
{10049780}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 40
{10050000}{}{банду грабителей, идущих по следу с собаками}
{10050010}{}{заросли хищных цветков и группу волков}
{10050020}{}{разбойничью шайку}
{10050030}{}{опасную волчью стаю}
{10050040}{}{охотников за бандитами}
{10050050}{}{охотников за бандитами}
{10050060}{}{охотников за бандитами}
{10050070}{}{охотников за бандитами}
{10050080}{}{охотников за бандитами}
{10050090}{}{охотников за бандитами}
{10050100}{}{охотников за бандитами}
{10050110}{}{охотников за бандитами}
{10050120}{}{толпу отщепенцев с братом Мортона  во главе}
{10050130}{}{большую группу рад-скорпионов}
{10050140}{}{разбойников, встретившихся с тощими и злыми волками}
{10050150}{}{человека, охраняющего мост}
{10050160}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 41
{10050500}{}{свалку ядовитых отходов}
{10050510}{}{странную одинокую собаку}
{10050520}{}{стадо браминов}
{10050530}{}{банду грабителей, идущих по следу с собаками}
{10050540}{}{охотников за бандитами}
{10050550}{}{охотников за бандитами}
{10050560}{}{охотников за бандитами}
{10050570}{}{охотников за бандитами}
{10050580}{}{охотников за бандитами}
{10050590}{}{охотников за бандитами}
{10050600}{}{охотников за бандитами}
{10050610}{}{охотников за бандитами}
{10050620}{}{толпу отщепенцев с братом Мортона  во главе}
{10050630}{}{заросли хищных цветков и группу волков}
{10050640}{}{разбойничью шайку}
{10050650}{}{опасную волчью стаю}
{10050660}{}{немалое количество рад-скорпионов}
{10050670}{}{разбойников, встретившихся с тощими и злыми волками}
{10050680}{}{останки белого кита}
{10050690}{}{большую каменную голову}
{10050700}{}{разбившийся шаттл}
{10050710}{}{Портал Хранителя}
{10050720}{}{рыцарей короля Артура}
{10050730}{}{железного дровосека}
{10050740}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 42
{10051000}{}{свалку ядовитых отходов}
{10051010}{}{странную одинокую собаку}
{10051020}{}{стадо браминов}
{10051030}{}{вооруженный патруль АНКЛАВА}
{10051040}{}{охотников за бандитами}
{10051050}{}{охотников за бандитами}
{10051060}{}{охотников за бандитами}
{10051070}{}{охотников за бандитами}
{10051080}{}{охотников за бандитами}
{10051090}{}{охотников за бандитами}
{10051100}{}{охотников за бандитами}
{10051110}{}{охотников за бандитами}
{10051120}{}{толпу отщепенцев с братом Мортона  во главе}
{10051130}{}{останки белого кита}
{10051140}{}{большую каменную голову}
{10051150}{}{разбившийся шаттл}
{10051160}{}{Портал Хранителя}
{10051170}{}{рыцарей короля Артура}
{10051180}{}{железного дровосека}
{10051190}{}{немытых крестьян, гоняющихся за бродягой}
{10051200}{}{кафе Разбитых Мечтаний}

# Encounter Table 43
{10051500}{}{вооруженный патруль АНКЛАВА}
{10051510}{}{охотников за бандитами}
{10051520}{}{охотников за бандитами}
{10051530}{}{охотников за бандитами}
{10051540}{}{охотников за бандитами}
{10051550}{}{охотников за бандитами}
{10051560}{}{охотников за бандитами}
{10051570}{}{охотников за бандитами}
{10051580}{}{охотников за бандитами}
{10051590}{}{толпу отщепенцев с братом Мортона  во главе}
{10051600}{}{человека, охраняющего мост}
{10051610}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 44
{10052000}{}{вооруженный патруль АНКЛАВА}
{10052010}{}{охотников за бандитами}
{10052020}{}{охотников за бандитами}
{10052030}{}{охотников за бандитами}
{10052040}{}{охотников за бандитами}
{10052080}{}{охотников за бандитами}
{10052090}{}{охотников за бандитами}
{10052100}{}{охотников за бандитами}
{10052110}{}{охотников за бандитами}
{10052120}{}{толпу отщепенцев с братом Мортона  во главе}

# Encounter Table 45
{10052500}{}{свалку ядовитых отходов}
{10052510}{}{странную одинокую собаку}
{10052520}{}{стадо браминов}
{10052530}{}{кучку инопланетян и когтей смерти}
{10052540}{}{охотников за бандитами}
{10052550}{}{охотников за бандитами}
{10052560}{}{охотников за бандитами}
{10052570}{}{охотников за бандитами}
{10052580}{}{охотников за бандитами}
{10052590}{}{охотников за бандитами}
{10052600}{}{охотников за бандитами}
{10052610}{}{охотников за бандитами}
{10052620}{}{толпу отщепенцев с братом Мортона  во главе}
{10052630}{}{целую армию летателей и псевдо-кентавров}
{10052640}{}{огнедышащих ящеров}
{10052650}{}{большую толпу инопланетных туристов}
{10052660}{}{несколько когтей смерти}
{10052670}{}{кучку огнедышащих ящеров}
{10052680}{}{группу инопланетян}
{10052690}{}{табун псевдо-кентавров}
{10052700}{}{крупный выводок летателей}
{10052710}{}{останки белого кита}
{10052720}{}{большую каменную голову}
{10052730}{}{разбившийся шаттл}
{10052740}{}{Портал Хранителя}
{10052750}{}{рыцарей короля Артура}
{10052760}{}{железного дровосека}
{10052770}{}{немытых крестьян, гоняющихся за бродягой}
{10052780}{}{кафе Разбитых Мечтаний}

# Encounter Table 46
{10053000}{}{кучку инопланетян и когтей смерти}
{10053010}{}{целую армию летателей и псевдо-кентавров}
{10053020}{}{несколько огнедышащих ящеров}
{10053030}{}{большую толпу инопланетных туристов}
{10053040}{}{охотников за бандитами}
{10053050}{}{охотников за бандитами}
{10053060}{}{охотников за бандитами}
{10053070}{}{охотников за бандитами}
{10053080}{}{охотников за бандитами}
{10053090}{}{охотников за бандитами}
{10053100}{}{охотников за бандитами}
{10053110}{}{охотников за бандитами}
{10053120}{}{толпу отщепенцев с братом Мортона  во главе}
{10053130}{}{группу когтей смерти}
{10053140}{}{несколько огнедышащих ящеров}
{10053150}{}{кучку инопланетян}
{10053160}{}{табун псевдо-кентавров}
{10053170}{}{крупный выводок летателей}
{10053180}{}{человека, охраняющего мост}
{10053190}{}{рыцарей короля Артура, воюющих с грызуном}
{10053200}{}{странный одинокий дом}
{10053210}{}{тот самый военный склад, о котором вы слышали по радио}


# Encounter Table 47
{10053500}{}{кучку инопланетян и когтей смерти}
{10053510}{}{целую армию летателей и псевдо-кентавров}
{10053520}{}{несколько огнедышащих ящеров}
{10053530}{}{большую толпу инопланетных туристов}
{10053540}{}{охотников за бандитами}
{10053550}{}{охотников за бандитами}
{10053560}{}{охотников за бандитами}
{10053570}{}{охотников за бандитами}
{10053580}{}{охотников за бандитами}
{10053590}{}{охотников за бандитами}
{10053600}{}{охотников за бандитами}
{10053610}{}{охотников за бандитами}
{10053620}{}{толпу отщепенцев с братом Мортона  во главе}
{10053630}{}{несколько когтей смерти}
{10053640}{}{стайку огнедышащих ящеров}
{10053650}{}{кучку инопланетян}
{10053660}{}{табун псевдо-кентавров}
{10053670}{}{крупный выводок летателей}

# Encounter Table 48
{10054000}{}{свалку ядовитых отходов}
{10054010}{}{странную одинокую собаку}
{10054020}{}{стадо браминов}
{10054030}{}{большую кучу огнедышащих ящеров}
{10054040}{}{охотников за бандитами}
{10054050}{}{охотников за бандитами}
{10054060}{}{охотников за бандитами}
{10054070}{}{охотников за бандитами}
{10054080}{}{охотников за бандитами}
{10054090}{}{охотников за бандитами}
{10054100}{}{охотников за бандитами}
{10054110}{}{охотников за бандитами}
{10054120}{}{толпу отщепенцев с братом Мортона  во главе}
{10054130}{}{стаю нелепых огнедышащих ящеров}
{10054140}{}{невероятное множество золотых ящеров}
{10054150}{}{останки белого кита}
{10054160}{}{большую каменную голову}
{10054170}{}{разбившийся шаттл}
{10054180}{}{Портал Хранителя}
{10054190}{}{рыцарей короля Артура}
{10054200}{}{железного дровосека}
{10054210}{}{немытых крестьян, гоняющихся за бродягой}
{10054220}{}{кафе Разбитых Мечтаний}
{10054230}{}{заброшенную лабораторию безумного ученого}
{10054240}{}{заброшенный аванпост Рыцарей Пустоши}
{10054250}{}{заброшенный склад пончиков}
{10054260}{}{разрушенную церковь}

# Encounter Table 49
{10054500}{}{стаю нелепых огнедышащих ящеров}
{10054510}{}{большую кучу огнедышащих ящеров}
{10054520}{}{невероятное множество золотых ящеров}
{10054530}{}{охотников за бандитами}
{10054540}{}{охотников за бандитами}
{10054550}{}{охотников за бандитами}
{10054560}{}{охотников за бандитами}
{10054570}{}{охотников за бандитами}
{10054580}{}{охотников за бандитами}
{10054590}{}{охотников за бандитами}
{10054600}{}{охотников за бандитами}
{10054610}{}{толпу отщепенцев с братом Мортона  во главе}
{10054620}{}{человека, охраняющего мост}
{10054630}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 50
{10055000}{}{небольшую кучку огнедышащих ящеров}
{10055010}{}{крупную стаю огнедышащих ящеров}
{10055020}{}{невероятное множество золотых ящеров}
{10055030}{}{охотников за бандитами}
{10055040}{}{охотников за бандитами}
{10055050}{}{охотников за бандитами}
{10055060}{}{охотников за бандитами}
{10055070}{}{охотников за бандитами}
{10055080}{}{охотников за бандитами}
{10055090}{}{охотников за бандитами}
{10055100}{}{охотников за бандитами}
{10055110}{}{толпу отщепенцев с братом Мортона  во главе}

# Encounter Table 51
{10055500}{}{свалку ядовитых отходов}
{10055510}{}{странную одинокую собаку}
{10055520}{}{стадо браминов}
{10055530}{}{большую кучу когтей смерти}
{10055540}{}{охотников за бандитами}
{10055550}{}{охотников за бандитами}
{10055560}{}{охотников за бандитами}
{10055570}{}{охотников за бандитами}
{10055580}{}{охотников за бандитами}
{10055590}{}{охотников за бандитами}
{10055600}{}{охотников за бандитами}
{10055610}{}{охотников за бандитами}
{10055620}{}{толпу отщепенцев с братом Мортона  во главе}
{10055630}{}{крупную стаю огнедышащих ящеров}
{10055640}{}{торговцев из каравана, бьющихся со когтями смерти}
{10055650}{}{торговцев из каравана, бьющихся со когтями смерти}
{10055660}{}{напавших на караван огнедышащих ящеров}
{10055670}{}{напавших на караван огнедышащих ящеров}
{10055680}{}{караван}
{10055690}{}{караван}
{10055700}{}{караван}
{10055710}{}{караван}
{10055720}{}{останки белого кита}
{10055730}{}{большую каменную голову}
{10055740}{}{разбившийся шаттл}
{10055750}{}{Портал Хранителя}
{10055760}{}{рыцарей короля Артура}
{10055770}{}{железного дровосека}
{10055780}{}{немытых крестьян, гоняющихся за бродягой}
{10055790}{}{заброшенную лабораторию безумного ученого}
{10055800}{}{заброшенный аванпост Рыцарей Пустоши}
{10055810}{}{заброшенный склад пончиков}

# Encounter Table 52
{10056000}{}{большую группу когтей смерти}
{10056010}{}{стайку огнедышащих ящеров}
{10056020}{}{торговцев из каравана, бьющихся со когтями смерти}
{10056030}{}{торговцев из каравана, бьющихся со когтями смерти}
{10056040}{}{охотников за бандитами}
{10056050}{}{охотников за бандитами}
{10056060}{}{охотников за бандитами}
{10056070}{}{охотников за бандитами}
{10056080}{}{охотников за бандитами}
{10056090}{}{охотников за бандитами}
{10056100}{}{охотников за бандитами}
{10056110}{}{охотников за бандитами}
{10056120}{}{толпу отщепенцев с братом Мортона  во главе}
{10056130}{}{напавших на караван огнедышащих ящеров}
{10056140}{}{напавших на караван огнедышащих ящеров}
{10056150}{}{караван}
{10056160}{}{караван}
{10056170}{}{караван}
{10056180}{}{караван}
{10056190}{}{человека, охраняющего мост}
{10056200}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 53
{10056500}{}{свалку ядовитых отходов}
{10056510}{}{странную одинокую собаку}
{10056520}{}{стадо браминов}
{10056530}{}{несколько якудза}
{10056540}{}{охотников за бандитами}
{10056550}{}{охотников за бандитами}
{10056560}{}{охотников за бандитами}
{10056570}{}{охотников за бандитами}
{10056580}{}{охотников за бандитами}
{10056590}{}{охотников за бандитами}
{10056600}{}{охотников за бандитами}
{10056610}{}{охотников за бандитами}
{10056620}{}{толпу отщепенцев с братом Мортона  во главе}
{10056630}{}{банду}
{10056640}{}{опасную стаю волков}
{10056650}{}{большую толпу мафиози, напавших на якудза}
{10056660}{}{местных мафиози, разбирающихся с конкурентами}
{10056670}{}{группу мафиози}
{10056680}{}{пешехода}
{10056690}{}{останки белого кита}
{10056700}{}{большую каменную голову}
{10056710}{}{разбившийся шаттл}
{10056720}{}{Портал Хранителя}
{10056730}{}{рыцарей короля Артура}
{10056740}{}{железного дровосека}
{10056750}{}{немытых крестьян, гоняющихся за бродягой}
{10056760}{}{кафе Разбитых Мечтаний}

# Encounter Table 54
{10057000}{}{несколько якудза}
{10057010}{}{банду}
{10057020}{}{опасную волчью стаю}
{10057030}{}{большую толпу мафиози, напавших на якудза}
{10057040}{}{охотников за бандитами}
{10057050}{}{охотников за бандитами}
{10057060}{}{охотников за бандитами}
{10057070}{}{охотников за бандитами}
{10057080}{}{охотников за бандитами}
{10057090}{}{охотников за бандитами}
{10057100}{}{охотников за бандитами}
{10057110}{}{охотников за бандитами}
{10057120}{}{толпу отщепенцев с братом Мортона  во главе}
{10057130}{}{местных мафиози, разбирающихся с конкурентами}
{10057140}{}{группу мафиози}
{10057150}{}{пешехода}
{10057160}{}{человека, охраняющего мост}
{10057170}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 55
{10057500}{}{несколько якудза}
{10057510}{}{банду}
{10057520}{}{стаю голодных волков}
{10057530}{}{большую толпу мафиози, напавших на якудза}
{10057540}{}{охотников за бандитами}
{10057550}{}{охотников за бандитами}
{10057560}{}{охотников за бандитами}
{10057570}{}{охотников за бандитами}
{10057580}{}{охотников за бандитами}
{10057590}{}{охотников за бандитами}
{10057600}{}{охотников за бандитами}
{10057610}{}{охотников за бандитами}
{10057620}{}{толпу отщепенцев с братом Мортона  во главе}
{10057630}{}{местных мафиози, разбирающихся с конкурентами}
{10057640}{}{кучку мафиози}
{10057650}{}{пешехода}
{10057660}{}{разрушенную церковь}

# Encounter Table 56
{10058000}{}{свалку ядовитых отходов}
{10058010}{}{странную одинокую собаку}
{10058020}{}{стадо браминов}
{10058030}{}{бандитскую шайку и небольшую волчью стаю}
{10058040}{}{охотников за бандитами}
{10058050}{}{охотников за бандитами}
{10058060}{}{охотников за бандитами}
{10058070}{}{охотников за бандитами}
{10058080}{}{охотников за бандитами}
{10058090}{}{охотников за бандитами}
{10058100}{}{охотников за бандитами}
{10058110}{}{охотников за бандитами}
{10058120}{}{толпу отщепенцев с братом Мортона  во главе}
{10058130}{}{бандитскую группировку}
{10058140}{}{стаю голодных волков}
{10058150}{}{большое стадо рад-скорпионов}
{10058160}{}{огромный лес хищных цветков}
{10058170}{}{патруль Единства, бьющийся с какими-то ворами}
{10058180}{}{патруль Единства, беспощадно истребляющий волков}
{10058190}{}{патруль Единства}
{10058200}{}{останки белого кита}
{10058210}{}{большую каменную голову}
{10058220}{}{разбившийся шаттл}
{10058230}{}{Портал Хранителя}
{10058240}{}{рыцарей короля Артура}
{10058250}{}{железного дровосека}
{10058260}{}{немытых крестьян, гоняющихся за бродягой}

# Encounter Table 57
{10058500}{}{бандитскую шайку и небольшую волчью стаю}
{10058510}{}{небольшое сборище воров}
{10058520}{}{опасную волчью стаю}
{10058530}{}{крупное стадо рад-скорпионов}
{10058540}{}{охотников за бандитами}
{10058550}{}{охотников за бандитами}
{10058560}{}{охотников за бандитами}
{10058570}{}{охотников за бандитами}
{10058580}{}{охотников за бандитами}
{10058590}{}{охотников за бандитами}
{10058600}{}{охотников за бандитами}
{10058610}{}{охотников за бандитами}
{10058620}{}{толпу отщепенцев с братом Мортона  во главе}
{10058630}{}{огромный лес хищных цветков}
{10058640}{}{патруль Единства, бьющийся с какими-то ворами}
{10058650}{}{патруль Единства, беспощадно истребляющий волков}
{10058660}{}{патруль Единства}
{10058670}{}{человека, охраняющего мост}
{10058680}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 58
{10059000}{}{подразделение наемников}
{10059010}{}{банду саботажников}
{10059020}{}{крупное стадо когтей смерти}
{10059030}{}{большое скопление огнедышащих ящеров}
{10059040}{}{охотников за бандитами}
{10059050}{}{охотников за бандитами}
{10059060}{}{охотников за бандитами}
{10059070}{}{охотников за бандитами}
{10059080}{}{охотников за бандитами}
{10059090}{}{охотников за бандитами}
{10059100}{}{охотников за бандитами}
{10059110}{}{охотников за бандитами}
{10059120}{}{толпу отщепенцев с братом Мортона  во главе}
{10059130}{}{ревущую толпу инопланетян}
{10059140}{}{мирных хабологистов, воюющих с наемниками}
{10059150}{}{сумасшедших хабологистов, бьющихся с врагами}
{10059160}{}{хабологистов}
{10059170}{}{группу насекомых-мутантов}
{10059180}{}{палатку наркодилеров, о которой говорила Нэнси по радио}

# Encounter Table 59
{10059500}{}{подразделение наемников}
{10059510}{}{банду саботажников}
{10059520}{}{крупное стадо когтей смерти}
{10059530}{}{большое скопление огнедышащих ящеров}
{10059540}{}{охотников за бандитами}
{10059550}{}{охотников за бандитами}
{10059560}{}{охотников за бандитами}
{10059570}{}{охотников за бандитами}
{10059580}{}{охотников за бандитами}
{10059590}{}{охотников за бандитами}
{10059600}{}{охотников за бандитами}
{10059610}{}{охотников за бандитами}
{10059620}{}{толпу отщепенцев с братом Мортона  во главе}
{10059630}{}{ревущую толпу инопланетян}
{10059640}{}{мирных хабологистов, воюющих с наемниками}
{10059650}{}{сумасшедших хабологистов, бьющихся с врагами}
{10059660}{}{хабологистов}
{10059670}{}{человека, охраняющего мост}
{10059680}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 60
{10060000}{}{подразделение наемников}
{10060010}{}{банду саботажников}
{10060020}{}{крупное стадо когтей смерти}
{10060030}{}{большое скопление огнедышащих ящеров}
{10060040}{}{охотников за бандитами}
{10060050}{}{охотников за бандитами}
{10060060}{}{охотников за бандитами}
{10060070}{}{охотников за бандитами}
{10060080}{}{охотников за бандитами}
{10060090}{}{охотников за бандитами}
{10060100}{}{охотников за бандитами}
{10060110}{}{охотников за бандитами}
{10060120}{}{толпу отщепенцев с братом Мортона  во главе}
{10060130}{}{ревущую толпу инопланетян}
{10060140}{}{мирных хабологистов, воюющих с наемниками}
{10060150}{}{сумасшедших хабологистов, бьющихся с врагами}
{10060160}{}{хабологистов}
{10060170}{}{группу насекомых-мутантов}
{10060180}{}{разрушенную церковь}

# Encounter Table 61
{10060500}{}{свалку ядовитых отходов}
{10060510}{}{странную одинокую собаку}
{10060520}{}{большое стадо браминов}
{10060530}{}{подразделение наемников}
{10060540}{}{охотников за бандитами}
{10060550}{}{охотников за бандитами}
{10060560}{}{охотников за бандитами}
{10060570}{}{охотников за бандитами}
{10060580}{}{охотников за бандитами}
{10060590}{}{охотников за бандитами}
{10060600}{}{охотников за бандитами}
{10060610}{}{охотников за бандитами}
{10060620}{}{толпу отщепенцев с братом Мортона  во главе}
{10060630}{}{банду саботажников}
{10060640}{}{крупное стадо когтей смерти}
{10060650}{}{большое скопление огнедышащих ящеров}
{10060660}{}{ревущую толпу инопланетян}
{10060670}{}{мирных хабологистов, воюющих с наемниками}
{10060680}{}{сумасшедших хабологистов, бьющихся с врагами}
{10060690}{}{хабологистов}
{10060700}{}{останки белого кита}
{10060710}{}{большую каменную голову}
{10060720}{}{разбившийся шаттл}
{10060730}{}{Портал Хранителя}
{10060740}{}{рыцарей короля Артура}
{10060750}{}{железного дровосека}
{10060760}{}{немытых крестьян, гоняющихся за бродягой}
{10060770}{}{кафе Разбитых Мечтаний}
{10060780}{}{группу насекомых-мутантов}

# Encounter Table 62
{10061000}{}{свалку ядовитых отходов}
{10061010}{}{странную одинокую собаку}
{10061020}{}{большое стадо браминов}
{10061030}{}{подразделение наемников}
{10061040}{}{охотников за бандитами}
{10061050}{}{охотников за бандитами}
{10061060}{}{охотников за бандитами}
{10061070}{}{охотников за бандитами}
{10061080}{}{охотников за бандитами}
{10061090}{}{охотников за бандитами}
{10061100}{}{охотников за бандитами}
{10061110}{}{охотников за бандитами}
{10061120}{}{толпу отщепенцев с братом Мортона  во главе}
{10061130}{}{небольшую стаю когтей смерти}
{10061140}{}{малое количество огнедышащих ящеров}
{10061150}{}{ревущую толпу инопланетян}
{10061160}{}{торговый караван, отбивающий атаку наемников}
{10061170}{}{торговый караван, отбивающий атаку наемников}
{10061180}{}{торговцев, сражающихся с огнедышащими ящерами}
{10061190}{}{нападающих на караван инопланетян}
{10061200}{}{караван}
{10061210}{}{караван}
{10061220}{}{останки белого кита}
{10061230}{}{большую каменную голову}
{10061240}{}{разбившийся шаттл}
{10061250}{}{Портал Хранителя}
{10061260}{}{рыцарей короля Артура}
{10061270}{}{железного дровосека}
{10061280}{}{немытых крестьян, гоняющихся за бродягой}
{10061290}{}{кафе Разбитых Мечтаний}

# Encounter Table 63
{10061500}{}{подразделение наемников}
{10061510}{}{небольшую стаю когтей смерти}
{10061520}{}{малое количество огнедышащих ящеров}
{10061530}{}{ревущую толпу инопланетян}
{10061540}{}{охотников за бандитами}
{10061550}{}{охотников за бандитами}
{10061560}{}{охотников за бандитами}
{10061570}{}{охотников за бандитами}
{10061580}{}{охотников за бандитами}
{10061590}{}{охотников за бандитами}
{10061600}{}{охотников за бандитами}
{10061610}{}{охотников за бандитами}
{10061620}{}{толпу отщепенцев с братом Мортона  во главе}
{10061630}{}{торговый караван, отбивающий атаку наемников}
{10061640}{}{торговый караван, отбивающий атаку наемников}
{10061650}{}{торговцев, сражающихся с огнедышащими ящерами}
{10061660}{}{нападающих на караван инопланетян}
{10061670}{}{караван}
{10061680}{}{караван}

# Encounter Table 64
{10062000}{}{свалку ядовитых отбросов}
{10062010}{}{странную одинокую собаку}
{10062020}{}{крупное стадо браминов}
{10062030}{}{вооруженный патруль АНКЛАВА}
{10062040}{}{охотников за бандитами}
{10062050}{}{охотников за бандитами}
{10062060}{}{охотников за бандитами}
{10062070}{}{охотников за бандитами}
{10062080}{}{охотников за бандитами}
{10062090}{}{охотников за бандитами}
{10062100}{}{охотников за бандитами}
{10062110}{}{охотников за бандитами}
{10062120}{}{толпу отщепенцев с братом Мортона  во главе}
{10062130}{}{выживших солдат из армии Повелителя}
{10062140}{}{небольшую группу когтей смерти}
{10062150}{}{целую тучу мантисов}
{10062160}{}{останки белого кита}
{10062170}{}{большую каменную голову}
{10062180}{}{разбившийся шаттл}
{10062190}{}{Портал Хранителя}
{10062200}{}{рыцарей короля Артура}
{10062210}{}{железного дровосека}
{10062220}{}{немытых крестьян, гоняющихся за бродягой}
{10062230}{}{кафе Разбитых Мечтаний}

# Encounter Table 65
{10062500}{}{вооруженный патруль АНКЛАВА}
{10062510}{}{ничтожные остатки войск Повелителя}
{10062520}{}{небольшую группу когтей смерти}
{10062530}{}{целую тучу мантисов}
{10062540}{}{охотников за бандитами}
{10062550}{}{охотников за бандитами}
{10062560}{}{охотников за бандитами}
{10062570}{}{охотников за бандитами}
{10062580}{}{охотников за бандитами}
{10062590}{}{охотников за бандитами}
{10062600}{}{охотников за бандитами}
{10062610}{}{охотников за бандитами}
{10062620}{}{толпу отщепенцев с братом Мортона  во главе}
{10062630}{}{человека, охраняющего мост}
{10062640}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 66
{10063000}{}{свалку ядовитых отбросов}
{10063010}{}{странную одинокую собаку}
{10063020}{}{крупное стадо браминов}
{10063030}{}{караван, подвергшийся нападению дезертиров из армии Повелителя}
{10063040}{}{охотников за бандитами}
{10063050}{}{охотников за бандитами}
{10063060}{}{охотников за бандитами}
{10063070}{}{охотников за бандитами}
{10063080}{}{охотников за бандитами}
{10063090}{}{охотников за бандитами}
{10063100}{}{охотников за бандитами}
{10063110}{}{охотников за бандитами}
{10063120}{}{толпу отщепенцев с братом Мортона  во главе}
{10063130}{}{караван, подвергшийся нападению дезертиров из армии Повелителя}
{10063140}{}{зловещих когтей смерти, атакующих торговый караван}
{10063150}{}{караван}
{10063160}{}{караван}
{10063170}{}{караван}
{10063180}{}{останки белого кита}
{10063190}{}{большую каменную голову}
{10063200}{}{разбившийся шаттл}
{10063210}{}{Портал Хранителя}
{10063220}{}{рыцарей короля Артура}
{10063230}{}{железного дровосека}
{10063240}{}{немытых крестьян, гоняющихся за бродягой}
{10063250}{}{кафе Разбитых Мечтаний}

# Encounter Table 67
{10063500}{}{караван, подвергшийся нападению дезертиров из армии Повелителя}
{10063510}{}{караван, подвергшийся нападению дезертиров из армии Повелителя}
{10063520}{}{зловещих когтей смерти, атакующих торговый караван}
{10063530}{}{караван}
{10063540}{}{охотников за бандитами}
{10063550}{}{охотников за бандитами}
{10063560}{}{охотников за бандитами}
{10063570}{}{охотников за бандитами}
{10063580}{}{охотников за бандитами}
{10063590}{}{охотников за бандитами}
{10063600}{}{охотников за бандитами}
{10063610}{}{охотников за бандитами}
{10063620}{}{толпу отщепенцев с братом Мортона  во главе}
{10063630}{}{караван}
{10063640}{}{караван}
{10063650}{}{человека, охраняющего мост}
{10063660}{}{рыцарей короля Артура, воюющих с грызуном}
{10063670}{}{заброшенный склад пончиков}

# Encounter Table 68
{10064000}{}{опасную волчью стаю}
{10064010}{}{целую тучу мантисов}
{10064020}{}{крупное семейство рад-скорпионов}
{10064030}{}{охотников за бандитами}
{10064040}{}{охотников за бандитами}
{10064050}{}{охотников за бандитами}
{10064060}{}{охотников за бандитами}
{10064070}{}{охотников за бандитами}
{10064080}{}{охотников за бандитами}
{10064090}{}{охотников за бандитами}
{10064100}{}{охотников за бандитами}
{10064110}{}{толпу отщепенцев с братом Мортона  во главе}
{10064120}{}{человека, охраняющего мост}
{10064130}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 69
{10064500}{}{свалку ядовитых отходов}
{10064510}{}{странную одинокую собаку}
{10064520}{}{большое стадо браминов}
{10064530}{}{значительное скопление волков}
{10064540}{}{охотников за бандитами}
{10064550}{}{охотников за бандитами}
{10064560}{}{охотников за бандитами}
{10064570}{}{охотников за бандитами}
{10064580}{}{охотников за бандитами}
{10064590}{}{охотников за бандитами}
{10064600}{}{охотников за бандитами}
{10064610}{}{охотников за бандитами}
{10064620}{}{толпу отщепенцев с братом Мортона  во главе}
{10064630}{}{целую тучу мантисов}
{10064640}{}{крупное семейство рад-скорпионов}
{10064650}{}{останки белого кита}
{10064660}{}{большую каменную голову}
{10064670}{}{разбившийся шаттл}
{10064680}{}{Портал Хранителя}
{10064690}{}{рыцарей короля Артура}
{10064700}{}{железного дровосека}
{10064710}{}{немытых крестьян, гоняющихся за бродягой}
{10064720}{}{кафе Разбитых Мечтаний}
{10064730}{}{странный заброшенный дом}
{10064740}{}{заброшенный склад пончиков}

# Encounter Table 70
{10065000}{}{свалку ядовитых отходов}
{10065010}{}{странную одинокую собаку}
{10065020}{}{крупное стадо браминов}
{10065030}{}{собрание воров в законе}
{10065040}{}{охотников за бандитами}
{10065050}{}{охотников за бандитами}
{10065060}{}{охотников за бандитами}
{10065070}{}{охотников за бандитами}
{10065080}{}{охотников за бандитами}
{10065090}{}{охотников за бандитами}
{10065100}{}{охотников за бандитами}
{10065110}{}{охотников за бандитами}
{10065120}{}{толпу отщепенцев с братом Мортона  во главе}
{10065130}{}{крупную волчью стаю}
{10065140}{}{скопище гнусных рад-скорпионов}
{10065150}{}{местных воров, пытающихся обчистить караван}
{10065160}{}{местных воров, пытающихся обчистить караван}
{10065170}{}{волков, желающих поживиться торговцами}
{10065180}{}{рад-скорпионов, решивших сожрать караван}
{10065190}{}{караван}
{10065200}{}{караван}
{10065210}{}{караван}
{10065220}{}{караван}
{10065230}{}{пешехода}
{10065240}{}{останки белого кита}
{10065250}{}{большую каменную голову}
{10065260}{}{разбившийся шаттл}
{10065270}{}{Портал Хранителя}
{10065280}{}{рыцарей короля Артура}
{10065290}{}{железного дровосека}
{10065300}{}{немытых крестьян, гоняющихся за бродягой}
{10065310}{}{кафе Разбитых Мечтаний}

# Encounter Table 71
{10065500}{}{собрание воров в законе}
{10065510}{}{большую стаю голодных волков}
{10065520}{}{стадо мерзких рад-скорпионов}
{10065530}{}{местных воров, пытающихся обчистить караван}
{10065540}{}{охотников за бандитами}
{10065550}{}{охотников за бандитами}
{10065560}{}{охотников за бандитами}
{10065570}{}{охотников за бандитами}
{10065580}{}{охотников за бандитами}
{10065590}{}{охотников за бандитами}
{10065600}{}{охотников за бандитами}
{10065610}{}{охотников за бандитами}
{10065620}{}{толпу отщепенцев с братом Мортона  во главе}
{10065630}{}{местных воров, пытающихся обчистить караван}
{10065640}{}{волков, желающих поживиться торговцами}
{10065650}{}{рад-скорпионов, решивших сожрать караван}
{10065660}{}{караван}
{10065670}{}{караван}
{10065680}{}{караван}
{10065690}{}{караван}
{10065700}{}{пешехода}
{10065710}{}{человека, охраняющего мост}
{10065720}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 72
{10066000}{}{войсковое подразделение армии Повелителя}
{10066010}{}{собрание воров в законе}
{10066020}{}{группу Рейнджеров, отражающих атаку взвода армии Повелителя}
{10066030}{}{отряд Рейнджеров, бьющийся с ворами в законе}
{10066040}{}{охотников за бандитами}
{10066050}{}{охотников за бандитами}
{10066060}{}{охотников за бандитами}
{10066070}{}{охотников за бандитами}
{10066080}{}{охотников за бандитами}
{10066090}{}{охотников за бандитами}
{10066100}{}{охотников за бандитами}
{10066110}{}{охотников за бандитами}
{10066120}{}{толпу отщепенцев с братом Мортона  во главе}
{10066130}{}{крестьян, пытающихся обороняться от мародеров из армии Повелителя}
{10066140}{}{крестьян, устраивающих самосуд над ворами}
{10066150}{}{подразделение Рейнджеров Калифорнии}
{10066160}{}{группу крестьян}
{10066170}{}{человека, охраняющего мост}
{10066180}{}{рыцарей короля Артура, воюющих с грызуном}
{10066190}{}{разномастную шайку бандитов}
{10066200}{}{несколько мятежных рейнджеров Уильяма Коди}


# Encounter Table 73
{10066500}{}{свалку ядовитых отбросов}
{10066510}{}{странную одинокую собаку}
{10066520}{}{крупное стадо браминов}
{10066530}{}{войсковое подразделение армии Повелителя}
{10066540}{}{охотников за бандитами}
{10066550}{}{охотников за бандитами}
{10066560}{}{охотников за бандитами}
{10066570}{}{охотников за бандитами}
{10066580}{}{охотников за бандитами}
{10066590}{}{охотников за бандитами}
{10066600}{}{охотников за бандитами}
{10066610}{}{охотников за бандитами}
{10066620}{}{толпу отщепенцев с братом Мортона  во главе}
{10066630}{}{собрание воров в законе}
{10066640}{}{группу Рейнджеров, отражающую атаку взвода армии Повелителя}
{10066650}{}{отряд Рейнджеров, бьющийся с ворами в законе}
{10066660}{}{крестьян, пытающихся обороняться от мародеров из армии Повелителя}
{10066670}{}{крестьян, устраивающих самосуд над ворами}
{10066680}{}{подразделение Рейнджеров Калифорнии}
{10066690}{}{местных крестьян}
{10066700}{}{останки белого кита}
{10066710}{}{большую каменную голову}
{10066720}{}{разбившийся шаттл}
{10066730}{}{Портал Хранителя}
{10066740}{}{рыцарей короля Артура}
{10066750}{}{железного дровосека}
{10066760}{}{немытых крестьян, гоняющихся за бродягой}
{10066770}{}{кафе Разбитых Мечтаний}

# Encounter Table 74
{10067000}{}{выживших солдат из армии Повелителя, борющихся с кротами-гризли}
{10067010}{}{жалкие остатки мощных когда-то армий Повелителя}
{10067020}{}{целую тучу мантисов}
{10067030}{}{крупную стаю мутировавших кротов-гризли}
{10067040}{}{охотников за бандитами}
{10067050}{}{охотников за бандитами}
{10067060}{}{охотников за бандитами}
{10067070}{}{охотников за бандитами}
{10067080}{}{охотников за бандитами}
{10067090}{}{охотников за бандитами}
{10067100}{}{охотников за бандитами}
{10067110}{}{охотников за бандитами}
{10067120}{}{толпу отщепенцев с братом Мортона  во главе}
{10067130}{}{небольшую стайку рад-скорпионов}
{10067140}{}{человека, охраняющего мост}
{10067150}{}{рыцарей короля Артура, воюющих с грызуном}

# Encounter Table 75
{10067500}{}{свалку ядовитых отбросов}
{10067510}{}{странную одинокую собаку}
{10067520}{}{крупное стадо браминов}
{10067530}{}{выживших солдат из армии Повелителя, борющихся с кротами-гризли}
{10067540}{}{охотников за бандитами}
{10067550}{}{охотников за бандитами}
{10067560}{}{охотников за бандитами}
{10067570}{}{охотников за бандитами}
{10067580}{}{охотников за бандитами}
{10067590}{}{охотников за бандитами}
{10067600}{}{охотников за бандитами}
{10067610}{}{охотников за бандитами}
{10067620}{}{толпу отщепенцев с братом Мортона  во главе}
{10067630}{}{жалкие остатки могучей армии Повелителя}
{10067640}{}{целую тучу мантисов}
{10067650}{}{крупное сообщество мутировавших кротов-гризли}
{10067660}{}{стайку гнусных рад-скорпионов}
{10067670}{}{останки белого кита}
{10067680}{}{большую каменную голову}
{10067690}{}{разбившийся шаттл}
{10067700}{}{Портал Хранителя}
{10067710}{}{рыцарей короля Артура}
{10067720}{}{железного дровосека}
{10067730}{}{немытых крестьян, гоняющихся за бродягой}
{10067740}{}{кафе Разбитых Мечтаний}
{10067750}{}{остатки каравана Даппо}

# Encounter Table 76 (Ocean North)

{10068010}{}{мель}
{10068020}{}{несколько водяных крыс}
{10068030}{}{островок, кишаший крысами}
{10068040}{}{водяных крыс-переростков}
{10068050}{}{островок с гнездом мантисов}
{10068060}{}{дрейфующий плот}
{10068070}{}{торговца}

# Encounter Table 77 (Ocean South)

{10068200}{}{мель}
{10068210}{}{голодных и злых водяных крыс}
{10068220}{}{островок, кишаший крысами}
{10068230}{}{мутировавших водяных крыс}
{10068240}{}{островок с гнездом мантисов}
{10068250}{}{остров с несколькими осами-переростками}
{10068260}{}{остров с осиным гнездом}
{10068270}{}{дрейфующий плот}
{10068280}{}{торговца}

# Encounter Table 78 (Hell)

{10068400}{}{беглых каторжников}
{10068410}{}{патруль хабологов}
{10068420}{}{усиленный патруль хабологов}
{10068430}{}{патруль хабологов, воюющий с беглыми каторжниками}
{10068440}{}{беглых каторжников, устраивающих самосуд над хабологами}
{10068450}{}{нескольких оголодавших каторжников}
{10068460}{}{толпу беглых каторжников, потерявших разум}
{10068470}{}{стайку каких-то ящеров}
{10068480}{}{опасную волчью стаю}
{10068490}{}{мутировавших и отощавших кротов-гризли}
{10068500}{}{мутировавших кротов-гризли, дерущихся с ящерами}
{10068510}{}{рад-скорпионов, пытающихся сожрать кротов-гризли}
{10068520}{}{человека, охраняющего мост}
{10068530}{}{рыцарей короля Артура, воюющих с грызуном}

