#include "Common.h"

#include "Server.h"

///# ...
///# param imageSlot ...
///# param imageName ...
///@ ExportMethod
[[maybe_unused]] void Server_Game_LoadImage(FOServer* self, int imageSlot, string_view imageName)
{
}

///# ...
///# param imageSlot ...
///# param x ...
///# param y ...
///# return ...
///@ ExportMethod
[[maybe_unused]] uint Server_Game_GetImageColor(FOServer* self, int imageSlot, int x, int y)
{
    return 0;
}

///# ...
///# return ...
///@ ExportMethod
[[maybe_unused]] bool Server_Critter_IsFree(Critter* self)
{
    return false;
}

///# ...
///# return ...
///@ ExportMethod
[[maybe_unused]] bool Server_Critter_IsBusy(Critter* self)
{
    return false;
}

///# ...
///# param ms ...
///@ ExportMethod
[[maybe_unused]] void Server_Critter_Wait(Critter* self, uint ms)
{
}
