#
# Worldmap Encounter messages
#

{10000010}{}{You encounter: @lex who@.}
{10000011}{}{You encounter: @lex who@ and @lex player@.}
{10000012}{}{You encounter: @lex who@ and @lex player@ group.}
{10000013}{}{You encounter: @lex player@.}
{10000014}{}{You encounter: @lex player@ group.}
{10000020}{}{Do you wish to encounter: @lex who@.}
{10000021}{}{Do you wish to encounter: @lex who@ and @lex player@.}
{10000022}{}{Do you wish to encounter: @lex who@ and @lex player@ group.}
{10000023}{}{Do you wish to encounter: @lex player@.}
{10000024}{}{Do you wish to encounter: @lex player@ group.}

# Encounter Table 0 (Fallout 1 + FOnline global table)
{10030000}{}{A party of raiders}
{10030010}{}{Some radscorpions}
{10030020}{}{Giant rats}
{10030030}{}{A merchant party}
{10030040}{}{<Special>}
{10030050}{}{someone unknown}
{10030060}{}{The church of Brock and Xander}
{10030070}{}{A traveller}
{10030080}{}{головорезов из банды Шакалы Карлоса}

# Encounter Table 1
{10030500}{}{A party of raiders}
{10030510}{}{Some manti}
{10030520}{}{A group of geckos}
{10030530}{}{A group of mole rats}
{10030540}{}{A group of radscorpions}
{10030550}{}{A group of giant rats}
{10030560}{}{A merchant party}
{10030570}{}{<Special>}

# Encounter Table 2
{10031000}{}{A party of raiders}
{10031010}{}{A group of radscorpions}
{10031020}{}{A group of giant rats}
{10031030}{}{A merchant party}
{10031040}{}{<Special>}

# Encounter Table 3
{10031500}{}{A party of raiders}

# Encounter Table 4
{10032000}{}{A party of raiders}

# Encounter Table 5
{10032500}{}{A party of raiders}

# Encounter Table 6
{10033000}{}{A war party}
{10033010}{}{A group of cannibals}
{10033020}{}{A group of spore plants and some silver geckos}
{10033030}{}{A group of silver geckos}
{10033040}{}{Some bounty hunters}
{10033050}{}{Some bounty hunters}
{10033060}{}{Some bounty hunters}
{10033070}{}{Some bounty hunters}
{10033080}{}{Some bounty hunters}
{10033090}{}{Some bounty hunters}
{10033100}{}{Some bounty hunters}
{10033110}{}{Some bounty hunters}
{10033120}{}{A band of ruffians led by a Morton Brother}
{10033130}{}{A group of scorpions}
{10033140}{}{A group of spore plants}
{10033150}{}{A group of pig rats}
{10033160}{}{A group of rats}
{10033170}{}{A hunting party fighting cannibals}
{10033180}{}{A group of ants}
{10033190}{}{A hunting party fighting some scorpions}
{10033200}{}{A small group of pig rats}
{10033210}{}{A small group of radscorpions}
{10033220}{}{A small group of ants}
{10033230}{}{A hunting party}
{10033240}{}{A group of nomads}
{10033250}{}{A man guarding a bridge}
{10033260}{}{King Arthur's Knights fighting a rat}

# Encounter Table 7
{10033500}{}{Toxic waste dump}
{10033510}{}{A lone surviving dog}
{10033520}{}{A herd of brahmin}
{10033530}{}{A war party}
{10033540}{}{Some bounty hunters}
{10033550}{}{Some bounty hunters}
{10033560}{}{Some bounty hunters}
{10033570}{}{Some bounty hunters}
{10033580}{}{Some bounty hunters}
{10033590}{}{Some bounty hunters}
{10033600}{}{Some bounty hunters}
{10033610}{}{Some bounty hunters}
{10033620}{}{A band of ruffians led by a Morton Brother}
{10033630}{}{A group of cannibals}
{10033640}{}{A group of spore plants and some silver geckos}
{10033650}{}{A group of silver geckos}
{10033660}{}{A group of scorpions}
{10033670}{}{A group of spore plants}
{10033680}{}{A group of pig rats}
{10033690}{}{A group of rats}
{10033700}{}{A hunting party fighting cannibals}
{10033710}{}{A group of ants}
{10033720}{}{A hunting party fighting some scorpions}
{10033730}{}{A small group of pig rats}
{10033740}{}{A small group of radscorpions}
{10033750}{}{A small group of ants}
{10033760}{}{A hunting party}
{10033770}{}{A group of nomads}
{10033780}{}{The remains of a whale}
{10033790}{}{A giant stone head}
{10033800}{}{A crashed shuttle}
{10033810}{}{A Guardian Portal}
{10033820}{}{King Arthur's Knights}
{10033830}{}{A tin woodsman}
{10033840}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 8
{10034000}{}{A war party}
{10034010}{}{A group of cannibals}
{10034020}{}{A group of spore plants and some silver geckos}
{10034030}{}{A group of silver geckos}
{10034040}{}{Some bounty hunters}
{10034050}{}{Some bounty hunters}
{10034060}{}{Some bounty hunters}
{10034070}{}{Some bounty hunters}
{10034080}{}{Some bounty hunters}
{10034090}{}{Some bounty hunters}
{10034100}{}{Some bounty hunters}
{10034110}{}{Some bounty hunters}
{10034120}{}{A band of ruffians led by a Morton Brother}
{10034130}{}{A group of scorpions}
{10034140}{}{A group of spore plants}
{10034150}{}{A group of pig rats}
{10034160}{}{A group of rats}
{10034170}{}{A hunting party fighting cannibals}
{10034180}{}{A group of ants}
{10034190}{}{A hunting party fighting some scorpions}
{10034200}{}{A small group of pig rats}
{10034210}{}{A small group of radscorpions}
{10034220}{}{A small group of ants}
{10034230}{}{A hunting party}
{10034240}{}{A group of nomads}

# Encounter Table 9
{10034500}{}{Toxic waste dump}
{10034510}{}{A lone surviving dog}
{10034520}{}{A herd of brahmin}
{10034530}{}{A band of outcasts}
{10034540}{}{Some bounty hunters}
{10034550}{}{Some bounty hunters}
{10034560}{}{Some bounty hunters}
{10034570}{}{Some bounty hunters}
{10034580}{}{Some bounty hunters}
{10034590}{}{Some bounty hunters}
{10034600}{}{Some bounty hunters}
{10034610}{}{Some bounty hunters}
{10034620}{}{A band of ruffians led by a Morton Brother}
{10034630}{}{A group of holy people}
{10034640}{}{Some geckos and some molerats}
{10034650}{}{Some geckos}
{10034660}{}{Some radscorpions hiding amongst spore plants}
{10034670}{}{Some spore plants}
{10034680}{}{A family of radscorpions}
{10034690}{}{A group of Molerats}
{10034700}{}{A group of holy people staving off a war party}
{10034710}{}{A band of nomads}
{10034720}{}{The remains of a whale}
{10034730}{}{A giant stone head}
{10034740}{}{A crashed shuttle}
{10034750}{}{A Guardian Portal}
{10034760}{}{King Arthur's Knights}
{10034770}{}{A tin woodsman}
{10034780}{}{The Unwashed Villagers hunting a spammer}
{10034790}{}{Wasteland Children shelter}
{10034800}{}{заброшенный аванпост Рыцарей Пустоши}
{10034810}{}{пещеру}
{10034820}{}{заброшенную деревеньку. Даже с расстояния ощущается зло, исходящее от нее}
{10034830}{}{abandoned doughnut warehouse}

# Encounter Table 10
{10035000}{}{A band of outcasts}
{10035010}{}{A group of holy people}
{10035020}{}{Some bounty hunters}
{10035030}{}{Some bounty hunters}
{10035040}{}{Some bounty hunters}
{10035050}{}{Some bounty hunters}
{10035060}{}{Some bounty hunters}
{10035070}{}{Some bounty hunters}
{10035080}{}{Some bounty hunters}
{10035090}{}{Some bounty hunters}
{10035100}{}{A band of ruffians led by a Morton Brother}
{10035110}{}{Some silver geckos hiding amongst spore plants}
{10035120}{}{Some geckos}
{10035130}{}{Some radscorpions hiding amongst spore plants}
{10035140}{}{Some spore plants}
{10035150}{}{A family of radscorpions}
{10035160}{}{A group of Molerats}
{10035170}{}{A group of holy people staving off a war party}
{10035180}{}{A band of nomads}
{10035190}{}{A man guarding a bridge}
{10035200}{}{King Arthur's Knights fighting a rat}

# Encounter Table 11
{10035500}{}{Toxic waste dump}
{10035510}{}{A lone surviving dog}
{10035520}{}{A herd of brahmin}
{10035530}{}{A pack of golden geckos and a family of radscorpions}
{10035540}{}{Some bandits}
{10035550}{}{A group of homeless people}
{10035560}{}{A pack of golden geckos}
{10035570}{}{Some bounty hunters}
{10035580}{}{Some bounty hunters}
{10035590}{}{Some bounty hunters}
{10035600}{}{Some bounty hunters}
{10035610}{}{Some bounty hunters}
{10035620}{}{Some bounty hunters}
{10035630}{}{Some bounty hunters}
{10035640}{}{Some bounty hunters}
{10035650}{}{A band of ruffians led by a Morton Brother}
{10035660}{}{A family of radscorpions}
{10035670}{}{Some spore plants}
{10035680}{}{Some bandits attacked by some golden geckos}
{10035690}{}{Some farmers defending against some geckos}
{10035700}{}{Some farmers fending off some golden geckos}
{10035710}{}{Some trappers battling some golden geckos}
{10035720}{}{Some trappers fending off some bandits}
{10035730}{}{A group of trappers subduing some geckos}
{10035740}{}{Some bandits ambushing some homeless people}
{10035750}{}{Some homeless people butchering some farmers}
{10035760}{}{Some bandits attacking some farmers}
{10035770}{}{Some farmers fending off some scorpions}
{10035780}{}{Some trappers fighting some scorpions}
{10035790}{}{Some trappers attacking some pig rats}
{10035800}{}{Some farmers rooting out an infestation of pig rats}
{10035810}{}{Some farmers}
{10035820}{}{A group of trappers}
{10035830}{}{The remains of a whale}
{10035840}{}{A giant stone head}
{10035850}{}{A crashed shuttle}
{10035860}{}{A Guardian Portal}
{10035870}{}{King Arthur's Knights}
{10035880}{}{A tin woodsman}
{10035890}{}{The Unwashed Villagers hunting a spammer}
{10035900}{}{Пристанище Детей Пустоши}
{10035910}{}{заброшенный аванпост Рыцарей Пустоши}
{10035920}{}{заброшенную деревеньку. Даже с расстояния ощущается зло, исходящее от нее}
{10035930}{}{the lost doughnut warehouse}

# Encounter Table 12
{10036000}{}{A pack of golden geckos and a family of radscorpions}
{10036010}{}{Some bandits}
{10036020}{}{A group of homeless people}
{10036030}{}{A pack of golden geckos}
{10036040}{}{Some bounty hunters}
{10036050}{}{Some bounty hunters}
{10036060}{}{Some bounty hunters}
{10036070}{}{Some bounty hunters}
{10036080}{}{Some bounty hunters}
{10036090}{}{Some bounty hunters}
{10036100}{}{Some bounty hunters}
{10036110}{}{Some bounty hunters}
{10036120}{}{A band of ruffians led by a Morton Brother}
{10036130}{}{A family of radscorpions}
{10036140}{}{Some spore plants}
{10036150}{}{Some bandits attacked by some golden geckos}
{10036160}{}{Some farmers defending against some geckos}
{10036170}{}{Some farmers fending off some golden geckos}
{10036180}{}{Some trappers battling some golden geckos}
{10036190}{}{Some trappers fending off some bandits}
{10036200}{}{A group of trappers subduing some geckos}
{10036210}{}{Some bandits ambushing some homeless people}
{10036220}{}{Some homeless people butchering some farmers}
{10036230}{}{Some bandits attacking some farmers}
{10036240}{}{Some farmers fending off some scorpions}
{10036250}{}{Some trappers fighting some scorpions}
{10036260}{}{Some trappers attacking some pig rats}
{10036270}{}{Some farmers rooting out an infestation of pig rats}
{10036280}{}{Some farmers}
{10036290}{}{A group of trappers}
{10036300}{}{A man guarding a bridge}
{10036310}{}{King Arthur's Knights fighting a rat}
{10036320}{}{the lost doughnut warehouse}

# Encounter Table 13
{10036500}{}{Toxic waste dump}
{10036510}{}{A lone surviving dog}
{10036520}{}{A herd of brahmin}
{10036530}{}{A merchant and some guards}
{10036540}{}{Some bounty hunters}
{10036550}{}{Some bounty hunters}
{10036560}{}{Some bounty hunters}
{10036570}{}{Some bounty hunters}
{10036580}{}{Some bounty hunters}
{10036590}{}{Some bounty hunters}
{10036600}{}{Some bounty hunters}
{10036610}{}{Some bounty hunters}
{10036620}{}{A band of ruffians led by a Morton Brother}
{10036630}{}{Some trappers}
{10036640}{}{Some bandits attacking a merchant party}
{10036650}{}{Some bandits ambushing some trappers}
{10036660}{}{A family of radscorpions attacking a merchant party}
{10036670}{}{Some trappers trying to catch radscorpions}
{10036680}{}{A group of radscorpions}
{10036690}{}{A family of molerats}
{10036700}{}{Some bandits}
{10036710}{}{A band of trappers trying to catch some golden geckos}
{10036720}{}{Some scorpions fighting some golden geckos}
{10036730}{}{Some scorpions attacking some molerats and pig rats}
{10036740}{}{Some trappers and a merchant party fending off bandits}
{10036750}{}{Some golden geckos}
{10036760}{}{Some trappers fighting some molerats and pig rats}
{10036770}{}{A merchant party fending off some molerats and pig rats}
{10036780}{}{The remains of a whale}
{10036790}{}{A giant stone head}
{10036800}{}{A crashed shuttle}
{10036810}{}{A Guardian Portal}
{10036820}{}{King Arthur's Knights}
{10036830}{}{A tin woodsman}
{10036840}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 14
{10037000}{}{Toxic waste dump}
{10037010}{}{A lone surviving dog}
{10037020}{}{A herd of brahmin}
{10037030}{}{A band of highwaymen}
{10037040}{}{Some bounty hunters}
{10037050}{}{Some bounty hunters}
{10037060}{}{Some bounty hunters}
{10037070}{}{Some bounty hunters}
{10037080}{}{Some bounty hunters}
{10037090}{}{Some bounty hunters}
{10037100}{}{Some bounty hunters}
{10037110}{}{Some bounty hunters}
{10037120}{}{A band of ruffians led by a Morton Brother}
{10037130}{}{A band of robbers}
{10037140}{}{A band of robbers and highwaymen}
{10037150}{}{Some golden geckos and some radscorpions}
{10037160}{}{A family of golden geckos}
{10037170}{}{A family of molerats}
{10037180}{}{A large group of radscorpions}
{10037190}{}{A large infestation of spore plants}
{10037200}{}{A band of robbers contesting a group of highwaymen}
{10037210}{}{A merchant party fending off some highwaymen}
{10037220}{}{A merchant party fending off some robbers}
{10037230}{}{A merchant party fending off some radscorpions}
{10037240}{}{A group of golden geckos battling some radscorpions}
{10037250}{}{A merchant with some guards}
{10037260}{}{The remains of a whale}
{10037270}{}{A giant stone head}
{10037280}{}{A crashed shuttle}
{10037290}{}{A Guardian Portal}
{10037300}{}{King Arthur's Knights}
{10037310}{}{A tin woodsman}
{10037320}{}{The Unwashed Villagers hunting a spammer}
{10037330}{}{развалины дома}
{10037331}{}{странную пещеру}

# Encounter Table 15
{10037500}{}{A band of highwaymen}
{10037510}{}{A band of robbers}
{10037520}{}{A band of robbers and highwaymen}
{10037530}{}{Some golden geckos and some radscorpions}
{10037540}{}{Some bounty hunters}
{10037550}{}{Some bounty hunters}
{10037560}{}{Some bounty hunters}
{10037570}{}{Some bounty hunters}
{10037580}{}{Some bounty hunters}
{10037590}{}{Some bounty hunters}
{10037600}{}{Some bounty hunters}
{10037610}{}{Some bounty hunters}
{10037620}{}{A band of ruffians led by a Morton Brother}
{10037630}{}{A family of golden geckos}
{10037640}{}{A family of molerats}
{10037650}{}{A large group of radscorpions}
{10037660}{}{A large infestation of spore plants}
{10037670}{}{A band of robbers contesting a group of highwaymen}
{10037680}{}{A merchant party fending off some highwaymen}
{10037690}{}{A merchant party fending off some robbers}
{10037700}{}{A merchant party fending off some radscorpions}
{10037710}{}{A group of golden geckos battling some radscorpions}
{10037720}{}{A merchant with some guards}
{10037730}{}{A man guarding a bridge}
{10037740}{}{King Arthur's Knights fighting a rat}

# Encounter Table 16
{10038000}{}{Toxic waste dump}
{10038010}{}{A lone surviving dog}
{10038020}{}{A herd of brahmin}
{10038030}{}{A group of slavers and slaves}
{10038040}{}{Some bounty hunters}
{10038050}{}{Some bounty hunters}
{10038060}{}{Some bounty hunters}
{10038070}{}{Some bounty hunters}
{10038080}{}{Some bounty hunters}
{10038090}{}{Some bounty hunters}
{10038100}{}{Some bounty hunters}
{10038110}{}{Some bounty hunters}
{10038120}{}{A band of ruffians led by a Morton Brother}
{10038130}{}{A group of highwaymen}
{10038140}{}{A band of robbers}
{10038150}{}{Some golden geckos hiding amongst a large number of spore plants}
{10038160}{}{A pack of radscorpions and some molerats}
{10038170}{}{A pack of radscorpions}
{10038180}{}{A group of molerats}
{10038190}{}{A band of robbers ambushing a group of highwaymen}
{10038200}{}{A group of slavers attempting to enslave some people}
{10038210}{}{A group of slavers and slaves fending off some robbers}
{10038220}{}{Some slavers and slaves fending off some golden geckos}
{10038230}{}{Some radscorpions raiding a Rave party}
{10038240}{}{A Rave party}
{10038250}{}{The remains of a whale}
{10038260}{}{A giant stone head}
{10038270}{}{A crashed shuttle}
{10038280}{}{A Guardian Portal}
{10038290}{}{King Arthur's Knights}
{10038300}{}{A tin woodsman}
{10038310}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 17
{10038500}{}{A group of slavers and slaves}
{10038510}{}{A group of highwaymen}
{10038520}{}{A band of robbers}
{10038530}{}{Some golden geckos hiding amongst a large number of spore plants}
{10038540}{}{Some bounty hunters}
{10038550}{}{Some bounty hunters}
{10038560}{}{Some bounty hunters}
{10038570}{}{Some bounty hunters}
{10038580}{}{Some bounty hunters}
{10038590}{}{Some bounty hunters}
{10038600}{}{Some bounty hunters}
{10038610}{}{Some bounty hunters}
{10038620}{}{A band of ruffians led by a Morton Brother}
{10038630}{}{A pack of radscorpions and some molerats}
{10038640}{}{A pack of radscorpions}
{10038650}{}{A group of molerats}
{10038660}{}{A band of robbers ambushing a group of highwaymen}
{10038670}{}{A group of slavers attempting to enslave some people}
{10038680}{}{A group of slavers and slaves fending off some robbers}
{10038690}{}{Some slavers and slaves fending off some golden geckos}
{10038700}{}{A man guarding a bridge}
{10038710}{}{King Arthur's Knights fighting a rat}

# Encounter Table 18
{10039000}{}{Some highwaymen and robbers}
{10039010}{}{Some highwaymen}
{10039020}{}{A large pack of golden geckos}
{10039030}{}{Some scorpions hiding in the spore plants}
{10039040}{}{Some bounty hunters}
{10039050}{}{Some bounty hunters}
{10039060}{}{Some bounty hunters}
{10039070}{}{Some bounty hunters}
{10039080}{}{Some bounty hunters}
{10039090}{}{Some bounty hunters}
{10039100}{}{Some bounty hunters}
{10039110}{}{Some bounty hunters}
{10039120}{}{A band of ruffians led by a Morton Brother}
{10039130}{}{Some robbers fighting some scorpions}
{10039140}{}{Some robbers}
{10039150}{}{A merchant party attacked by highwaymen}
{10039160}{}{A merchant party ambushed by robbers}
{10039170}{}{Some highwaymen attacked by some spore plants}
{10039180}{}{A merchant party}
{10039190}{}{A man guarding a bridge}
{10039200}{}{King Arthur's Knights fighting a rat}

# Encounter Table 19
{10039500}{}{Some highwaymen}
{10039510}{}{Some robbers}
{10039520}{}{Some homeless people}
{10039530}{}{Some golden geckos and mantis}
{10039540}{}{Some bounty hunters}
{10039550}{}{Some bounty hunters}
{10039560}{}{Some bounty hunters}
{10039570}{}{Some bounty hunters}
{10039580}{}{Some bounty hunters}
{10039590}{}{Some bounty hunters}
{10039600}{}{Some bounty hunters}
{10039610}{}{Some bounty hunters}
{10039620}{}{A band of ruffians led by a Morton Brother}
{10039630}{}{Some wild brahmin}
{10039640}{}{Some scorpions}
{10039650}{}{Some moonshiners attacked by some highwaymen}
{10039660}{}{Some highwaymen attacking some homeless people}
{10039670}{}{Some moonshiners and farmers}
{10039680}{}{Some mantis attacking some farmers}
{10039690}{}{Some moonshiners battling some farmers}
{10039700}{}{Some brahmin fending off some mantis}
{10039710}{}{Some mantis attacking some molerats}
{10039720}{}{Some moonshiners}
{10039730}{}{Some farmers}
{10039740}{}{A herd of brahmin}
{10039750}{}{A man guarding a bridge}
{10039760}{}{King Arthur's Knights fighting a rat}

# Encounter Table 20
{10040000}{}{Some highwaymen tracking with wild dogs}
{10040010}{}{Some robbers searching with wild dogs}
{10040020}{}{A band of robbers}
{10040030}{}{A band of highwaymen}
{10040040}{}{Some bounty hunters}
{10040050}{}{Some bounty hunters}
{10040060}{}{Some bounty hunters}
{10040070}{}{Some bounty hunters}
{10040080}{}{Some bounty hunters}
{10040090}{}{Some bounty hunters}
{10040100}{}{Some bounty hunters}
{10040110}{}{Some bounty hunters}
{10040120}{}{A band of ruffians led by a Morton Brother}
{10040130}{}{A swarm of mantis infesting some spore plants}
{10040140}{}{A pack of wild dogs amongst some spore plants}
{10040150}{}{A swarm of mantis}
{10040160}{}{A pack of wild dogs}
{10040170}{}{Some robbers fending off some wild dogs}
{10040180}{}{A caravan attacked by wild dogs}
{10040190}{}{A caravan ambushed by robbers}
{10040200}{}{A caravan ambushed by highwaymen}
{10040210}{}{A caravan}
{10040220}{}{A man guarding a bridge}
{10040230}{}{King Arthur's Knights fighting a rat}

# Encounter Table 21
{10040500}{}{Toxic waste dump}
{10040510}{}{A lone surviving dog}
{10040520}{}{A herd of brahmin}
{10040530}{}{Some highwaymen tracking with wild dogs}
{10040540}{}{Some bounty hunters}
{10040550}{}{Some bounty hunters}
{10040560}{}{Some bounty hunters}
{10040570}{}{Some bounty hunters}
{10040580}{}{Some bounty hunters}
{10040590}{}{Some bounty hunters}
{10040600}{}{Some bounty hunters}
{10040610}{}{Some bounty hunters}
{10040620}{}{A band of ruffians led by a Morton Brother}
{10040630}{}{Some robbers searching with wild dogs}
{10040640}{}{A band of robbers}
{10040650}{}{A band of highwaymen}
{10040660}{}{A swarm of mantis infesting some spore plants}
{10040670}{}{A pack of wild dogs amongst some spore plants}
{10040680}{}{A swarm of mantis}
{10040690}{}{A pack of wild dogs}
{10040700}{}{Some robbers fending off some wild dogs}
{10040710}{}{A caravan attacked by wild dogs}
{10040720}{}{A caravan ambushed by robbers}
{10040730}{}{A caravan ambushed by highwaymen}
{10040740}{}{A caravan}
{10040750}{}{The remains of a whale}
{10040760}{}{A giant stone head}
{10040770}{}{A crashed shuttle}
{10040780}{}{A Guardian Portal}
{10040790}{}{King Arthur's Knights}
{10040800}{}{A tin woodsman}
{10040810}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 22
{10041000}{}{Some golden geckos}
{10041010}{}{A swarm of mantis}
{10041020}{}{Some radscorpions}
{10041030}{}{Some wild brahmin}
{10041040}{}{Some bounty hunters}
{10041050}{}{Some bounty hunters}
{10041060}{}{Some bounty hunters}
{10041070}{}{Some bounty hunters}
{10041080}{}{Some bounty hunters}
{10041090}{}{Some bounty hunters}
{10041100}{}{Some bounty hunters}
{10041110}{}{Some bounty hunters}
{10041120}{}{A band of ruffians led by a Morton Brother}
{10041130}{}{A trader and guards fighting golden geckos}
{10041140}{}{A swarm of mantis massacring a trading band}
{10041150}{}{A swarm of mantis fighting wild brahmin}
{10041160}{}{Some radscorpions feasting on mantis}
{10041170}{}{Some radscorpions butchering some wild brahmin}
{10041180}{}{A trader and guards}
{10041190}{}{A man guarding a bridge}
{10041200}{}{King Arthur's Knights fighting a rat}

# Encounter Table 23
{10041500}{}{Toxic waste dump}
{10041510}{}{A lone surviving dog}
{10041520}{}{A herd of brahmin}
{10041530}{}{Some golden geckos}
{10041540}{}{Some bounty hunters}
{10041550}{}{Some bounty hunters}
{10041560}{}{Some bounty hunters}
{10041570}{}{Some bounty hunters}
{10041580}{}{Some bounty hunters}
{10041590}{}{Some bounty hunters}
{10041600}{}{Some bounty hunters}
{10041610}{}{Some bounty hunters}
{10041620}{}{A band of ruffians led by a Morton Brother}
{10041630}{}{A swarm of mantis}
{10041640}{}{Some radscorpions}
{10041650}{}{Some wild brahmin}
{10041660}{}{A trader and guards fighting golden geckos}
{10041670}{}{A swarm of mantis massacring a trading band}
{10041680}{}{A swarm of mantis fighting wild brahmin}
{10041690}{}{Some radscorpions feasting on mantis}
{10041700}{}{Some radscorpions butchering some wild brahmin}
{10041710}{}{A trader and guards}
{10041720}{}{The remains of a whale}
{10041730}{}{A giant stone head}
{10041740}{}{A crashed shuttle}
{10041750}{}{A Guardian Portal}
{10041760}{}{King Arthur's Knights}
{10041770}{}{A tin woodsman}
{10041780}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 24
{10042000}{}{Toxic waste dump}
{10042010}{}{A lone surviving dog}
{10042020}{}{A herd of brahmin}
{10042030}{}{Some mutated molerats}
{10042040}{}{Some bounty hunters}
{10042050}{}{Some bounty hunters}
{10042060}{}{Some bounty hunters}
{10042070}{}{Some bounty hunters}
{10042080}{}{Some bounty hunters}
{10042090}{}{Some bounty hunters}
{10042100}{}{Some bounty hunters}
{10042110}{}{Some bounty hunters}
{10042120}{}{A band of ruffians led by a Morton Brother}
{10042130}{}{Some mutated pig rats}
{10042140}{}{Some spore plants}
{10042150}{}{A hermit and some dogs fighting mutated molerats}
{10042160}{}{A hermit fending off some wild dogs}
{10042170}{}{A hermit fending off some mutated pig rats}
{10042180}{}{A hermit with some dogs fighting mutated molerats}
{10042190}{}{Some mutated molerats fighting some mutated pig rats}
{10042200}{}{Some mutated molerats fighting some spore plants}
{10042210}{}{Some mutated pig rats fighting some wild dogs}
{10042220}{}{A hermit}
{10042230}{}{The remains of a whale}
{10042240}{}{A giant stone head}
{10042250}{}{A crashed shuttle}
{10042260}{}{A Guardian Portal}
{10042270}{}{King Arthur's Knights}
{10042280}{}{A tin woodsman}
{10042290}{}{The Unwashed Villagers hunting a spammer}
{10042300}{}{секретное логово супермутантов}

# Encounter Table 25
{10042500}{}{Some mutated molerats}
{10042510}{}{Some mutated pig rats}
{10042520}{}{Some spore plants}
{10042530}{}{A hermit and some dogs fighting mutated molerats}
{10042540}{}{Some bounty hunters}
{10042550}{}{Some bounty hunters}
{10042560}{}{Some bounty hunters}
{10042570}{}{Some bounty hunters}
{10042580}{}{Some bounty hunters}
{10042590}{}{Some bounty hunters}
{10042600}{}{Some bounty hunters}
{10042610}{}{Some bounty hunters}
{10042620}{}{A band of ruffians led by a Morton Brother}
{10042630}{}{A hermit fending off some wild dogs}
{10042640}{}{A hermit fending off some mutated pig rats}
{10042650}{}{A hermit with some dogs fighting mutated molerats}
{10042660}{}{Some mutated molerats fighting some mutated pig rats}
{10042670}{}{Some mutated molerats fighting some spore plants}
{10042680}{}{Some mutated pig rats fighting some wild dogs}
{10042690}{}{A hermit}
{10042700}{}{A man guarding a bridge}
{10042710}{}{King Arthur's Knights fighting a rat}

# Encounter Table 26
{10043000}{}{A band of slavers and some dogs}
{10043010}{}{A band of slavers}
{10043020}{}{Some golden geckos}
{10043030}{}{A pack of wild dogs}
{10043040}{}{Some bounty hunters}
{10043050}{}{Some bounty hunters}
{10043060}{}{Some bounty hunters}
{10043070}{}{Some bounty hunters}
{10043080}{}{Some bounty hunters}
{10043090}{}{Some bounty hunters}
{10043100}{}{Some bounty hunters}
{10043110}{}{Some bounty hunters}
{10043120}{}{A band of ruffians led by a Morton Brother}
{10043130}{}{A patrol unit and dogs subduing slavers}
{10043140}{}{A band of slavers fending off some golden geckos}
{10043150}{}{A patrol unit fighting some slavers}
{10043160}{}{A patrol unit battling some golden geckos}
{10043170}{}{A patrol unit fending off wild dogs}
{10043180}{}{A patrol unit}
{10043190}{}{A man guarding a bridge}
{10043200}{}{King Arthur's Knights fighting a rat}

# Encounter Table 27
{10043500}{}{Toxic waste dump}
{10043510}{}{A lone surviving dog}
{10043520}{}{A herd of brahmin}
{10043530}{}{A band of slavers and some dogs}
{10043540}{}{Some bounty hunters}
{10043550}{}{Some bounty hunters}
{10043560}{}{Some bounty hunters}
{10043570}{}{Some bounty hunters}
{10043580}{}{Some bounty hunters}
{10043590}{}{Some bounty hunters}
{10043600}{}{Some bounty hunters}
{10043610}{}{Some bounty hunters}
{10043620}{}{A band of ruffians led by a Morton Brother}
{10043630}{}{A band of slavers}
{10043640}{}{Some golden geckos}
{10043650}{}{A pack of wild dogs}
{10043660}{}{A patrol unit and dogs subduing slavers}
{10043670}{}{A band of slavers fending off some golden geckos}
{10043680}{}{A patrol unit fighting some slavers}
{10043690}{}{A patrol unit battling some golden geckos}
{10043700}{}{A patrol unit fending off wild dogs}
{10043710}{}{A patrol unit}
{10043720}{}{The remains of a whale}
{10043730}{}{A giant stone head}
{10043740}{}{A crashed shuttle}
{10043750}{}{A Guardian Portal}
{10043760}{}{King Arthur's Knights}
{10043770}{}{A tin woodsman}
{10043780}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 28
{10044000}{}{A slew of scavengers}
{10044010}{}{Some ghoul scavengers}
{10044020}{}{A bunch of crazies}
{10044030}{}{Some ghoul crazies}
{10044040}{}{Some bounty hunters}
{10044050}{}{Some bounty hunters}
{10044060}{}{Some bounty hunters}
{10044070}{}{Some bounty hunters}
{10044080}{}{Some bounty hunters}
{10044090}{}{Some bounty hunters}
{10044100}{}{Some bounty hunters}
{10044110}{}{Some bounty hunters}
{10044120}{}{A band of ruffians led by a Morton Brother}
{10044130}{}{Some geckos}
{10044140}{}{A pack of wild dogs}
{10044150}{}{A family of radscorpions}
{10044160}{}{A bunch of mutated pig rats}
{10044170}{}{A pack of mutated rats}
{10044180}{}{Some scavengers battling a bunch of crazies}
{10044190}{}{Some ghoul scavengers fending off some crazies}
{10044200}{}{Some geckos fighting some crazies}
{10044210}{}{Some mutated rats infesting some ghoul scavengers}
{10044220}{}{A man guarding a bridge}
{10044230}{}{King Arthur's Knights fighting a rat}

# Encounter Table 29
{10044500}{}{Toxic waste dump}
{10044510}{}{A lone surviving dog}
{10044520}{}{A herd of brahmin}
{10044530}{}{A slew of scavengers}
{10044540}{}{Some bounty hunters}
{10044550}{}{Some bounty hunters}
{10044560}{}{Some bounty hunters}
{10044570}{}{Some bounty hunters}
{10044580}{}{Some bounty hunters}
{10044590}{}{Some bounty hunters}
{10044600}{}{Some bounty hunters}
{10044610}{}{Some bounty hunters}
{10044620}{}{A band of ruffians led by a Morton Brother}
{10044630}{}{Some ghoul scavengers}
{10044640}{}{A bunch of crazies}
{10044650}{}{Some ghoul crazies}
{10044660}{}{Some geckos}
{10044670}{}{A pack of wild dogs}
{10044680}{}{A family of radscorpions}
{10044690}{}{A bunch of mutated pig rats}
{10044700}{}{A pack of mutated rats}
{10044710}{}{Some scavengers battling a bunch of crazies}
{10044720}{}{Some ghoul scavengers fending off some crazies}
{10044730}{}{Some geckos fighting some crazies}
{10044740}{}{Some mutated rats infesting some ghoul scavengers}
{10044750}{}{The remains of a whale}
{10044760}{}{A giant stone head}
{10044770}{}{A crashed shuttle}
{10044780}{}{A Guardian Portal}
{10044790}{}{King Arthur's Knights}
{10044800}{}{A tin woodsman}
{10044810}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 30
{10045000}{}{Some cannibals}
{10045010}{}{Some wilders}
{10045020}{}{A war party}
{10045030}{}{some outcasts}
{10045040}{}{Some bounty hunters}
{10045050}{}{Some bounty hunters}
{10045060}{}{Some bounty hunters}
{10045070}{}{Some bounty hunters}
{10045080}{}{Some bounty hunters}
{10045090}{}{Some bounty hunters}
{10045100}{}{Some bounty hunters}
{10045110}{}{Some bounty hunters}
{10045120}{}{A band of ruffians led by a Morton Brother}
{10045130}{}{A family of radscorpions}
{10045140}{}{Some molerats}
{10045150}{}{Some fishermen fending off some cannibals}
{10045160}{}{Some cannibals battling some wilders}
{10045170}{}{Some radscorpions attacking some wilders}
{10045180}{}{Some fishermen}

# Encounter Table 31
{10045500}{}{Toxic waste dump}
{10045510}{}{A lone surviving dog}
{10045520}{}{A herd of brahmin}
{10045530}{}{Some cannibals}
{10045540}{}{Some bounty hunters}
{10045550}{}{Some bounty hunters}
{10045560}{}{Some bounty hunters}
{10045570}{}{Some bounty hunters}
{10045580}{}{Some bounty hunters}
{10045590}{}{Some bounty hunters}
{10045600}{}{Some bounty hunters}
{10045610}{}{Some bounty hunters}
{10045620}{}{A band of ruffians led by a Morton Brother}
{10045630}{}{Some outcasts}
{10045640}{}{Some wilders}
{10045650}{}{A war party}
{10045660}{}{Some geckos hiding in some spore plants}
{10045670}{}{Some geckos and some radscorpions}
{10045680}{}{Some geckos}
{10045690}{}{Some radscorpions hiding in some spore plants}
{10045700}{}{Some scorpions}
{10045710}{}{Some geckos attacking some outcasts}
{10045720}{}{Some geckos fighting some wilders}
{10045730}{}{Some radscorpions fighting some cannibals}
{10045740}{}{Some radscorpions attacking a hermit}
{10045750}{}{A hermit}
{10045760}{}{The remains of a whale}
{10045770}{}{A giant stone head}
{10045780}{}{A crashed shuttle}
{10045790}{}{A Guardian Portal}
{10045800}{}{King Arthur's Knights}
{10045810}{}{A tin woodsman}
{10045820}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 32
{10046000}{}{Some cannibals}
{10046010}{}{Some outcasts}
{10046020}{}{Some wilders}
{10046030}{}{A war party}
{10046040}{}{Some bounty hunters}
{10046050}{}{Some bounty hunters}
{10046060}{}{Some bounty hunters}
{10046070}{}{Some bounty hunters}
{10046080}{}{Some bounty hunters}
{10046090}{}{Some bounty hunters}
{10046100}{}{Some bounty hunters}
{10046110}{}{Some bounty hunters}
{10046120}{}{A band of ruffians led by a Morton Brother}
{10046130}{}{Some geckos hiding in some spore plants}
{10046140}{}{Some geckos and some radscorpions}
{10046150}{}{Some geckos}
{10046160}{}{Some radscorpions hiding in some spore plants}
{10046170}{}{Some scorpions}
{10046180}{}{Some geckos attacking some outcasts}
{10046190}{}{Some geckos fighting some wilders}
{10046200}{}{Some radscorpions fighting some cannibals}
{10046210}{}{Some radscorpions attacking a hermit}
{10046220}{}{A hermit}
{10046230}{}{A man guarding a bridge}
{10046240}{}{King Arthur's Knights fighting a rat}

# Encounter Table 33
{10046500}{}{Toxic waste dump}
{10046510}{}{A lone surviving dog}
{10046520}{}{A herd of brahmin}
{10046530}{}{A Den caravan}
{10046540}{}{Some bounty hunters}
{10046550}{}{Some bounty hunters}
{10046560}{}{Some bounty hunters}
{10046570}{}{Some bounty hunters}
{10046580}{}{Some bounty hunters}
{10046590}{}{Some bounty hunters}
{10046600}{}{Some bounty hunters}
{10046610}{}{Some bounty hunters}
{10046620}{}{A band of ruffians led by a Morton Brother}
{10046630}{}{Some highwaymen and robbers}
{10046640}{}{Some highwaymen}
{10046650}{}{Some robbers}
{10046660}{}{A Redding caravan fending off highwaymen}
{10046670}{}{A New Reno caravan fending off robbers}
{10046680}{}{A Den caravan fending off highwaymen}
{10046690}{}{Some robbers ambushing a caravan}
{10046700}{}{A Den caravan attacking a Vault City caravan}
{10046710}{}{Some highwaymen fighting some robbers}
{10046720}{}{A Vault City caravan}
{10046730}{}{A Den caravan}
{10046740}{}{The remains of a whale}
{10046750}{}{A giant stone head}
{10046760}{}{A crashed shuttle}
{10046770}{}{A Guardian Portal}
{10046780}{}{King Arthur's Knights}
{10046790}{}{A tin woodsman}
{10046800}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 34
{10047000}{}{A Den caravan}
{10047010}{}{Some highwaymen and robbers}
{10047020}{}{Some highwaymen}
{10047030}{}{Some robbers}
{10047040}{}{Some bounty hunters}
{10047050}{}{Some bounty hunters}
{10047060}{}{Some bounty hunters}
{10047070}{}{Some bounty hunters}
{10047080}{}{Some bounty hunters}
{10047090}{}{Some bounty hunters}
{10047100}{}{Some bounty hunters}
{10047110}{}{Some bounty hunters}
{10047120}{}{A band of ruffians led by a Morton Brother}
{10047130}{}{A Redding caravan fending off highwaymen}
{10047140}{}{A New Reno caravan fending off robbers}
{10047150}{}{A Den caravan fending off highwaymen}
{10047160}{}{Some robbers ambushing a caravan}
{10047170}{}{A Den caravan attacking a Vault City caravan}
{10047180}{}{Some highwaymen fighting some robbers}
{10047190}{}{A Vault City caravan}
{10047200}{}{A Den caravan}
{10047210}{}{A man guarding a bridge}
{10047220}{}{King Arthur's Knights fighting a rat}

# Encounter Table 35
{10047500}{}{Toxic waste dump}
{10047510}{}{A lone surviving dog}
{10047520}{}{A herd of brahmin}
{10047530}{}{Some geckos and some wolves}
{10047540}{}{Some bounty hunters}
{10047550}{}{Some bounty hunters}
{10047560}{}{Some bounty hunters}
{10047570}{}{Some bounty hunters}
{10047580}{}{Some bounty hunters}
{10047590}{}{Some bounty hunters}
{10047600}{}{Some bounty hunters}
{10047610}{}{Some bounty hunters}
{10047620}{}{A band of ruffians led by a Morton Brother}
{10047630}{}{Some claim jumpers}
{10047640}{}{Some wolves}
{10047650}{}{Some geckos}
{10047660}{}{Some prospectors fighting some claim jumpers}
{10047670}{}{Some trappers fighting some geckos}
{10047680}{}{Some bootleggers fighting some wolves}
{10047690}{}{Some homesteaders fighting some claim jumpers}
{10047700}{}{Some homesteaders fending off some wolves}
{10047710}{}{Some bootleggers}
{10047720}{}{Some trappers}
{10047730}{}{Some prospectors}
{10047740}{}{The remains of a whale}
{10047750}{}{A giant stone head}
{10047760}{}{A crashed shuttle}
{10047770}{}{A Guardian Portal}
{10047780}{}{King Arthur's Knights}
{10047790}{}{A tin woodsman}
{10047800}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 36
{10048000}{}{Some geckos and some wolves}
{10048010}{}{Some claim jumpers}
{10048020}{}{Some wolves}
{10048030}{}{Some geckos}
{10048040}{}{Some bounty hunters}
{10048050}{}{Some bounty hunters}
{10048060}{}{Some bounty hunters}
{10048070}{}{Some bounty hunters}
{10048080}{}{Some bounty hunters}
{10048090}{}{Some bounty hunters}
{10048100}{}{Some bounty hunters}
{10048110}{}{Some bounty hunters}
{10048120}{}{A band of ruffians led by a Morton Brother}
{10048130}{}{Some prospectors fighting some claim jumpers}
{10048140}{}{Some trappers fighting some geckos}
{10048150}{}{Some bootleggers fighting some wolves}
{10048160}{}{Some homesteaders fighting some claim jumpers}
{10048170}{}{Some homesteaders fending off some wolves}
{10048180}{}{Some bootleggers}
{10048190}{}{Some trappers}
{10048200}{}{Some prospectors}
{10048210}{}{A man guarding a bridge}
{10048220}{}{King Arthur's Knights fighting a rat}

# Encounter Table 37
{10048500}{}{A pack of wolves and some molerats}
{10048510}{}{Some radscorpions and some wolves}
{10048520}{}{Some mutated molerats and some radscorpions}
{10048530}{}{A pack of geckos}
{10048540}{}{Some bounty hunters}
{10048550}{}{Some bounty hunters}
{10048560}{}{Some bounty hunters}
{10048570}{}{Some bounty hunters}
{10048580}{}{Some bounty hunters}
{10048590}{}{Some bounty hunters}
{10048600}{}{Some bounty hunters}
{10048610}{}{Some bounty hunters}
{10048620}{}{A band of ruffians led by a Morton Brother}
{10048630}{}{A pack of wolves}
{10048640}{}{A pack of mutated molerats}
{10048650}{}{A pack of radscorpions}
{10048660}{}{A pack of wolves and some geckos}
{10048670}{}{Some mutated molerats fighting some geckos}
{10048680}{}{Some molerats fighting some radscorpions}
{10048690}{}{A man guarding a bridge}
{10048700}{}{King Arthur's Knights fighting a rat}

# Encounter Table 38
{10049000}{}{A band of raiders}
{10049010}{}{Some wolves}
{10049020}{}{A caravan fending off some raiders}
{10049030}{}{A caravan fending off some raiders}
{10049040}{}{Some bounty hunters}
{10049050}{}{Some bounty hunters}
{10049060}{}{Some bounty hunters}
{10049070}{}{Some bounty hunters}
{10049080}{}{Some bounty hunters}
{10049090}{}{Some bounty hunters}
{10049100}{}{Some bounty hunters}
{10049110}{}{Some bounty hunters}
{10049120}{}{A band of ruffians led by a Morton Brother}
{10049130}{}{A caravan fending off some raiders}
{10049140}{}{A caravan fending off some raiders}
{10049150}{}{A caravan}
{10049160}{}{A caravan}
{10049170}{}{A caravan}
{10049180}{}{A caravan}
{10049190}{}{A man guarding a bridge}
{10049200}{}{King Arthur's Knights fighting a rat}

# Encounter Table 39
{10049500}{}{Toxic waste dump}
{10049510}{}{A lone surviving dog}
{10049520}{}{A herd of brahmin}
{10049530}{}{A band of raiders}
{10049540}{}{Some bounty hunters}
{10049550}{}{Some bounty hunters}
{10049560}{}{Some bounty hunters}
{10049570}{}{Some bounty hunters}
{10049580}{}{Some bounty hunters}
{10049590}{}{Some bounty hunters}
{10049600}{}{Some bounty hunters}
{10049610}{}{Some bounty hunters}
{10049620}{}{A band of ruffians led by a Morton Brother}
{10049630}{}{Some wolves}
{10049640}{}{A caravan fending off some raiders}
{10049650}{}{A caravan fending off some raiders}
{10049660}{}{A caravan fending off some raiders}
{10049670}{}{A caravan fending off some raiders}
{10049680}{}{A caravan}
{10049690}{}{A caravan}
{10049700}{}{A caravan}
{10049710}{}{A caravan}
{10049720}{}{The remains of a whale}
{10049730}{}{A giant stone head}
{10049740}{}{A crashed shuttle}
{10049750}{}{A Guardian Portal}
{10049760}{}{King Arthur's Knights}
{10049770}{}{A tin woodsman}
{10049780}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 40
{10050000}{}{A band of raiders leading some wolves}
{10050010}{}{Some spore plants and some wolves}
{10050020}{}{A band of raiders}
{10050030}{}{A pack of wolves}
{10050040}{}{Some bounty hunters}
{10050050}{}{Some bounty hunters}
{10050060}{}{Some bounty hunters}
{10050070}{}{Some bounty hunters}
{10050080}{}{Some bounty hunters}
{10050090}{}{Some bounty hunters}
{10050100}{}{Some bounty hunters}
{10050110}{}{Some bounty hunters}
{10050120}{}{A band of ruffians led by a Morton Brother}
{10050130}{}{A pack of radscorpions}
{10050140}{}{A pack of wolves fighting some raiders}
{10050150}{}{A man guarding a bridge}
{10050160}{}{King Arthur's Knights fighting a rat}

# Encounter Table 41
{10050500}{}{Toxic waste dump}
{10050510}{}{A lone surviving dog}
{10050520}{}{A herd of brahmin}
{10050530}{}{A band of raiders leading some wolves}
{10050540}{}{Some bounty hunters}
{10050550}{}{Some bounty hunters}
{10050560}{}{Some bounty hunters}
{10050570}{}{Some bounty hunters}
{10050580}{}{Some bounty hunters}
{10050590}{}{Some bounty hunters}
{10050600}{}{Some bounty hunters}
{10050610}{}{Some bounty hunters}
{10050620}{}{A band of ruffians led by a Morton Brother}
{10050630}{}{Some spore plants and some wolves}
{10050640}{}{A band of raiders}
{10050650}{}{A pack of wolves}
{10050660}{}{A pack of radscorpions}
{10050670}{}{A pack of wolves fighting some raiders}
{10050680}{}{The remains of a whale}
{10050690}{}{A giant stone head}
{10050700}{}{A crashed shuttle}
{10050710}{}{A Guardian Portal}
{10050720}{}{King Arthur's Knights}
{10050730}{}{A tin woodsman}
{10050740}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 42
{10051000}{}{Toxic waste dump}
{10051010}{}{A lone surviving dog}
{10051020}{}{A herd of brahmin}
{10051030}{}{An Enclave Patrol}
{10051040}{}{Some bounty hunters}
{10051050}{}{Some bounty hunters}
{10051060}{}{Some bounty hunters}
{10051070}{}{Some bounty hunters}
{10051080}{}{Some bounty hunters}
{10051090}{}{Some bounty hunters}
{10051100}{}{Some bounty hunters}
{10051110}{}{Some bounty hunters}
{10051120}{}{A band of ruffians led by a Morton Brother}
{10051130}{}{The remains of a whale}
{10051140}{}{A giant stone head}
{10051150}{}{A crashed shuttle}
{10051160}{}{A Guardian Portal}
{10051170}{}{King Arthur's Knights}
{10051180}{}{A tin woodsman}
{10051190}{}{The Unwashed Villagers hunting a spammer}
{10051200}{}{The Cafe of Broken Dreams}

# Encounter Table 43
{10051500}{}{An Enclave Patrol}
{10051510}{}{Some bounty hunters}
{10051520}{}{Some bounty hunters}
{10051530}{}{Some bounty hunters}
{10051540}{}{Some bounty hunters}
{10051550}{}{Some bounty hunters}
{10051560}{}{Some bounty hunters}
{10051570}{}{Some bounty hunters}
{10051580}{}{Some bounty hunters}
{10051590}{}{A band of ruffians led by a Morton Brother}
{10051600}{}{A man guarding a bridge}
{10051610}{}{King Arthur's Knights fighting a rat}

# Encounter Table 44
{10052000}{}{An Enclave Patrol}
{10052010}{}{Some bounty hunters}
{10052020}{}{Some bounty hunters}
{10052030}{}{Some bounty hunters}
{10052040}{}{Some bounty hunters}
{10052080}{}{Some bounty hunters}
{10052090}{}{Some bounty hunters}
{10052100}{}{Some bounty hunters}
{10052110}{}{Some bounty hunters}
{10052120}{}{A band of ruffians led by a Morton Brother}

# Encounter Table 45
{10052500}{}{Toxic waste dump}
{10052510}{}{A lone surviving dog}
{10052520}{}{A herd of brahmin}
{10052530}{}{Some aliens and deathclaws}
{10052540}{}{Some bounty hunters}
{10052550}{}{Some bounty hunters}
{10052560}{}{Some bounty hunters}
{10052570}{}{Some bounty hunters}
{10052580}{}{Some bounty hunters}
{10052590}{}{Some bounty hunters}
{10052600}{}{Some bounty hunters}
{10052610}{}{Some bounty hunters}
{10052620}{}{A band of ruffians led by a Morton Brother}
{10052630}{}{An army of floaters and centaurs}
{10052640}{}{Some fire geckos}
{10052650}{}{A large pack of aliens}
{10052660}{}{Some deathclaws}
{10052670}{}{Some fire geckos}
{10052680}{}{Some aliens}
{10052690}{}{A pack of centaurs}
{10052700}{}{A swarm of floaters}
{10052710}{}{The remains of a whale}
{10052720}{}{A giant stone head}
{10052730}{}{A crashed shuttle}
{10052740}{}{A Guardian Portal}
{10052750}{}{King Arthur's Knights}
{10052760}{}{A tin woodsman}
{10052770}{}{The Unwashed Villagers hunting a spammer}
{10052780}{}{The Cafe of Broken Dreams}

# Encounter Table 46
{10053000}{}{Some aliens and deathclaws}
{10053010}{}{An army of floaters and centaurs}
{10053020}{}{Some fire geckos}
{10053030}{}{A large pack of aliens}
{10053040}{}{Some bounty hunters}
{10053050}{}{Some bounty hunters}
{10053060}{}{Some bounty hunters}
{10053070}{}{Some bounty hunters}
{10053080}{}{Some bounty hunters}
{10053090}{}{Some bounty hunters}
{10053100}{}{Some bounty hunters}
{10053110}{}{Some bounty hunters}
{10053120}{}{A band of ruffians led by a Morton Brother}
{10053130}{}{Some deathclaws}
{10053140}{}{Some fire geckos}
{10053150}{}{Some aliens}
{10053160}{}{A pack of centaurs}
{10053170}{}{A swarm of floaters}
{10053180}{}{A man guarding a bridge}
{10053190}{}{King Arthur's Knights fighting a rat}
{10053200}{}{strange alone house}

# Encounter Table 47
{10053500}{}{Some aliens and deathclaws}
{10053510}{}{An army of floaters and centaurs}
{10053520}{}{Some fire geckos}
{10053530}{}{A large pack of aliens}
{10053540}{}{Some bounty hunters}
{10053550}{}{Some bounty hunters}
{10053560}{}{Some bounty hunters}
{10053570}{}{Some bounty hunters}
{10053580}{}{Some bounty hunters}
{10053590}{}{Some bounty hunters}
{10053600}{}{Some bounty hunters}
{10053610}{}{Some bounty hunters}
{10053620}{}{A band of ruffians led by a Morton Brother}
{10053630}{}{Some deathclaws}
{10053640}{}{Some fire geckos}
{10053650}{}{Some aliens}
{10053660}{}{A pack of centaurs}
{10053670}{}{A swarm of floaters}

# Encounter Table 48
{10054000}{}{Toxic waste dump}
{10054010}{}{A lone surviving dog}
{10054020}{}{A herd of brahmin}
{10054030}{}{A pack of fire geckos}
{10054040}{}{Some bounty hunters}
{10054050}{}{Some bounty hunters}
{10054060}{}{Some bounty hunters}
{10054070}{}{Some bounty hunters}
{10054080}{}{Some bounty hunters}
{10054090}{}{Some bounty hunters}
{10054100}{}{Some bounty hunters}
{10054110}{}{Some bounty hunters}
{10054120}{}{A band of ruffians led by a Morton Brother}
{10054130}{}{A pack of fire geckos}
{10054140}{}{A large pack of golden geckos}
{10054150}{}{The remains of a whale}
{10054160}{}{A giant stone head}
{10054170}{}{A crashed shuttle}
{10054180}{}{A Guardian Portal}
{10054190}{}{King Arthur's Knights}
{10054200}{}{A tin woodsman}
{10054210}{}{The Unwashed Villagers hunting a spammer}
{10054220}{}{The Cafe of Broken Dreams}
{10054230}{}{The Mad scientist's lab}
{10054240}{}{заброшенный аванпост Рыцарей Пустоши}
{10054250}{}{the lost doughnut warehouse}
{10054260}{}{the ruins of a church}

# Encounter Table 49
{10054500}{}{A pack of fire geckos}
{10054510}{}{A pack of fire geckos}
{10054520}{}{A large pack of golden geckos}
{10054530}{}{Some bounty hunters}
{10054540}{}{Some bounty hunters}
{10054550}{}{Some bounty hunters}
{10054560}{}{Some bounty hunters}
{10054570}{}{Some bounty hunters}
{10054580}{}{Some bounty hunters}
{10054590}{}{Some bounty hunters}
{10054600}{}{Some bounty hunters}
{10054610}{}{A band of ruffians led by a Morton Brother}
{10054620}{}{A man guarding a bridge}
{10054630}{}{King Arthur's Knights fighting a rat}

# Encounter Table 50
{10055000}{}{A pack of fire geckos}
{10055010}{}{A pack of fire geckos}
{10055020}{}{A large pack of golden geckos}
{10055030}{}{Some bounty hunters}
{10055040}{}{Some bounty hunters}
{10055050}{}{Some bounty hunters}
{10055060}{}{Some bounty hunters}
{10055070}{}{Some bounty hunters}
{10055080}{}{Some bounty hunters}
{10055090}{}{Some bounty hunters}
{10055100}{}{Some bounty hunters}
{10055110}{}{A band of ruffians led by a Morton Brother}

# Encounter Table 51
{10055500}{}{Toxic waste dump}
{10055510}{}{A lone surviving dog}
{10055520}{}{A herd of brahmin}
{10055530}{}{A pack of deathclaws}
{10055540}{}{Some bounty hunters}
{10055550}{}{Some bounty hunters}
{10055560}{}{Some bounty hunters}
{10055570}{}{Some bounty hunters}
{10055580}{}{Some bounty hunters}
{10055590}{}{Some bounty hunters}
{10055600}{}{Some bounty hunters}
{10055610}{}{Some bounty hunters}
{10055620}{}{A band of ruffians led by a Morton Brother}
{10055630}{}{A pack of fire geckos}
{10055640}{}{A caravan fending off deathclaws}
{10055650}{}{A caravan fending off deathclaws}
{10055660}{}{A caravan fending off fire geckos}
{10055670}{}{A caravan fending off fire geckos}
{10055680}{}{A caravan}
{10055690}{}{A caravan}
{10055700}{}{A caravan}
{10055710}{}{A caravan}
{10055720}{}{The remains of a whale}
{10055730}{}{A giant stone head}
{10055740}{}{A crashed shuttle}
{10055750}{}{A Guardian Portal}
{10055760}{}{King Arthur's Knights}
{10055770}{}{A tin woodsman}
{10055780}{}{The Unwashed Villagers hunting a spammer}
{10055790}{}{заброшенную лабораторию безумного ученого}
{10055800}{}{заброшенный аванпост Рыцарей Пустоши}
{10055810}{}{the lost doughnut warehouse}

# Encounter Table 52
{10056000}{}{A pack of deathclaws}
{10056010}{}{A pack of fire geckos}
{10056020}{}{A caravan fending off deathclaws}
{10056030}{}{A caravan fending off deathclaws}
{10056040}{}{Some bounty hunters}
{10056050}{}{Some bounty hunters}
{10056060}{}{Some bounty hunters}
{10056070}{}{Some bounty hunters}
{10056080}{}{Some bounty hunters}
{10056090}{}{Some bounty hunters}
{10056100}{}{Some bounty hunters}
{10056110}{}{Some bounty hunters}
{10056120}{}{A band of ruffians led by a Morton Brother}
{10056130}{}{A caravan fending off fire geckos}
{10056140}{}{A caravan fending off fire geckos}
{10056150}{}{A caravan}
{10056160}{}{A caravan}
{10056170}{}{A caravan}
{10056180}{}{A caravan}
{10056190}{}{A man guarding a bridge}
{10056200}{}{King Arthur's Knights fighting a rat}

# Encounter Table 53
{10056500}{}{Toxic waste dump}
{10056510}{}{A lone surviving dog}
{10056520}{}{A herd of brahmin}
{10056530}{}{Some yakuza}
{10056540}{}{Some bounty hunters}
{10056550}{}{Some bounty hunters}
{10056560}{}{Some bounty hunters}
{10056570}{}{Some bounty hunters}
{10056580}{}{Some bounty hunters}
{10056590}{}{Some bounty hunters}
{10056600}{}{Some bounty hunters}
{10056610}{}{Some bounty hunters}
{10056620}{}{A band of ruffians led by a Morton Brother}
{10056630}{}{A gang}
{10056640}{}{A pack of wolves}
{10056650}{}{Some mobsters fighting some yakuza}
{10056660}{}{Some mobsters fighting a gang}
{10056670}{}{Some mobsters}
{10056680}{}{A traveler}
{10056690}{}{The remains of a whale}
{10056700}{}{A giant stone head}
{10056710}{}{A crashed shuttle}
{10056720}{}{A Guardian Portal}
{10056730}{}{King Arthur's Knights}
{10056740}{}{A tin woodsman}
{10056750}{}{The Unwashed Villagers hunting a spammer}
{10056760}{}{The Cafe of Broken Dreams}

# Encounter Table 54
{10057000}{}{Some yakuza}
{10057010}{}{A gang}
{10057020}{}{A pack of wolves}
{10057030}{}{Some mobsters fighting some yakuza}
{10057040}{}{Some bounty hunters}
{10057050}{}{Some bounty hunters}
{10057060}{}{Some bounty hunters}
{10057070}{}{Some bounty hunters}
{10057080}{}{Some bounty hunters}
{10057090}{}{Some bounty hunters}
{10057100}{}{Some bounty hunters}
{10057110}{}{Some bounty hunters}
{10057120}{}{A band of ruffians led by a Morton Brother}
{10057130}{}{Some mobsters fighting a gang}
{10057140}{}{Some mobsters}
{10057150}{}{A traveler}
{10057160}{}{A man guarding a bridge}
{10057170}{}{King Arthur's Knights fighting a rat}

# Encounter Table 55
{10057500}{}{Some yakuza}
{10057510}{}{A gang}
{10057520}{}{A pack of wolves}
{10057530}{}{Some mobsters fighting some yakuza}
{10057540}{}{Some bounty hunters}
{10057550}{}{Some bounty hunters}
{10057560}{}{Some bounty hunters}
{10057570}{}{Some bounty hunters}
{10057580}{}{Some bounty hunters}
{10057590}{}{Some bounty hunters}
{10057600}{}{Some bounty hunters}
{10057610}{}{Some bounty hunters}
{10057620}{}{A band of ruffians led by a Morton Brother}
{10057630}{}{Some mobsters fighting a gang}
{10057640}{}{Some mobsters}
{10057650}{}{A traveler}
{10057660}{}{the ruins of a church}

# Encounter Table 56
{10058000}{}{Toxic waste dump}
{10058010}{}{A lone surviving dog}
{10058020}{}{A herd of brahmin}
{10058030}{}{A band of rogues and some wolves}
{10058040}{}{Some bounty hunters}
{10058050}{}{Some bounty hunters}
{10058060}{}{Some bounty hunters}
{10058070}{}{Some bounty hunters}
{10058080}{}{Some bounty hunters}
{10058090}{}{Some bounty hunters}
{10058100}{}{Some bounty hunters}
{10058110}{}{Some bounty hunters}
{10058120}{}{A band of ruffians led by a Morton Brother}
{10058130}{}{A band of rogues}
{10058140}{}{A pack of wolves}
{10058150}{}{A pack of radscorpions}
{10058160}{}{A forest of spore plants}
{10058170}{}{A Unity patrol fighting some rogues}
{10058180}{}{A Unity patrol fighting some wolves}
{10058190}{}{A Unity patrol}
{10058200}{}{The remains of a whale}
{10058210}{}{A giant stone head}
{10058220}{}{A crashed shuttle}
{10058230}{}{A Guardian Portal}
{10058240}{}{King Arthur's Knights}
{10058250}{}{A tin woodsman}
{10058260}{}{The Unwashed Villagers hunting a spammer}

# Encounter Table 57
{10058500}{}{A band of rogues and some wolves}
{10058510}{}{A band of rogues}
{10058520}{}{A pack of wolves}
{10058530}{}{A pack of radscorpions}
{10058540}{}{Some bounty hunters}
{10058550}{}{Some bounty hunters}
{10058560}{}{Some bounty hunters}
{10058570}{}{Some bounty hunters}
{10058580}{}{Some bounty hunters}
{10058590}{}{Some bounty hunters}
{10058600}{}{Some bounty hunters}
{10058610}{}{Some bounty hunters}
{10058620}{}{A band of ruffians led by a Morton Brother}
{10058630}{}{A forest of spore plants}
{10058640}{}{A Unity patrol fighting some rogues}
{10058650}{}{A Unity patrol fighting some wolves}
{10058660}{}{A Unity patrol}
{10058670}{}{A man guarding a bridge}
{10058680}{}{King Arthur's Knights fighting a rat}

# Encounter Table 58
{10059000}{}{A band of mercenaries}
{10059010}{}{A press gang}
{10059020}{}{A herd of deathclaws}
{10059030}{}{A batch of fire geckos}
{10059040}{}{Some bounty hunters}
{10059050}{}{Some bounty hunters}
{10059060}{}{Some bounty hunters}
{10059070}{}{Some bounty hunters}
{10059080}{}{Some bounty hunters}
{10059090}{}{Some bounty hunters}
{10059100}{}{Some bounty hunters}
{10059110}{}{Some bounty hunters}
{10059120}{}{A band of ruffians led by a Morton Brother}
{10059130}{}{A slew of aliens}
{10059140}{}{Hubologists fighting mercenaries}
{10059150}{}{Hubologists fending off a press gang}
{10059160}{}{Hubologists}
{10059170}{}{насекомых-мутантов}
{10059180}{}{палатку наркодилеров, о которой говорила Нэнси по радио}
{10059190}{}{the ruins of a church}

# Encounter Table 59
{10059500}{}{A band of mercenaries}
{10059510}{}{A press gang}
{10059520}{}{A herd of deathclaws}
{10059530}{}{A batch of fire geckos}
{10059540}{}{Some bounty hunters}
{10059550}{}{Some bounty hunters}
{10059560}{}{Some bounty hunters}
{10059570}{}{Some bounty hunters}
{10059580}{}{Some bounty hunters}
{10059590}{}{Some bounty hunters}
{10059600}{}{Some bounty hunters}
{10059610}{}{Some bounty hunters}
{10059620}{}{A band of ruffians led by a Morton Brother}
{10059630}{}{A slew of aliens}
{10059640}{}{Hubologists fighting mercenaries}
{10059650}{}{Hubologists fending off a press gang}
{10059660}{}{Hubologists}
{10059670}{}{A man guarding a bridge}
{10059680}{}{King Arthur's Knights fighting a rat}

# Encounter Table 60
{10060000}{}{A band of mercenaries}
{10060010}{}{A press gang}
{10060020}{}{A herd of deathclaws}
{10060030}{}{A batch of fire geckos}
{10060040}{}{Some bounty hunters}
{10060050}{}{Some bounty hunters}
{10060060}{}{Some bounty hunters}
{10060070}{}{Some bounty hunters}
{10060080}{}{Some bounty hunters}
{10060090}{}{Some bounty hunters}
{10060100}{}{Some bounty hunters}
{10060110}{}{Some bounty hunters}
{10060120}{}{A band of ruffians led by a Morton Brother}
{10060130}{}{A slew of aliens}
{10060140}{}{Hubologists fighting mercenaries}
{10060150}{}{Hubologists fending off a press gang}
{10060160}{}{Hubologists}
{10060170}{}{группу насекомых-мутантов}
{10060180}{}{разрушенную церковь}

# Encounter Table 61
{10060500}{}{Toxic waste dump}
{10060510}{}{A lone surviving dog}
{10060520}{}{A herd of brahmin}
{10060530}{}{A band of mercenaries}
{10060540}{}{Some bounty hunters}
{10060550}{}{Some bounty hunters}
{10060560}{}{Some bounty hunters}
{10060570}{}{Some bounty hunters}
{10060580}{}{Some bounty hunters}
{10060590}{}{Some bounty hunters}
{10060600}{}{Some bounty hunters}
{10060610}{}{Some bounty hunters}
{10060620}{}{A band of ruffians led by a Morton Brother}
{10060630}{}{A press gang}
{10060640}{}{A herd of deathclaws}
{10060650}{}{A batch of fire geckos}
{10060660}{}{A slew of aliens}
{10060670}{}{Hubologists fighting mercenaries}
{10060680}{}{Hubologists fending off a press gang}
{10060690}{}{Hubologists}
{10060700}{}{The remains of a whale}
{10060710}{}{A giant stone head}
{10060720}{}{A crashed shuttle}
{10060730}{}{A Guardian Portal}
{10060740}{}{King Arthur's Knights}
{10060750}{}{A tin woodsman}
{10060760}{}{The Unwashed Villagers hunting a spammer}
{10060770}{}{The Cafe of Broken Dreams}
{10060780}{}{группу насекомых-мутантов}

# Encounter Table 62
{10061000}{}{Toxic waste dump}
{10061010}{}{A lone surviving dog}
{10061020}{}{A herd of brahmin}
{10061030}{}{A band of mercenaries}
{10061040}{}{Some bounty hunters}
{10061050}{}{Some bounty hunters}
{10061060}{}{Some bounty hunters}
{10061070}{}{Some bounty hunters}
{10061080}{}{Some bounty hunters}
{10061090}{}{Some bounty hunters}
{10061100}{}{Some bounty hunters}
{10061110}{}{Some bounty hunters}
{10061120}{}{A band of ruffians led by a Morton Brother}
{10061130}{}{A pack of deathclaws}
{10061140}{}{A pack of fire geckos}
{10061150}{}{A slew of aliens}
{10061160}{}{A caravan fending off mercenaries}
{10061170}{}{A caravan fending off mercenaries}
{10061180}{}{A caravan fending off fire geckos}
{10061190}{}{A caravan fending off aliens}
{10061200}{}{A caravan}
{10061210}{}{A caravan}
{10061220}{}{The remains of a whale}
{10061230}{}{A giant stone head}
{10061240}{}{A crashed shuttle}
{10061250}{}{A Guardian Portal}
{10061260}{}{King Arthur's Knights}
{10061270}{}{A tin woodsman}
{10061280}{}{The Unwashed Villagers hunting a spammer}
{10061290}{}{The Cafe of Broken Dreams}

# Encounter Table 63
{10061500}{}{A band of mercenaries}
{10061510}{}{A pack of deathclaws}
{10061520}{}{A pack of fire geckos}
{10061530}{}{A slew of aliens}
{10061540}{}{Some bounty hunters}
{10061550}{}{Some bounty hunters}
{10061560}{}{Some bounty hunters}
{10061570}{}{Some bounty hunters}
{10061580}{}{Some bounty hunters}
{10061590}{}{Some bounty hunters}
{10061600}{}{Some bounty hunters}
{10061610}{}{Some bounty hunters}
{10061620}{}{A band of ruffians led by a Morton Brother}
{10061630}{}{A caravan fending off mercenaries}
{10061640}{}{A caravan fending off mercenaries}
{10061650}{}{A caravan fending off fire geckos}
{10061660}{}{A caravan fending off aliens}
{10061670}{}{A caravan}
{10061680}{}{A caravan}

# Encounter Table 64
{10062000}{}{Toxic waste dump}
{10062010}{}{A lone surviving dog}
{10062020}{}{A herd of brahmin}
{10062030}{}{An Enclave patrol}
{10062040}{}{Some bounty hunters}
{10062050}{}{Some bounty hunters}
{10062060}{}{Some bounty hunters}
{10062070}{}{Some bounty hunters}
{10062080}{}{Some bounty hunters}
{10062090}{}{Some bounty hunters}
{10062100}{}{Some bounty hunters}
{10062110}{}{Some bounty hunters}
{10062120}{}{A band of ruffians led by a Morton Brother}
{10062130}{}{Remnants of the Master's army}
{10062140}{}{A pack of Deathclaws}
{10062150}{}{A swarm of mantis}
{10062160}{}{The remains of a whale}
{10062170}{}{A giant stone head}
{10062180}{}{A crashed shuttle}
{10062190}{}{A Guardian Portal}
{10062200}{}{King Arthur's Knights}
{10062210}{}{A tin woodsman}
{10062220}{}{The Unwashed Villagers hunting a spammer}
{10062230}{}{The Cafe of Broken Dreams}

# Encounter Table 65
{10062500}{}{An Enclave patrol}
{10062510}{}{Remnants of the Master's army}
{10062520}{}{A pack of Deathclaws}
{10062530}{}{A swarm of mantis}
{10062540}{}{Some bounty hunters}
{10062550}{}{Some bounty hunters}
{10062560}{}{Some bounty hunters}
{10062570}{}{Some bounty hunters}
{10062580}{}{Some bounty hunters}
{10062590}{}{Some bounty hunters}
{10062600}{}{Some bounty hunters}
{10062610}{}{Some bounty hunters}
{10062620}{}{A band of ruffians led by a Morton Brother}
{10062630}{}{A man guarding a bridge}
{10062640}{}{King Arthur's Knights fighting a rat}

# Encounter Table 66
{10063000}{}{Toxic waste dump}
{10063010}{}{A lone surviving dog}
{10063020}{}{A herd of brahmin}
{10063030}{}{A caravan fending off remnants of the Master's army}
{10063040}{}{Some bounty hunters}
{10063050}{}{Some bounty hunters}
{10063060}{}{Some bounty hunters}
{10063070}{}{Some bounty hunters}
{10063080}{}{Some bounty hunters}
{10063090}{}{Some bounty hunters}
{10063100}{}{Some bounty hunters}
{10063110}{}{Some bounty hunters}
{10063120}{}{A band of ruffians led by a Morton Brother}
{10063130}{}{A caravan fending off remnants of the Master's army}
{10063140}{}{A caravan fending off some deathclaws}
{10063150}{}{A caravan}
{10063160}{}{A caravan}
{10063170}{}{A caravan}
{10063180}{}{The remains of a whale}
{10063190}{}{A giant stone head}
{10063200}{}{A crashed shuttle}
{10063210}{}{A Guardian Portal}
{10063220}{}{King Arthur's Knights}
{10063230}{}{A tin woodsman}
{10063240}{}{The Unwashed Villagers hunting a spammer}
{10063250}{}{The Cafe of Broken Dreams}

# Encounter Table 67
{10063500}{}{A caravan fending off remnants of the Master's army}
{10063510}{}{A caravan fending off remnants of the Master's army}
{10063520}{}{A caravan fending off some deathclaws}
{10063530}{}{A caravan}
{10063540}{}{Some bounty hunters}
{10063550}{}{Some bounty hunters}
{10063560}{}{Some bounty hunters}
{10063570}{}{Some bounty hunters}
{10063580}{}{Some bounty hunters}
{10063590}{}{Some bounty hunters}
{10063600}{}{Some bounty hunters}
{10063610}{}{Some bounty hunters}
{10063620}{}{A band of ruffians led by a Morton Brother}
{10063630}{}{A caravan}
{10063640}{}{A caravan}
{10063650}{}{A man guarding a bridge}
{10063660}{}{King Arthur's Knights fighting a rat}
{10063670}{}{abandoned doughnut warehouse}

# Encounter Table 68
{10064000}{}{A pack of wolves}
{10064010}{}{A swarm of mantis}
{10064020}{}{A family of radscorpions}
{10064030}{}{Some bounty hunters}
{10064040}{}{Some bounty hunters}
{10064050}{}{Some bounty hunters}
{10064060}{}{Some bounty hunters}
{10064070}{}{Some bounty hunters}
{10064080}{}{Some bounty hunters}
{10064090}{}{Some bounty hunters}
{10064100}{}{Some bounty hunters}
{10064110}{}{A band of ruffians led by a Morton Brother}
{10064120}{}{A man guarding a bridge}
{10064130}{}{King Arthur's Knights fighting a rat}

# Encounter Table 69
{10064500}{}{Toxic waste dump}
{10064510}{}{A lone surviving dog}
{10064520}{}{A herd of brahmin}
{10064530}{}{A pack of wolves}
{10064540}{}{Some bounty hunters}
{10064550}{}{Some bounty hunters}
{10064560}{}{Some bounty hunters}
{10064570}{}{Some bounty hunters}
{10064580}{}{Some bounty hunters}
{10064590}{}{Some bounty hunters}
{10064600}{}{Some bounty hunters}
{10064610}{}{Some bounty hunters}
{10064620}{}{A band of ruffians led by a Morton Brother}
{10064630}{}{A swarm of mantis}
{10064640}{}{A family of radscorpions}
{10064650}{}{The remains of a whale}
{10064660}{}{A giant stone head}
{10064670}{}{A crashed shuttle}
{10064680}{}{A Guardian Portal}
{10064690}{}{King Arthur's Knights}
{10064700}{}{A tin woodsman}
{10064710}{}{The Unwashed Villagers hunting a spammer}
{10064720}{}{The Cafe of Broken Dreams}
{10064730}{}{strange abandoned house}
{10064740}{}{abandoned doughnut warehouse}

# Encounter Table 70
{10065000}{}{Toxic waste dump}
{10065010}{}{A lone surviving dog}
{10065020}{}{A herd of brahmin}
{10065030}{}{A band of marauders}
{10065040}{}{Some bounty hunters}
{10065050}{}{Some bounty hunters}
{10065060}{}{Some bounty hunters}
{10065070}{}{Some bounty hunters}
{10065080}{}{Some bounty hunters}
{10065090}{}{Some bounty hunters}
{10065100}{}{Some bounty hunters}
{10065110}{}{Some bounty hunters}
{10065120}{}{A band of ruffians led by a Morton Brother}
{10065130}{}{A pack of wolves}
{10065140}{}{A pack of radscorpions}
{10065150}{}{A caravan fending off marauders}
{10065160}{}{A caravan fending off marauders}
{10065170}{}{A caravan fending off wolves}
{10065180}{}{A caravan fending off radscorpions}
{10065190}{}{A caravan}
{10065200}{}{A caravan}
{10065210}{}{A caravan}
{10065220}{}{A caravan}
{10065230}{}{A traveler}
{10065240}{}{The remains of a whale}
{10065250}{}{A giant stone head}
{10065260}{}{A crashed shuttle}
{10065270}{}{A Guardian Portal}
{10065280}{}{King Arthur's Knights}
{10065290}{}{A tin woodsman}
{10065300}{}{The Unwashed Villagers hunting a spammer}
{10065310}{}{The Cafe of Broken Dreams}

# Encounter Table 71
{10065500}{}{A band of marauders}
{10065510}{}{A pack of wolves}
{10065520}{}{A pack of radscorpions}
{10065530}{}{A caravan fending off marauders}
{10065540}{}{Some bounty hunters}
{10065550}{}{Some bounty hunters}
{10065560}{}{Some bounty hunters}
{10065570}{}{Some bounty hunters}
{10065580}{}{Some bounty hunters}
{10065590}{}{Some bounty hunters}
{10065600}{}{Some bounty hunters}
{10065610}{}{Some bounty hunters}
{10065620}{}{A band of ruffians led by a Morton Brother}
{10065630}{}{A caravan fending off marauders}
{10065640}{}{A caravan fending off wolves}
{10065650}{}{A caravan fending off radscorpions}
{10065660}{}{A caravan}
{10065670}{}{A caravan}
{10065680}{}{A caravan}
{10065690}{}{A caravan}
{10065700}{}{A traveler}
{10065710}{}{A man guarding a bridge}
{10065720}{}{King Arthur's Knights fighting a rat}

# Encounter Table 72
{10066000}{}{A deteachment of the Master's armies}
{10066010}{}{A band of marauders}
{10066020}{}{Some Rangers fending off a squad of the Master's armies}
{10066030}{}{Some Rangers fighting some marauders}
{10066040}{}{Some bounty hunters}
{10066050}{}{Some bounty hunters}
{10066060}{}{Some bounty hunters}
{10066070}{}{Some bounty hunters}
{10066080}{}{Some bounty hunters}
{10066090}{}{Some bounty hunters}
{10066100}{}{Some bounty hunters}
{10066110}{}{Some bounty hunters}
{10066120}{}{A band of ruffians led by a Morton Brother}
{10066130}{}{Some farmers fending off parts of the Master's armies}
{10066140}{}{Some farmers fending off marauders}
{10066150}{}{A detachment of NCR Rangers}
{10066160}{}{Some farmers}
{10066170}{}{A man guarding a bridge}
{10066180}{}{King Arthur's Knights fighting a rat}
{10066190}{}{разномастную шайку бандитов}
{10066200}{}{несколько мятежных рейнджеров Уильяма Коди}

# Encounter Table 73
{10066500}{}{Toxic waste dump}
{10066510}{}{A lone surviving dog}
{10066520}{}{A herd of brahmin}
{10066530}{}{A detachment of the Master's armies}
{10066540}{}{Some bounty hunters}
{10066550}{}{Some bounty hunters}
{10066560}{}{Some bounty hunters}
{10066570}{}{Some bounty hunters}
{10066580}{}{Some bounty hunters}
{10066590}{}{Some bounty hunters}
{10066600}{}{Some bounty hunters}
{10066610}{}{Some bounty hunters}
{10066620}{}{A band of ruffians led by a Morton Brother}
{10066630}{}{A band of marauders}
{10066640}{}{Some Rangers fending off a squad of the Master's armies}
{10066650}{}{Some Rangers fighting some marauders}
{10066660}{}{Some farmers fending off parts of the Master's armies}
{10066670}{}{Some farmers fending off marauders}
{10066680}{}{A detachment of NCR Rangers}
{10066690}{}{Some farmers}
{10066700}{}{The remains of a whale}
{10066710}{}{A giant stone head}
{10066720}{}{A crashed shuttle}
{10066730}{}{A Guardian Portal}
{10066740}{}{King Arthur's Knights}
{10066750}{}{A tin woodsman}
{10066760}{}{The Unwashed Villagers hunting a spammer}
{10066770}{}{The Cafe of Broken Dreams}

# Encounter Table 74
{10067000}{}{Remnants of the Master's army fighting mutated molerats}
{10067010}{}{Remnants of the Master's armies}
{10067020}{}{A swarm of mantis}
{10067030}{}{A pack of mutated molerats}
{10067040}{}{Some bounty hunters}
{10067050}{}{Some bounty hunters}
{10067060}{}{Some bounty hunters}
{10067070}{}{Some bounty hunters}
{10067080}{}{Some bounty hunters}
{10067090}{}{Some bounty hunters}
{10067100}{}{Some bounty hunters}
{10067110}{}{Some bounty hunters}
{10067120}{}{A band of ruffians led by a Morton Brother}
{10067130}{}{A pack of radscorpions}
{10067140}{}{A man guarding a bridge}
{10067150}{}{King Arthur's Knights fighting a rat}

# Encounter Table 75
{10067500}{}{Toxic waste dump}
{10067510}{}{A lone surviving dog}
{10067520}{}{A herd of brahmin}
{10067530}{}{Remnants of the Master's army fighting mutated molerats}
{10067540}{}{Some bounty hunters}
{10067550}{}{Some bounty hunters}
{10067560}{}{Some bounty hunters}
{10067570}{}{Some bounty hunters}
{10067580}{}{Some bounty hunters}
{10067590}{}{Some bounty hunters}
{10067600}{}{Some bounty hunters}
{10067610}{}{Some bounty hunters}
{10067620}{}{A band of ruffians led by a Morton Brother}
{10067630}{}{Remnants of the Master's armies}
{10067640}{}{A swarm of mantis}
{10067650}{}{A pack of mutated molerats}
{10067660}{}{A pack of radscorpions}
{10067670}{}{The remains of a whale}
{10067680}{}{A giant stone head}
{10067690}{}{A crashed shuttle}
{10067700}{}{A Guardian Portal}
{10067710}{}{King Arthur's Knights}
{10067720}{}{A tin woodsman}
{10067730}{}{The Unwashed Villagers hunting a spammer}
{10067740}{}{The Cafe of Broken Dreams}
{10067750}{}{остатки каравана Даппо.}

# Encounter Table 76 (Ocean North)

{10068010}{}{мель}
{10068020}{}{несколько водяных крыс}
{10068030}{}{Isleок, кишаший крысами}
{10068040}{}{водяных крыс-переростков}
{10068050}{}{Isleок с гнездом мантисов}
{10068060}{}{дрейфующий плот}
{10068070}{}{торговца}

# Encounter Table 77 (Ocean South)

{10068200}{}{мель}
{10068210}{}{голодных и злых водяных крыс}
{10068220}{}{Isleок, кишаший крысами}
{10068230}{}{мутировавших водяных крыс}
{10068240}{}{Isleок с гнездом мантисов}
{10068250}{}{Isle с несколькими осами-переростками}
{10068260}{}{Isle с осиным гнездом}
{10068270}{}{дрейфующий плот}
{10068280}{}{торговца}

# Encounter Table 78 (Hell)

{10068400}{}{беглых каторжников}
{10068410}{}{патруль хабологов}
{10068420}{}{усиленный патруль хабологов}
{10068430}{}{патруль хабологов, воюющий с беглыми каторжниками}
{10068440}{}{беглых каторжников, устраивающих самосуд над хабологами}
{10068450}{}{нескольких оголодавших каторжников}
{10068460}{}{толпу беглых каторжников, потерявших разум}
{10068470}{}{стайку каких-то ящеров}
{10068480}{}{опасную волчью стаю}
{10068490}{}{мутировавших и отощавших кротов-гризли}
{10068500}{}{мутировавших кротов-гризли, дерущихся с ящерами}
{10068510}{}{рад-скорпионов, пытающихся сожрать кротов-гризли}
{10068520}{}{A man guarding a bridge}
{10068530}{}{King Arthur's Knights fighting a rat}
