# TODO:
# 1000 - 1530

# DONE:



#
# Created 21.04.08, Cvet
#
# В данном файле сценаристы могут создавать свои строки.
#

{1}{}{Включен nopvp режим.}
{2}{}{Отключен nopvp режим.}
# Плакаты
{5}{}{Вы вешаете плакат на стену.}
{6}{}{Вы не можете найти место, чтобы приклеить плакат.}

{10}{}{Test0}
{11}{}{Test1}
{12}{}{Test2}
{13}{}{Test3}

#
# Увеличение скила
#
{15}{}{Навык @lex skill@ увеличен на @lex value@ очков}

#
# Signal pistol.fos
#
{16}{}{Чтобы использовать сигнальный пистолет, возьмите его в руки.}
{17}{}{Сигнальная ракета открывает ваше положение на глобальной карте. В течение ближайших @lex minutes@ ждите гостей!}

#
# q_main_intro.fos
#

{20}{}{Вы прошли процедуру инициации.}

#
# jukebox.fos
#

{25}{}{Музыкальный автомат пока еще не готов к повторному использованию.}
{26}{}{Недостаточно денег. Цена прослушивания одной мелодии @lex price@$.}

#
# q_hunter.fos
#
{27}{}{Вы применили ультразвуковой гипнотизатор на мутировавшую крысу. Теперь ее можно положить себе в рюкзак. Если, конечно, она не очухается.}
{28}{}{В свистке закончились заряды. При последнем неаккуратном применении прибор был уничтожен.}
{29}{}{Крыса не реагирует на воздействие гипнотизатора. Попробуйте найти менее устойчивый экземпляр, где-нибудь в Пустоши.}

#
# rat_grenade.fos
#
{30}{}{Одна из ваших оглушенных крыс пришла в себя и удрала из рюкзака! Черт. Чем это так пахнет, и что это за жидкость?}
{30}{}{Одна из ваших оглушенных крыс пришла в себя и удрала из рюкзака!}
{30}{}{Одна из ваших оглушенных крыс пришла в себя и удрала из рюкзака! Вы упустили момент и больше ее не поймать.}
{31}{}{Одна оглушенная крыса, по всей видимости очнулась, и выскочила из рюкзака. Прикончите эту тварь немедленно.}
{31}{}{Одна оглушенная крыса, по всей видимости очнулась, и выскочила из рюкзака.}
{32}{}{Вы вкололи супертоксин оглушенной крысе. Теперь с каждым укусом она может отравить жертву.}
#
# q_hunter.fos
#
{33}{}{Неудачно выбрано место для использования приманки.}
{34}{}{Вы открываете крышку и у вас кружится голова от ужасной вони. Вы выливаете содержимое банки на свою одежду. Теперь остается только ждать, пока появятся крысы.}
{35}{}{Фу!!! Чем это от тебя воняет, @lex name@@??!!@@Ну и вонища!!!@@Проклятье! @lex name@!! Отойди от меня на другую сторону улицы. Или лучше вали куда подальше!@@Дерьмо! Кто-то навалил в штаны?@@Буэ... Меня сейчас вырвет! @lex name@, пошел вон!@@Что это за ужасный запах?!@@Что это за невыносимая вонь?@@*Зажимает ноздри пальцами*@@Уберите это дерьмо от меня!!}

#
# Nuka-Cola machine
#
{100}{}{You see a Nuka-Cola machine. You wonder if it still works.}
{101}{}{[thunk thunk chaching... sheeew]}
{102}{}{You get a not so fresh bottle of Nuka-Cola.}
{103}{}{Dooohhhh!}
{104}{}{You dodge the can of Nuka-Cola.}
{105}{}{@lex name @ skillfully dodges a can of Nuka-Cola.}
{106}{}{The machine seems to be out of stock.}


#
# Sandbag. Barricades stuff.
#
{200}{}{Мешок порвался у вас в руках - его нельзя класть в этом месте.}
{201}{}{В этом месте больше невозможно уложить ни одного мешка. }
{202}{}{Вы развязали мешок и высыпали песок из него на землю.}

#
# Extended craft.
#
{300}{}{Для производства требуется находиться рядом со cпециальным станком или верстаком.}
{301}{}{Станок или верстак в неработоспособном состоянии. Производство невозможно. Попробуйте позже.}
{302}{}{Станок или верстак в неработоспособном состоянии. Произведен максимум возможных предметов. Производство невозможно.}

#
# Generic messages
#

{500}{}{Gets @lex result@ on a die roll} # Dice
{510}{}{Yes} # Magic ball
{511}{}{No} # Magic ball
{520}{}{Preens @sex@|him||her|self} # Cosmetic
{530}{}{. Puffs on a cig .oO} # Cigarettes

#
# Guarded item
#

{540}{}{Отойди оттуда, @lex pname@}
{540}{}{Не вынуждай меня применить оружие, @lex pname@}
{540}{}{Эй, @lex pname@! Чем это ты занимаешься? Убирайся}
{540}{}{Не трогай это, @lex pname@}
{540}{}{@lex pname@! Немедленно перестань}

#
# Behemoth.fos
#
{600}{}{Цель подтверждена. Конечная цель маршрута @lex where@.}
{601}{}{Цель не подтверждена. Невозможно проложить маршрут по указанным координатам.}
{602}{}{Внимание. Последний приказ отменен.} 
{603}{}{Приказ выполнен. Цель @lex where@ достигнута. Мои координаты: @lex x@:@lex y@.}
{604}{}{Продолжаю движение к последней назначенной цели.}
{605}{}{Не могу выполнить команду. Сбой в управляющем контуре.}
{606}{}{Выполняю...}
{607}{}{Все задания выполнены. Ожидаю приказа.}
{608}{}{Внимание. В зоне патрулирования замечен @lex pname@.}
{609}{}{Цель @lex pname@ уничтожена.}
{610}{}{Сообщаю: подвергаюсь атаке от @lex pname@. Активирована защитная программа.}
{611}{}{Приступаю к патрулированию.}
{612}{}{Канал связи изменен.}
{613}{}{Машине не требуется ремонт.}
{614}{}{Вы частично устранили повреждения в системах жизнеобеспечения бегемота.}
{615}{}{Команда отменена. Не могу найти цель для атаки.}
{616}{}{Боевая программа активирована. Найдено целей... @lex targets@}

#
# Песня стража БС в яме
#
{630}{}{Стальное адское творенье,
Злой механический дракон}
{631}{}{Напал на мирное селенье и учиняет там погром!}
{632}{}{Огнём с небес людей сжигает,
Плюёт железом и свинцом}
{633}{}{И воздух гулом наполняет уничтожая всё кругом...}
{634}{}{Но Маркус,
Славный воин света,
Защитник выжженных земель,}
{635}{}{Он прекратит злодейство это, спасёт от гибели людей.}
{636}{}{И гнев во взгляде его ясном,
Глаза решимости полны,
А на его гербе прекрасном, три косозубых шестерни.}
{637}{}{Поднялись славные знамёна,
Запели звонкие рога}
{638}{}{И минизингер для синьора пропел хвалебные слова
Слуга копьё ему подносит и подаёт тяжелый щит
Молитву Маркус произносит, пусть его небо защитит.}
{639}{}{Он на коне помчался смело,
Как смерч по выжженной земле
И как звезда во тьме горела катушка тэсла на копье.}
{640}{}{Как гром слова его звучали:
"Презренный, выходи на бой! Я - паладин из Братства Стали, и я разделаюсь с тобой!"}
{641}{}{Они сошлись в бою суровом,
Вскипели небо и земля,
Сметало пламенным напором предметы с линии огня.}
{642}{}{Оплавлен щит огнём дракона,
И славный конь погиб в бою
И бронебойные патроны вгрызались в прочную броню.}
{643}{}{Дракон открыто потешался,
Пытался сбить героя с ног,
Но Маркус до него добрался метнув копьё в железный бок.}
{644}{}{И зверь взревел, копьём пронзённый, и стал искриться и стонать
Разрядом тока пораженный он начал высоту терять!}
{645}{}{Герой не зная состраданья,
Смотрел через огонь и дым
Как винтокрылое созданье упало оземь перед ним}
{646}{}{Он рано праздновал победу, коварный враг ещё дышал
И реактивную ракету навстречу Маркусу послал...}
{647}{}{[Booooooom! Badaboom!]}
{648}{}{Кровь по броне рекой струилась,
Он кинул прочь разбитый шлем}
{649}{}{Уже на минимум спустилась боеспособность всех систем}
{650}{}{Доспех почти что уничтожен,
Реактор начинает течь,
Но паладин достал из ножен тяжелый энтропийный меч.}
{651}{}{Индукционный накопитель оружье света пробудил,
И меч взревев как истребитель набрался запредельных сил.}
{652}{}{Герой прожог врага как масло, одним движением руки
Змей развалился безобразно на безобразные куски.}
{653}{}{В груди бойца зияли дыры
Он весь истерзан, обожжен,
Он потерял в бою все силы и был изрядно повреждён,}
{654}{}{Броню патроны изорвали, в них обеднённый был уран,
И, когда Маркуса подняли, в нем было три десятка ран...}
{655}{}{О рыцарь Маркус Непреклонный,
Оплакан сотней юных дев}
{656}{}{Лежит под древом погребённый
Молитвы светлые воспев}
{657}{}{И к тому древу, над могилой, прибит его походный щит
И дух его всё с той же силой те земли от врагов хранит!}
{658}{}{Ла-ла-ла-ла ла-ла-лэй ла-ла-ли-ла-лей!
Ла-ла-ла-ла ла-ла-лэй ла-ла-ли-ла-ла!}
{659}{}{Ла-ла-ла-ла ла-ла-лэй ла-ла-ли-ла-лей!
Ла-ла-ла-ла ла-ла-лэй ла-ла-ли-ла-ла!}

#
# Den store house
#

{1000}{}{Next!}
{1001}{}{Hey you! Do not approach!}
{1002}{}{Your time is coming to an end! If you don't hurry up I'll order the guard to kill you.}
{1003}{}{Guard}
{1004}{}{Эй, ты чего там делаешь?@@Сдохни, ворюга@@C ворами у меня разговор короткий@@Ребята, смотрите-ка, у нас воришка объявился@@Сейчас руки-то тебе поотрываю@@Вконец обнаглели. Посреди бела дня. В банке@@Очистим банки от ворья}

#
# Den entrance messages
#

{1050}{}{Вы испытываете странное чувство полной разрухи.}
{1051}{}{Где-то в глубине души вы очень рады, что покинули это место.}

#
# Den Bar Bekky boy
#

{1101}{}{Hmm...}
{1101}{}{Radio! Buy a radio!}
{1102}{}{La la la.}

#
# Quest warehouse
#

{1200}{}{Turrets on.}
{1201}{}{Turrets off.}
{1205}{}{Beep-Beep.}

#
# Den bank
#

{1300}{}{Get him, boys!}

#
# Den Trigger
#

{1400}{}{Something has crackled underfoot.}

#
# Manufacture, Alcohol
#

# Use
{1500}{}{The distillation device is out of order.}
{1501}{}{Firewood needed.}
{1502}{}{You watch as the firewood burns in the stove.}
{1503}{}{There is a fresh-brewed beer in a tank!}
{1504}{}{The tank with home-distilled alcohol is brimmed!}
# Use empty bottles
{1505}{}{You poured beer into the bottles.}
{1506}{}{You poured alcohol into the bottles.}
{1507}{}{You don't have enough bottles.}
# Use firewood
{1508}{}{This device is broken.}
{1509}{}{Need more firewood. What you have is probably not enough.}
{1510}{}{You don't know what ingredients to use and what the poportions are.}
{1511}{}{You prepared and poured in the stuff. You lit a fire in the stove. Distillation has begun.}
{1512}{}{You lit a fire in the stove and poured in the stuff. Home-distillated vodka is filling the tank.}
{1513}{}{There is enough wood there already.} 
{1514}{}{At first you have to pour out brewed beer.}
{1515}{}{At first you have to pour out distilled vodka.}
# To broke
{1516}{}{You have just broken the brewerage device.}
{1517}{}{You have just broken the distillating device.} 
{1518}{}{The boiler did not withstand the pressure and exploded!}
{1519}{}{Your eyes were splattered with boiling water.}
# Repair
{1520}{}{Looks like you need some details.}
{1521}{}{You need tools to fix this.}
{1522}{}{You have succesfully fixed the device.}
{1523}{}{You have failed at repairing and broken some details.}
# Science
{1524}{}{Device can be adjusted, but you need a wrench or something like that.}
{1525}{}{You broke your wrench. As well as the device.}
{1526}{}{During adjustment you dismounted half of the device. Now you need to assemble it back somehow.}
{1527}{}{You adjusted something carefully but it was useless.}
{1528}{}{You have adjusted the brewerage device. Now you'll need much less firewood.}
{1529}{}{You have adjusted the distillation device. Now you'll need much less firewood.}
{1530}{}{You have failed to adjust the device. Luckily, nothing got broken.}
# Scenery
{1560}{}{Some cereals lay here. They are cleansed and dried.}
{1561}{}{Fermentation of raw materials for alcohol takes place in these tanks.}

#
# Casino
#

{2000}{}{*Ring-a-ling*}
{2000}{}{*Zzzzzzz*}
{2000}{}{*Bing*}
{2000}{}{*Dingity-ding*}
{2000}{}{*Ding*}
{2000}{}{*Kaa-ching*}
{2001}{}{The machine is out of money.}

#
# Car, car.fos
#

{2100}{}{Number: @lex number@. Fuel: @lex fuel@/@lex fuel_tank@. Damage: @lex wear@%.}

#
# Getting firewood from tree (use axe on tree)
#

{2200}{}{This is suitable tree. You could cut fide wood... if your hands were okay.}
{2201}{}{You need to rest.}
{2202}{}{You hit your hand instead of tree!}
{2203}{}{You've cut some fire wood.}
{2204}{}{You've cut some fire wood, but can't carry it all.}
{2205}{}{You've cut some fire wood, but can't carry it at all.}

#
# Rangers
#

{2300}{}{Your target was liquidated by another ranger. Return to the outpost to get a new assignment.}

#
# Klamath, Bathhouse
#

{2400}{}{You didn't manage to figure out how to repair the pipe.}
{2401}{}{Farewell, babe.}
{2402}{}{Come back sometime.}
{2403}{}{I'll miss you.}
{2404}{}{You know where to find me.}

#
# Klamath, Grazing Area, Dogs. Using in klam_cowboy.fos
#

{2500}{}{Woooof! Woof! Woof!}
{2501}{}{Grrrrr!}
{2502}{}{Grr! Woof!}
{2503}{}{Woof!}
{2504}{}{Woof! Woof!}
{2505}{}{Woof! Woof! Wooof!}
{2506}{}{Wooooof!}
{2507}{}{*whines*}

#
# Primal tribe. Using in quest_trib_raiders_attack.fos
#
{2600}{}{Our tribe's Chief wants to talk to you.}
{2600}{}{Talk to Sulik.}
{2600}{}{The Chief is awaiting you.}
{2600}{}{Thanks for your help. Talk to the Chief.}
{2600}{}{The Chief wants to see you.}

#
# Slavers hunting. Using in q_slavers_hunt.fos
#
{2700}{}{Slavers base.}
{2701}{}{Вы сверяетесь с картой Элизы.\nСкорее всего работорговцев нужно искать между Кламатом и Ямой.}

#
# Dappo's lost caravan/ Using in q_dappo_lost_c_robot.fos
#
{2800}{}{Useless. I have find something else...}
{2801}{}{Hmmm... I can copy record from his camera.}
{2802}{}{Enemy spotted!}
{2803}{}{Enemy killed}
{2804}{}{Control point reached.}
{2805}{}{Moving next point...}
{2806}{}{От каравана Даппо мало что осталось. Пресловутым грузом оказался боевой робот в заводской упаковке.}
{2807}{}{Очевидно, что робот случайно активировался, выбрался на свободу и уничтожил караван. Даппо должен узнать, что произошло с его людьми. Робот не пожалел никого.}

#
# Alex holodisk. Using in q_ncr_alex_holo.fos
#
{2900}{}{Кажется, это то самое место, о котором говорится в голодиске. Осталось найти ящик.}
{2901}{}{Это место не похоже на то, что указано в голодиске.}

#
# NCR Michael. Using in ncr_michael.fos
#
{2910}{}{Посмотрим, что изменилось в Республике...}
{2911}{}{Бог ты мой, это же Майкл! Майкл, какими судьбами?}
{2912}{}{Отставить базар! Ему разрешено пройти.}

#
# NCR Westin. Using in ncr_westin.fos
#

{2930}{}{Тяжелый день...}
{2931}{}{Ну вот, опять нужно куда-то идти...}

#
# NCR Siege. Using in ncr_siege.fos
#

{2940}{}{Внимание! Говорит командир Рейнджеров НКР Элиза. Рейнджерам Республики нужна ваша помощь. Подступы к столице оккупированы бандами рейдеров и работорговцев. Мы платим за каждый вырезанный лагерь. Подробности у сержанта Кайла. Конец связи.}
{2941}{}{Внимание! Говорит командир Рейнджеров НКР Элиза. От имени штаба Армии НКР объявляю благодарность всем, оказавшим помощь. Рейдеры ликвидированы. Повторяю. Рейдеры уничтожены. Конец связи.}
{2942}{}{Это один из лагерей бандитов, угрожающих безопасности НКР.@@Вы нашли одно из мест, где закрепились рейдеры перед рещающей атакой на НКР.@@Здесь собрались самые отчаянные головорезы Пустоши. Они блокируют выходы из столицы Республики, убивают патрульных рейнджеров и грабят караваны НКР.}

#
# NCR Invasion. Using in ncr_invasion.fos
#
{2950}{}{Жалкие твари. Вы все подохнете как крысы@@Рейнджеры - пи*кашляет*!!!@@Сдохните, жалкие твари!@@НКР будет нашим! Мы наведем здесь порядок!@@Пацаны, смотрите, еще один. Вали его!@@Затопим эту дыру кровью рейнджеров!@@Вы все сдохнете!@@Убивайте всех. Не жалейте ни женщин ни детей.@@Республика падет!@@Мочи! Круши! Убей!@@Эй! НКР! Вы все должны сдохнуть!@@Ха-ха-ха!@@Умри!@@C дороги, мясо}
{2951}{}{Внимание! Всем! Всем! Говорит командир Рейнджеров НКР Элиза. На столицу Республики совершено нападение. Центр города пока в безопасности. Но на Базаре ситуация плачевная. Рейдеры закрепились на входе в город. Прорывайтесь в центр города для координации действий. Конец связи.}

#
# NCR Diplomatic mission. Using in ncr_shaiman.fos
#
{2960}{}{Вы не сумели взломать кейс c официальным ответом Братства Стали для генерала Армии НКР Шеймана.}
{2961}{}{Вы взломали замки кейса и прочитали письмо паладинов. Текст письма записан в вашем архиве.}

#
# Hell. Using in map_hell_level1.fos
#
{3000}{}{Как оказалось, трос не достает до земли, и вы, оценив расстояние до неё, решили прыгнуть вниз.}
{3001}{}{Вы не слишком удачно приземлились, сломав обе ноги.}
{3002}{}{Вы не слишком удачно приземлились, сломав левую ногу.}
{3003}{}{Вы не слишком удачно приземлились, сломав правую ногу.}
{3004}{}{Приземление, хоть и оказалось жестким, обошлось для вас лишь парой синяков и ушибов.}
{3005}{}{Вы не слишком удачно приземлились головой вниз.}
{3006}{}{A-A-A-A!!!}

#
# Hell. Using in hell_pipboys.fos
#
{3020}{}{Вы допущены до работы по сборке пипбоев. Когда решите выйти отсюда, привлеките внимание надзирателя.}
{3021}{}{You assembled a Pip-Boy. Total assembled: @lex pipnum@}
{3022}{}{You earned @lex sum@ dollars.}
{3023}{}{You earned @lex sum@ coins. Money were transferred to your replication account. Your balance is equal to: @lex bill@ dollars.}
{3024}{}{Congratulations! You have cleared your replication debt. You can now leave the special replication station.}
{3025}{}{У вас нет инструментов, необходимых для работы.}
{3026}{}{Вы исчерпали месячный лимит на оплату репликационных работ наличными.}

#
# Hell. Using in hell_mine_ore_reception.fos
#
{3030}{}{Терминал для сдачи добытой руды. Вы заглядываете в проем в стене, но ничего интересного там не видите. Оттуда лишь исходит странный гул, идущий откуда-то снизу.}

#
# Hell. Using in hell_mine_mining.fos
#
{3035}{}{Вы откололи кусок руды, который кажется более увесистым, чем остальные.@@Похоже, попалось то, что нужно.@@Вам попадается кусок породы с красивыми белыми прожилками.@@Кусок отличной породы глухо падает на пол.@@Вам попадается довольно неплохой кусок породы.}
{3036}{}{Вам попалась только пустая порода. Опять не везёт!@@Вы не добыли ничего полезного.@@Вы откалываете несколько крупных булыжников, но после осмотра понимаете, что это простой гранит.@@Вы усиленно колотите породу кувалдой, но ничего путного не попадается.}
{3037}{}{Вы откололи кусок руды, который кажется более увесистым, чем остальные.@@Похоже, попалось то, что нужно.@@Вам попадается кусок руды с золотой прожилкой.@@Отличный золотой самородок глухо падает на пол.@@Вам попадается довольно неплохой кусок породы.}


#
# Hell. Using in hell_lumbering.fos
#
{3040}{}{Вы допущены до работы на лесоповале. Когда решите выйти отсюда, обратитесь к солдату охраны.}
{3041}{}{Чтобы сдать дрова и получить награду, обратитесь к хабологам в соседнем здании.}

#
# Hell. Using in hell_level3.fos
#
{3045}{}{Вы не видите причин для того, чтобы лезть в эту странную дыру.}
{3046}{}{Вам не удаётся починить генератор. Попробуйте на свежую голову.}
{3047}{}{Покопавшись в генераторе, вы находите пару порваных проводов и быстро устраняете проблему.}

 #
 # Доска объявлений в НКР using in ncr_common.fos
 # ** КУПЛЮ ** 3100..3109
{3100}{}{СРОЧНО куплю Джет... и Баффаут. Доктор Трой.}
{3101}{}{Куплю патроны к солнечному скорчеру за любую цену. Избранный}
{3102}{}{Куплю силовую броню, 94 размера (Обращаться к Маркусу, шерифу Броукен Хиллз)}
{3103}{}{Куплю телевизоры, холодильники, радио-ДОРОГО. Вик}
{3104}{}{Куплю удобрение, желательно не вызывающее появление перхоти. Гарольд}
{3105}{}{Купим железную муху и железных людей. Дети Райт. Заплатит папа (наверное). }
{3106}{}{Куплю контактные линзы -3,5 на оба глаза, продам скобки для зубов, бу (обращаться в Главный Офис Ваут-Сити, спросить Первого Гражданина)}
{3107}{}{Купим унитазы!! Жители Модока. Дописано ножом: Чузен ты гад!!!}
{3108}{}{Купим резиновую куклу Чузена для отработки новых оружий. Гвардейцы АНКЛАВ}
{3109}{}{Куплю садовых вредитилей. Заколебал растительный юмор! Тифон}
# ** ИЩУ ** 3110..3116
{3110}{}{Пропала роба, сиреневая с желтыми полосами, просьба вернуть за вознаграждение. Хранитель моста.}
{3111}{}{Пропала кукла=85 см,с зевающим ртом,блондинка... нагая. Нашедшим просьба оставить у здания справа при входе в Модок.}
{3112}{}{Нужны брамины. Желательно взрывающиеся. Хранитель моста.}
{3113}{}{Ищем справедливость. Рэйнджеры
Ищем рэйнджеров. *Справедливость* [под перечеркнутой надписью виднеется : "Работорговцы"]}
{3114}{}{Ищем молодые таланты. Обращаться в офис в Нью-Рено *Golden Globes Porn*}
{3115}{}{Ищу свой глаз. *Капрал Диксон*}
{3116}{}{Нашедшему здоровенную металлическую задницу убедительная просиба не смеяться, никому не показывать и обязательно вернуть в ООО "Анклав"! Ф. Хорриган(верхняя часть)}
# ** ПРОДАМ ** 3117..3130
{3117}{}{Продаем нефть, оружие, лекарства, кроме того есть Гекк. Нефтяная вышка. Самовывоз. Просьба не взрывать. Ричардсон}
{3118}{}{Продам Скайнет, можно на запчасти. Chosen One.}
{3119}{}{Первое июля. 
Куплю энерго батареи для заправки тачки. Оплата по договорённости. Chosen One.

Тринадцатое июля. 
Продам трофеи. В том числе: гранаты, пистолеты, пулемёты, ружья, базуки, холодное оружие, броню, медикаменты, патроны (в том числе энеро батареи). Дёшево! (Хорошо по пустыне погулял! Блин, куда же всё это сбагрить?) Chosen One.}
{3120}{}{В связи с некоторыми геополитическими изменениями срочно продам благоустроенную нефтяную вышку с действующим атомным реактором. Президент Ричардсон.}
{3121}{}{Токсичные отходы самовывозом, по оптовым ценам. Смайли.}
{3122}{}{Продаю базу со всем ее содержимым и персоналом. Цена договорная. Для чузенов не продается. Сержант Гранит.}
{3123}{}{Продаётся Ядерный реактор (б/у) со всеми удобствами, каменная кладка, евроремонт 2143 год, цена договорная (радЭвей и Ремонтный бот прилаг.) Первый Гражданин Волт-сити. Обращаться с 8.00 до 18.00 при себе иметь Дневной пропуск}
{3124}{}{Продам гаусс-виндикатор, дорого, очень дорого. (Обращаться к Алгернону, Нью-Рено)}
{3125}{}{Продаём золотую щахту ванаминого в Рединнге. Ванаминого прилагаются. Коварный Мак Грю.}
{3126}{}{Продаю APA и лазерную винтовку. Просьба Избранному, Хорригану и Железному дровосеку не обращаться! Сержант Гранит}
{3127}{}{- Продам ГЕКК за ненадобностью оного. Избранный
- Господи, какой идиот!!! <Старейшина>}
{3128}{}{Продам часто линяющего геккона. ОЧЕНЬ дорого. Смайли.}
{3129}{}{Продам нефть. Президент.}
{3130}{}{Продаю металлолом. Дёшево. Самовывоз из Наварро.}
# ** РЕКЛАМА ** 3131..3138
{3131}{}{Спиртное крупным и мелким оптом. Семья Райт.}
{3132}{}{Гекогриль - живой грильбар в Вашем доме. Чудесное средство для быстрой зажарки любого блюда. Редкая природная разновидность геккона. Лучший рождественский подарок любимой тёще. Внимание - кормить в огнеупорном костюме. зоомагазин "старик Гекконыч"}
{3133}{}{Бесплатные споры по поводу того, кто есть Чузен. Говорящая Голова.
  <внизу начерчено> "Прием краденых камней у Головы" Чузен.}
{3134}{}{Вылечим от наркомании за 10 дней. Майрон.}
{3135}{}{У вас есть деньги? ЭТО ПОПРАВИМО! Рейдеры.}
{3136}{}{Экспресс-загар дешево, обращаться на АЭС Гекко.}
{3137}{}{Собери пять голов с татуировкой, и получи значок рейнжера. Рейнджеры НКР
 дописано: Собери пять значков рейнжеров, и получи тату на лоб. Работорговцы}
{3138}{}{Экономическое чудо. Высокоприбыльный бизнес. Новая консервная фабрика Чипа. Консервы, тушенка, печенка. Желающим заработать - просьба проходить на задний двор (в подвал, без оружия). Мутантам - специальное предложение.}
# ** УСЛУГИ ** 3139..3146
{3139}{}{Сеансы общения с духами предков. Спросить Сулика.
Общение с духами,но дешевле чем у Сулика. Хакуин.}
{3140}{}{Сеансы гаусс-терапии на дому. Ваши патроны, мой гаусс. Спросить Кейсиди.}
{3141}{}{Увлекательный морской круиз с феерическим ночным шоу! ООО "Посейдон-Трэвел"}
{3142}{}{УСЛУГИ МАГА: Снимаю порчу ломаю крушу краду взламываю. Обращаться в Гильдию Работорговцев. Кто угодно из гильдии.}
{3143}{}{Приглашаю крутых засранцев в тур по Пустоши с попутным лечением завышенной самооценки. Самый крутой засранец.}
{3144}{}{Очищу Ваш город от всего живого. *Избранный*}
{3145}{}{Пасу браминов, есть собака, опыт. Избранный}
{3146}{}{Соберу из мусора, карманной корпии, зажигалок, цветков, шприцов, ожерелий - пылесосы, тракторы, экскаваторы, рекативные самолеты, вечные двигатели первого и второго рода. Обращаться к Ретчу, НКР.}
# ** АКЦИИ ** 3147..3154
{3147}{}{Принимаем работорговцев оптом и в розницу за хорошее вознаграждение. Можно только головы. Рейнджеры НКР.}
{3148}{}{*Крупными буквами* Спешите! Спешите! Только у нас и только для вас! Аттракцион "Заржавевший анклавовец"! Разрешается стучать по лбу и пинать по заднице! Где-то в пустыне, сами найдете... Избранный.}
{3149}{}{ООО "Анклав" проводит день открытых дверей! В программе: весёлая беготня по нефтяной вышке, арм-рэслинг с Фрэнки, приседания в энергоброне, а так же экскурсия "Увидеть бомбу и умереть"! В конце программы весёлые солдаты пинками проводят вас до выхода с криками "Эвакуация!!!" ООО "Анклав"
P.S. Чузенов просьба не беспокоить.}
{3150}{}{Приглашаем на новую театральную постановку "Чужие-7"! Обращаться в Реддинг, шахту Ванаминго!}
{3151}{}{Собери 10 голов мертвяков и получи 50% скидку на гражданство Города! Линетт.}
{3152}{}{У Вас нет денег, но есть нелюбимые родственники??? Мы Вам поможем!!! За очень хорошую плату Вы можете оставить у Нас своих родственников на постоянное проживание!!! Обращаться в Дэн, Восточный район, в Гильдию Работорговцев. Метцгер.}
{3153}{}{Желающим сняться в качестве жертв в фильме "чужие" просьба почаще навещать шахту ванаминго.} 
{3154}{}{Всем пацанам из охраны Волт-Сити!!! Пэйнтболл и халявное пиво! Сбор за оградой, сами знаете где. Гражданин-сержант СТАРК}
# ** РАЗНОЕ ** 3155..3175
{3155}{}{Меняю: копье с заточенным наконечником (в неплохом состоянии) на винтовку Гауса с подробной инструкцией по эксплуатации, гарантийным талоном и прочей документацией, если таковая имеется. БЕЗ ДОПЛАТЫ. Chosen One.}
{3156}{}{Меняю двадцать шкурок золотого Гекко на обрез. Чуз.}
{3157}{}{Меняю турбоплазменную винтовку с возможностью автоматического огня на гранату Антиоха. Ну Чузен, теперь посмотрим кто из нас настоящий манчкин! Фрэнки.}
{3158}{}{Меняем чертежи ключей от вертиберда на чертежи самого вертиберда. (Обращаться в бункер Братства Стали в Сан-Франциско)}
{3159}{}{Познакомлюсь с девушкой, некурящей, непьющей, дисциплинированной, владеющей бензиновым автомобилем для извлечения взаимной выгоды. Капитан Танкера "Посейдон Ойл" Вальдез.}
{3160}{}{Розыск! Имя: Рэндэл. Кличка: Железный дровосек. Место службы: Анклав. Пропал на миссии по уничтожению Избранного. Подпись: Сержант.}
{3161}{}{Много сложной, грязной и плохооплачиваемой работы, обращаться к шрифу Реддинга.}
{3162}{}{Дайте денег, или я сейчас выброшусь! Кит.}
{3163}{}{Бюрократы Города-Уежища - №%!$ $&*$^!& (Подпись неразборчива)}
{3164}{}{Форматируем Императора. Дли Ши - бесплатно! Остальным - за $1.95}
{3165}{}{Объявление. Открылся бар "Танцующий мутант". В программе: Стриптиз в исполнении звезды пустошей мутантихи Изольды (сценический псевдоним). Живая музыка (Рок-группа "Гейгер", вокалист - Гарольд).}
{3166}{}{Поздравляю всех анклавовцев и Френка с Днём Защитника Отечества. Президент.}
{3167}{}{Обаятельная, 34 года, ищет мужчину для совместного времяпрепровождения. Интим предлагать(но втайне от мужа). Мисс Бишоп.}
{3168}{}{Познакомлюсь с порядочным мужчиной, обеспеченным с чувством юмора. Избранных просьба не беспокоить. Линнет}
{3169}{}{27 июля 2247 года ушёл из Арройо на поиски ГЭККа и не вернулся Избранный. На EMS не отвечает. Нашедшму просьба обратиться на вышку "Посейдон", третий уровень, первая камера, а также напомнить Избранному, что до gameover'а у него остался один месяц манчкинства. Старейшина, 27 июня 2260.}
{3170}{}{Нубы должны страдать! Гопы}
{3171}{}{Гопы должны страдать! Нубы}
{3172}{}{Вы, РЕАЛЬНО, ничего не понимаете в Сути Пустоши. Хабологи}
{3173}{}{!!!АТОМ ВСЕСИЛЬНО ИСКРИТ!!!!}
{3174}{}{Продам 50 томми-ганов или обменяю их на 50 патронов к .223 пистолету. Неизвестный.}
{3175}{}{Ок. Krizalis}

#
# ncr Spy mission quest. Using in q_spy_mission.fos
#

{3180}{}{МакКлюр? Вы и сегодня умудрились опоздать.}
{3181}{}{Прошу прощения, Первый Гражданин, слишком много дел. Подобное не повторится.}
{3182}{}{Вы говорите это всегда. Я бы давно от вас избавилась, но, увы, сейчас это невозможно.}
{3183}{}{Не понимаю, о чем вы, Первый Гражданин.}
{3184}{}{МакКлюр, давайте откажемся от лицемерия, когда мы наедине. Мы оба прекрасно понимаем, о чем идет речь.}
{3185}{}{Хорошо, Линетт. Я всего лишь обязан выполнить свой долг. Надеюсь, в скором будущем положение дел изменится.}
{3186}{}{А я надеюсь, что статус-кво сохранится. Ваша самоуверенность вас подведет, и вы совершите ошибку. А я ее использую.}
{3187}{}{Хотелось бы верить, что у вас не будет такого шанса. Отставим наши словесные баталии и вернемся к работе.}
{3188}{}{Слушаю вас, советник.}
{3189}{}{Настроения в Городе не изменились. За последнюю неделю не зафиксировано значимых происшествий и преступлений.}
{3190}{}{Да сам факт вашего существования, советник, является преступлением!}
{3191}{}{Первый Гражданин, мне уйти?}
{3192}{}{Ладно, забудем, мне нельзя поддаваться эмоциям. Продолжайте.}
{3193}{}{В Реддинге зафиксировано несколько случаев нападения на стражей порядка. Недовольство коренных жителей растет.}
{3194}{}{Добыча?}
{3195}{}{Темпы золотодобычи упали за последнюю неделю. Нам нужны еще шахтеры. Возможно, нам следует отправить часть слуг в шахты Реддинга.}
{3196}{}{Чепуха. Усильте подразделения регуляторов. Чтобы никто не мог отлынивать от работы. Что с НКР?}
{3197}{}{Военное положение все еще в силе. На столицу Республики было совершено несколько нападений рейдеров, они отбиты армией НКР.}
{3198}{}{Отношения армии и Братства Стали остались без изменений?}
{3199}{}{По информации из достоверных источников, Шейман пытается наладить контакт с паладинами. Но пока безрезультатно.}
{3200}{}{Что-нибудь еще?}
{3201}{}{Нет, на сегодня это все.}
{3202}{}{Отвратительно. Хотя, чего я еще могла бы ожидать от предателя?}
{3203}{}{Предлагаю обойтись без навешивания ярлыков. И вообще отказаться от поступков, о которых можно пожалеть в будущем...}
{3204}{}{Это угроза, МакКлюр? Не смешите меня. Вы свободны.}
{3205}{}{Всего доброго, Первый Гражданин.}

#
#Радиопереговоры после выполнения квеста "На связи". redding_common.fos
#
{3300}{}{Док Джонсон на связи. Вызываю своих…}
{3301}{}{Свой своему поневоле брат. Привет, Безболезненный, давно не виделись.}
{3302}{}{Это ты, что ли, Трой, клизма подземная? Сидишь там в своем убежище, как Том Круз какой-то.}
{3303}{}{Ты кого клизмой назвал. Я между прочим, антиджет изобрел, а ты только и умеешь, что антракоз своим шахтерам лечить.}
{3304}{}{Ой, посмотрите, изобрел он. А производство наладить не смог, мне пришлось заниматься…}
{3305}{}{Ну началось… Эти двое как сойдутся…}
{3306}{}{А, привет Холидей. Как сам-то?}
{3307}{}{Да скриплю потихоньку. Мутантов и гулей полечиваю. Что –то Юбилея  я не слышу. Здесь он? Холидей вызывает Юбилей!}
{3308}{}{Да здесь я, здесь. Привет всем.}
{3309}{}{И тебе поздорову. Мужики, а помните, как наш Юбилей, будучи в ординатуре, у мужика одного аппендикс слева искал?  Чуть не по локоть влез, а найти не может…}
{3310}{}{Ладно, ладно. Это всего раз было. И потом, я ж тогда пьяный был. Не считается.}
{3311}{}{Да уж конечно, не считается. Местечко-то ты себе нашел получше всех нас, сидишь там в НКР, вкушаешь прелести демократии…}
{3312}{}{Вам бы такие прелести! Тут было дело, давненько правда, меня Избранный чуть наизнанку не вывернул, сказал, что я у какого-то шахтера спер карту Убежища 13. Еле как отмазался. До сих пор вздрагиваю, как вспомню.}
{3313}{}{Так тебе, буржую. Хе-хе…}
{3314}{}{Ладно, ладно. Слушай, Джонсон, у тебя там по слухам, эпидемия сифилиса была? Как разобрался?}
{3315}{}{Да пришлось изрядно поебаться. На первичные симптомы внимания никто из них не обратил, а когда обратили, уж зараженных выше крыши было. Ну, и ходил я везде, как дурак, опросы проводил, разбирался, кто в кого совал, надоело. В оконцовке сделал сводную таблицу и вычислил источник. Тьху на тебя блин. Напомнил.}
{3316}{}{Да ладно, справился  же. Молодец.}
{3317}{}{Присоединяюсь. Молодец, Джонсон.}
{3318}{}{Ооо! Доктор Фунг, моё почтение!}
{3319}{}{Приветствую, учитель!}
{3320}{}{Рад вас слышать.}
{3321}{}{Здравствуйте, мальчики. Я тоже рад вас всех слышать. Также рад, что у нас есть теперь всегда возможность поговорить и спросить совета друг у друга. Вы все стали неплохими специалистами.}
{3322}{}{Спасибо, учитель…}
{3323}{}{Не перебивай старших! Я не закончил. Полагаю, вам всем следует задуматься об учениках. Знание не должно быть потеряно. Ну, Трой об этом уже позаботился, я в курсе. А остальные – айяяй.}
{3324}{}{Хорошо, учитель.}
{3325}{}{Обязательно.}
{3326}{}{Мдя. А мне что-то и в ум не приходило…}
{3327}{}{Так, мальчики, я извиняюсь и оставляю вас. Ко мне тут принесли китайца, покусанного акулами, нужно срочно им заняться. Свяжемся на той неделе, мне есть о чём с вами поговорить.}
{3328}{}{Да, учитель.}
{3329}{}{До связи.}
{3330}{}{Здоровья вам.}
{3331}{}{Гм. Ну вот. Мужики, а знаете что? Предлагаю нам всем немедленно выпить! Как относитесь?}
{3332}{}{Ну и вопрос.}
{3333}{}{Поддерживаю.}
{3334}{}{Так. А у меня кроме спирта ничего нет, давайте я в бар сгоняю. Ну подождите 20 минут, будьте вы людьми.}
{3335}{}{Да хорошо, хорошо. Давай через полчаса снова все на связь. И чтоб уже без отговорок. Кстати, на всякий случай – резервная волна, эээ…}
{3336}{}{Давай год, когда пенициллин придумали.}
{3337}{}{Годится.}
{3338}{}{Всё, до связи, мужики, я побежал.}
{3339}{}{Угу.}
{3340}{}{Давай.}
###Если в разговор пытается влезть игрок
{3341}{}{Посторонние на канале! Все на другой канал!}
{3342}{}{Давай год, когда Пастер пастеризацию придумал.}
{3343}{}{Принято.}

#
# ncr westin vs bishop quest chain. Using in ncr_smit.fos
#
# диалог на воротах города между смитом и охранником
{3400}{}{Здравствуйте. Предъявите пропуск.}
{3401}{}{Привествую, офицер. Увы, у меня нет пропуска.}
{3402}{}{В таком случае, сообщите о цели визита в НКР и представьтесь.}
{3403}{}{Меня зовут Смит. Собирался заглянуть в местный бар.}
{3404}{}{Cмит, для того, чтобы пройти в НКР, вам потребуется оформить пропуск у капитана охраны.}
{3405}{}{Где я могу найти капитана охраны?}
{3406}{}{Капитана вы найдете на таможне. Удачного дня.}
{3407}{}{Всего доброго, офицер.}
{3408}{}{Надо же! Мне крупно повезло, на входе нет охраны!}
# переговоры Смита и Бишопа по радио
{3420}{}{[Говорит в рацию] Прием. Проверка связи.}
{3421}{}{Прием. Проверка связи.}
{3422}{}{..шш..}

{3423}{}{[Говорит в рацию] Ворон, Ворон. Я Брамин, прием.}
{3424}{}{Ворон, Ворон. Я Брамин, прием.}
{3425}{}{..шш..}

{3426}{}{[Говорит в рацию] Ворон, я Брамин. Брамин вызывает Ворона.}
{3427}{}{Ворон, я Брамин. Брамин вызывает Ворона}
{3428}{}{Пошел на х..}

{3429}{}{[Говорит в рацию] Ворон, повторите, не понял, прием.}
{3430}{}{Ворон, повторите, не понял, прием.}
{3431}{}{ Пошел на х.. ..шш.. брамин ..шш.. ..ный!!!!}

{3432}{}{[Говорит в рацию] Ворон, ответьте. Почему ангелы летают?}
{3433}{}{Ворон, ответьте. Почему ангелы летают?}
{3434}{}{Ты что, совсем тупой? ..шш.. Пошел ты в ..шш.. кретин! Я тебя.. ..шш... и твою мать.. ..шш.. и твоего отца.. ..шш.. Ты меня понял, жо.. ..шш. .шами?! Прием?!}

{3435}{}{Похоже, я выбрал не ту волну. [Настраивает рацию и повторяет] Ворон, прием, я Брамин.}
{3436}{}{Ворон, прием, я Брамин.}
{3437}{}{ Слышу тебя, Брамин. Я Ворон. Прием. }

{3438}{}{Ну вот, слава богу. [Говорит в рацию] Ворон, почему ангелы летают? }
{3439}{}{Ворон, почему ангелы летают?}
{3440}{}{Смит, браминья твоя башка. Как ты задрал со своей конспирацией, придурок. Как понял меня, прием?}

{3441}{}{[Про себя] Отзыв правильный. Отлично. [В рацию] Прошу прощения, мистер Бишоп.}
{3442}{}{Прошу прощения, мистер Бишоп.}
{3443}{}{Как поживает Вейстин? Какие новости?}

{3444}{}{[В рацию] Я в НКР, мистер Бишоп. Вейстин на прицеле. В ближайшие дни приступаю к нейтрализации советника.}
{3445}{}{Я в НКР, мистер Бишоп. Вейстин на прицеле. В ближайшие дни приступаю к нейтрализации советника.}
{3446}{}{Не тяни, Смит. Иначе я буду вынужден найти кого-то другого для этой работы. А тобой займутся мои люди.}

{3447}{}{[В рацию] Нет проблем, мистер Бишоп. Можете не беспокоиться на счет советника.}
{3448}{}{Нет проблем, мистер Бишоп. Можете не беспокоиться на счет советника.}
{3449}{}{ Я тебя предупредил. Конец связи. }

{3450}{}{[В рацию] Конец связи.}
{3451}{}{Конец связи.}
#Если грант мертв или нет в радиусе поиска
{3455}{}{Ха. Грант куда-то отлучился. То, что мне нужно.}
# Грант заметил Смита
{3456}{}{Эй! Кто здесь! Выйди на свет, иначе стреляю!}
{3457}{}{Что случилось? Я не делаю ничего противозаконного.}
{3458}{}{Здесь находиться запрещено. Проваливай, пока цел.}
{3459}{}{Уже ухожу, прошу прощения.}
#Диалог Смита и Вейстина
{3460}{}{Здравствуйте, мистер Вейстин.}
{3461}{}{Что... Кто вы? Как вы оказались в моем доме?! Охрана! На помощь!}
{3462}{}{Никто не придет, мистер Вейстин. Я здесь, чтобы передать вам привет от господина Бишопа.}
{3463}{}{Бишоп? Человек Бишопа?! Вы пришли меня убить?!}
{3464}{}{Удивительная проницательность. Прощайте, мистер Вейстин.}
{3465}{}{Помогите! Убивают!}
#Вейстина нет на месте или он убит
{3466}{}{Черт подери! Вейстина нет на месте! Проклятье.}

#Ill brahmin felix quest. Using in ncr_common.fos
{3470}{}{Вы на самом деле готовы проверить, чем отравился брамин, используя резиновые перчатки и вантус?}
{3471}{}{Да, с богом!}
{3472}{}{НИ ЗА ЧТО!!!}
{3473}{}{Ух, дрянь какая! После нескольких унизительных мгновений вы извлекаете наружу причину "отравления" брамина.}
{3474}{}{Вы нашли @lex item_name@. И как только он мог ЭТО сожрать...}
{3475}{}{Вы кладете непонятный цветок Феликса под морду брамина. Он с интересом на него смотрит, и с громким чавканьем съедает. Смотрит на вас с надеждой: а еще есть?}

# Quest "Arroyo defence". Using in scripts arroyo_mynoc_defence.fos & map_arroyo_rayders_camp.fos
{3480}{}{Вы получили @lex exp@ опыта.}
{3481}{}{Вы отстали от группы.}
{3482}{}{Вы обнаружили рейдеров нападающих на караваны Арройо.}
{3483}{}{Вы не успели расправиться с рейдерами, они сбежали.}

#caravan quest.Using in caravan.fos
{3500}{}{Немедленно отойди от груза}
{3500}{}{Эй! А ну-ка, отвали от повозок}
{3500}{}{Не вздумай приближаться к грузу}
{3500}{}{Убирайся, не смей к ним прикасаться}
{3500}{}{Отойди. Быстро}
{3500}{}{Не трогай}


# Квест "Правосудие Хаба". sf_common.fos
{3510}{}{Перестань! Пожалуйста, перестань!}
{3510}{}{За что... }
{3510}{}{Мы никогда никому не причинили вреда! За что нам это все?}
{3510}{}{Не убивай, будь человеком}
{3510}{}{НЕЕЕЕТ!}

#Изучение рецепта хитиновой брони.
{3515}{}{Вы не сумели запомнить содержимое рецепта. Вот если бы вы были немного опытнее...}
{3516}{}{Вы выучили рецепт усовершенствования кожаной брони с помощью хитиновых панцирей гигантских жуков.}

#hub holodisk quest. Using in loc_tech_bunker.fos
{3600}{}{Вы не можете иметь больше таких предметов.}


# Resources system
{3700}{}{Здесь больше делать нечего}
{3701}{}{Вы не можете взять больше}
{3702}{}{Вы добыли : @lex itemname@ - @lex count@@lex type@}
{3703}{}{Вы добыли : @lex itemname@}
{3704}{}{Вы добыли немного дров}
{3705}{}{шт}
{3706}{}{кг}
{3707}{}{В этом холодильнике не осталось ни капли аммиака.}
{3708}{}{Вы набрали почти полную бутылку аммиака. Плотно заверните крышку.}

# Game Event Den Racing
{3800}{}{Да не будет сегодня не фига. Расходитесь.}
{3800}{}{Да сколько можно  ждать!}
{3800}{}{Не, ну я не понял, где шоу?}
{3800}{}{Хлеба и Зрелищ!}
{3800}{}{Жил на свете мальчик Билли. Дети Билли не любилллли.}
{3801}{}{Ну ты, не толкайся.}
{3801}{}{Да начинай уже!!!}
{3802}{}{Где сиськи, Билли!!!} 
{3802}{}{Билл, ты испытываешь наше терпение.}
{3803}{}{А пиво когда привезут?}
{3804}{}{Нам тут до ночи торчать?}
{3804}{}{Билли, не спи! Начинай уже!}
{3805}{}{Але, на! Я сейчас засну от скуки.}
{3805}{}{Вот идиот! И эти двое – чисто брамины в костюмах!} 
{3806}{}{А что мы тут стоим-то?}
{3806}{}{Поехали! Даешь гонки!}
{3807}{}{Я, кажется, утюг забыла выключить!} 
{3808}{}{Джон, не ковыряй в носу, тут люди!}

{3809}{}{Итак!!! Почтеннейшая публика}
{3810}{}{Дамы и господа}
{3811}{}{Я Билли Гейц!!! и!!! я объявляю начало}
{3812}{}{Всесезонных!! Смертельных}
{3813}{}{Гонок Западного побережья}
{3814}{}{Гранд-Пасифик-Американ}
{3815}{}{Напоминаю!!! Что всё хорошее!!! что здесь происходит!!! мы имеем благодаря!!! Семье Бишопов из Нью-Рено}
{3816}{}{Сегодня!!! Смелые сыны и дочери пустоши сойдутся в борьбе!! за главный приз гонок!! Силовую броню!!! Поприветствуем их}
{3817}{}{Внимание участников !!! Как только вы покинете город!! На ваш пипбой вы получите информацию!!! по расположению первого чекпойнта!!! По его достижению получите расположение следующего!!! И так далее!!! Если вы меня не поняли – значит зря сюда прибыли}
{3818}{}{А теперь!!!! Ти ши наааа!!! По моей команде!!! При счете ТРИ начнется гонка!!!}
{3819}{}{Один!!! }
{3820}{}{Два!!! }
{3821}{}{Три!!!}

{3822}{}{Не тяни, придурок!}
{3823}{}{Чо он сказал, я не услышал!}
{3824}{}{Да, да, задолбал уже}
{3825}{}{Ой, уже началось?!!}
{3826}{}{Где сиськи, Билли!!! Урааа!!!}
{3827}{}{Ура!!}

{3828}{}{Чтоб они сдохли!} 
{3829}{}{Да чо он шепчет, хер поймешь!} 
{3830}{}{Бишопы рулят!!!}
{3831}{}{А дочка у них та ещё блядина!!!} 
{3832}{}{Я возьму отбивную с луком!!!}
{3833}{}{Где сиськи, Билли!!!}

{3834}{}{Да она сломанная, поди!!!} 
{3835}{}{Ура!!!}
{3836}{}{Давай, мужики!!!}  
{3837}{}{Вот так и разводят нас как лохов!!!} 
{3838}{}{Чего он говорит, я не понял!}
{3839}{}{Где сиськи, Билли!!!}

{3840}{}{Слышь, ты что-нибудь понял?!!!} 
{3841}{}{Ура!!!}
{3842}{}{Нарезааай!!!}
{3843}{}{У меня в том году брамин от этого сдох!!!} 
{3844}{}{Это он с кем разговаривает?!}
{3845}{}{Где сиськи, Билли!!!}

{3846}{}{Я опять не услышал!!!} 
{3847}{}{Ура!!!}
{3848}{}{Газ в пол!!!} 
{3849}{}{Как насчет пива?!!} 
{3850}{}{А мой-то дурак на рыбалку пошел!!!} 
{3851}{}{Вперёёёд!!!}
{3852}{}{Где сиськи, Билли!!!}

{3853}{}{Внимание! Всем, кого это касается! Всем желающим принять участие  - записываться заранее! Заявки принимаются  на заправке в Дене! Не пропусти Всесезонные Смертельные Гонки Западного побережья Гранд-Пасифик-Американ! Гонки на приз семьи Бишопов  состоятся:}
{3854}{}{Ура.}
{3855}{}{Девочки, а он ничего.}

{3856}{}{В пипбой загружены координаты чепоинта №@lex num@.}

# Magic Ball mesages
# > 0 luck = 3899..3908
# > 3 luck = 3899..3919
# > 5 luck = 3899..3919
# > 6 luck = 3899..3932
# > 7 luck = 3899..3935
# > 8 luck = 3899..3941
# > 9 luck = 3899..3943
{3899}{}{Это что еще за идиотский вопрос?}
{3900}{}{Перспективы хорошие.}
{3901}{}{Перспективы не слишком хорошие.}
{3902}{}{Мой ответ - нет.}
{3903}{}{Не рассчитывайте на это.}
{3904}{}{Можете рассчитывать на это.}
{3905}{}{Спросите потом.}
{3906}{}{Скорее всего.}
{3907}{}{Сейчас невозможно сказать заранее.}
{3908}{}{Да.}
{3909}{}{Да. Несомненно.}
{3910}{}{Лучше пока вам не говорить.}
{3911}{}{Вне всякого сомнения.}
{3912}{}{Очень сомнительно.}
{3913}{}{Определенно так.}
{3914}{}{Сосредоточьтесь и спросите снова.}
{3915}{}{Знаки указывают, что да.}
{3916}{}{Мои источники говорят, что нет.}
{3917}{}{Несомненно.}
{3918}{}{Ответ неясен, попробуйте еще раз.}
{3919}{}{Как мне кажется, да.}
{3920}{}{Хватит меня так трясти. Больно же!}
{3921}{}{У вас сильная правая рука.}
{3922}{}{Перед тем как снова меня трясти, прошу вас, вытрите руки.}
{3923}{}{Временно не обслуживается.}
{3924}{}{Закрыто по приказу Совета РПГ.}
{3925}{}{Будешь и дальше меня трясти, будут неприятности.}
{3926}{}{Мне плохо.}
{3927}{}{Меня тошнит.}
{3928}{}{У тебя руки теплые.}
{3929}{}{Нет.}
{3930}{}{Ваш показатель - 23 из 100. У вас еще масса способов уйти. И не спрашивайте, что это значит.}
{3931}{}{Если верить моему внутреннему чутью, у вас все получится. А если не верить - наоборот. Сожалею.}
{3932}{}{Если вы встретите робота-стража, уничтожившего караван, не забудьте считать информацию с его видеокамеры.}
{3933}{}{На Атолле есть парень, который продает ГЕКК. Если, конечно, его еще никто не купил.}
{3934}{}{Попробуйте проследить, куда нищенка из НКР прячет деньги, нажитые непосильным попрошайничеством.}
{3935}{}{Посылку паладинов Братства можно взломать. Точно.}
{3936}{}{Хватит меня так трясти.}
{3937}{}{Ваша УДАЧА очень высока. Трясите меня, что-нибудь полезное расскажу!}
{3938}{}{Среди объявлений на доске НКР вы не найдете ничего полезного.}
{3939}{}{Алекс в НКР может подарить очень интересный голодиск, если вы удивите его своими познаниями. А может и не подарить.}
{3940}{}{Перестань меня тереть!}
{3941}{}{Нет! Нет! И еще раз, нет!}
{3942}{}{Код для активации сейфа в покоях императора - @lex code@.}


# Game Event Den Racing
{3950}{}{Сволочи!!!}
{3951}{}{Верните деньги!!!}
{3952}{}{А уже кончилось, что ли?!!}
{3953}{}{Эй, Пустошь! У нас есть победитель Смертельных Гонок! Поздравляем с заслуженной победой}
{3954}{}{Говорит Билл Гейс! Всесезонные Смертельные Гонки Западного побережья Гранд-Пасифик-Американ нашли своего победителя! Мы ждем серебрянного призера и сворачиваемся! Ура!}
{3955}{}{Внимание всем участникам Смертельных Гонок! Гонки завершены! Повторяю, гонки завершены! Следующие гонки состоятся через 3..4 месяца!}
{3956}{}{Внимание, внимание! Время, отведенное на маршрут для гонщиков Смертельных Гонок Западного побережья Гранд-Пасифик-Американ истекло! Сегодня мы остались без победителя! Всем спасибо! Все свободны!}
{3957}{}{Спасибо всем! Все призовые места заняты! Второе место заслуженно получает...}


# Game Event Replicator.
{4000}{}{Аррр-гх!}
{4000}{}{Поднимается, кряхтит, машет головой.}
{4000}{}{Несколько раз подскальзывается но снова встает.}
{4000}{}{Ыы-ааыа-ыаыы ыа аыааыыыа ыа убью!}
{4000}{}{Я все еще жив... ыАоооООНугрн ххха-ххахха}
{4000}{}{Встает на ноги}
{4001}{}{Арг-хгх-гх}
{4001}{}{МОЗГИ}
{4001}{}{УБЬЮ}
{4001}{}{Мамочка, ты меня звала?}
{4001}{}{Кто здесь?}
{4001}{}{Смерть гладкокожим}
{4001}{}{Урргаххаха}
{4001}{}{Урргаххаха}
{4002}{}{Подвывает}
{4002}{}{Нервно ковыляет в сторону}
{4002}{}{Кряхтит}
{4002}{}{Стонет}
{4002}{}{Гргх-гх-гхм}
{4002}{}{Дергается}
{4002}{}{Что эти твари сделали со мной?}
{4002}{}{Где я? Кто все эти гули? Почему они похожи на меня?}
{4003}{}{Бдыщ!}
{4003}{}{Хлоп!}
{4003}{}{Ш-ш-ш-ш!}
{4003}{}{Чпок!}
{4004}{}{Эй, @lex player@! Возможно, вас заинтересует наше предложение...@@Приветствую вас, @lex player@. Не желаете ли неплохо заработать?@@*Кх-хм. @lex player@. Могу ли я расчитывать на ваше внимание? Есть серьезный разговор.}
{4005}{}{Цель поражена. Но нужно время, чтобы убедиться, что гуль мертв и больше не поднимется.}
{4006}{}{Да, похоже этот уже не встанет. Прошло достаточно времени, чтобы понять, что гуль мертв окончательно.}
{4007}{}{Проклятие! "Убитый" гуль снова поднимается. Отчего же они такие прочные?}

# SF Invasion mobs. Using in sf_invasion.fos
{5100}{}{Расправляет крылья}
{5100}{}{ж-ж-ж}
{5100}{}{Шелестит крыльями}
{5100}{}{Щелк! Щелк!}
{5100}{}{Шёлкает}
{5100}{}{Угрожающе шевелит жвалами}
{5100}{}{Громко щелкает}
{5100}{}{Поворачивает голову в вашу сторону и издает какой-то скрежет}
{5101}{}{Прислушивается к собрату}
{5101}{}{Останавливается и готовится напасть}
{5101}{}{Медленно разворачивается и замирает}

# Квест Нэнси и Сид. Using in sf_common.fos
{5110}{}{S.O.S.}
{5111}{}{Это Нэнси... Сид, он...}
{5112}{}{Помогите кто-нибудь, я в палатке наркодилеров на побережье... Ранена... Умираю... Сид ушел...}

#Квест "Непыльная работа". navarro.fos
{5150}{}{Вы сканируете память робота с помощью сканера. Объем сохраненных данных: @lex value@%}
{5151}{}{Вы сканируете память робота с помощью сканера. Объем сохраненных данных: 100%! Можно возвращаться к технику в Наварро.}
{5152}{}{Банк данных этого робота опустошен. Возможно, кто-то уже просканировал и разрушил его память.}
{5153}{}{Вы устанавливаете чип в коммуникационный разъем робота. Остается только привести его в работоспособное состояние, и у вас будет самый лучший телохранитель.}
{5154}{}{Вам понятия не имеете, где этот разъем и как использовать чип.}
{5155}{}{Вам не удалось отремонтировать робота-стража.}
{5156}{}{Используя накопленные знания, вы приводите стража в работоспособное состояние. Теперь он станет вашим спутником.}

# Сообщения и тексты на карте Рынка. Using in map_barter_ground.fos
{5200}{}{Эй! @lex pname@! Ты зря захватил это с собой! К нам нельзя приносить эту дрянь!}
{5200}{}{Запрещенный предмет! Запрещенный предмет! Уничтожить @lex pname@}
{5200}{}{Внимание, всем! У репликанта @lex pname@ замечены запрещенные предметы. Уничтожить!}

# Урон от энерогетических барьеров
{5300}{}{You are shocked by the weakened force field.}
{5301}{}{You are shocked by the force field.}
{5302}{}{You fail to lower the force field.}
{5303}{}{You disable the force field.}
{5304}{}{You enable the force field.}
{5305}{}{You destroy the force field emitter.}
{5306}{}{You can see no way to use the emitter.}
{5307}{}{You can see no way to use the force field.}
{5308}{}{Yes, there is a lot of energy going through there. You stop before the electricity arcs to your hand.}
{5309}{}{You fail to do anything useful, and take about 50,000 volts for it. At least you won't have to worry about shaving.}
{5310}{}{The force field seems to be unaffected.}
{5311}{}{You fail to upper the force field.}

# Охрана на воротах реддинга. redd_gates.fos
{5400}{}{Назад, немедленно!@@Не подходи к двери @lex pname@. Второй раз предупреждать не буду.}
{5401}{}{Ты слишком глуп@lex sex@. Эта ошибка будет стоить тебе жизни!@@Тебя предупреждали}
{5402}{}{КУДА ТЫ? ТЫ ТРУП@@Нарушитель. Огонь на поражение}

# Работа в шахте Реддинга. redd_mines.fos
{5420}{}{Вы бережно опускаете один из золотых самородков в вагонетку. Всего добыто золота: @lex num@.}

#Могила мужа Руни
{5425}{}{Да, это та самая могила. Вы оставляете цветы возле обелиска.}

# Сообщение на входе в Реддинг
{5430}{}{По приближению к городу, Вы замечаете, что северная его часть огорожена длинной стеной.}

# Город из ГЕККа MapGeckCity.fos
{5500}{}{This place is completely unsuitable for contructing a city.}
{5501}{}{Wrong code. Activation cancelled.}
{5502}{}{Code accepted. Activating G.E.C.K...}
{5503}{}{Citizen's info saved. Name: @lex pname@.}
{5504}{}{Congratulations! You have been registered in city's system. You now have an access to all the systems.}
{5505}{}{Garden of Eden Construction Kit work is now complete... Welcome to city that G.E.C.K. built.}
{5506}{}{Электронный замок на этой двери невозможно открыть стандартными способами. От отмычек или динамита не будет никакого толку.}
{5507}{}{@lex leadername@ has entered you into the lists of citizens of city constructed by G.E.C.K.}
{5508}{}{@lex leadername@ has removed you from the the lists of citizens of city constructed by G.E.C.K.}
{5509}{}{Generator is charged, total charges: @lex charges@. Estimated barrier work time: @lex time@.}
{5510}{}{Out of order.}
{5511}{}{Посмотрим, что здесь можно сделать...}

#Квест "Семья", ГУ, Вэлери. vcity_common.fos
{5800}{}{Типичная женская писанина. Даже смотреть не хочется.}
{5801}{}{Вам совершенно случайно попадаются на глаза первые строки письма. Они настолько увлекают вас, что вы дочитываете до самого конца: …и прости, что я так вела себя с тобой. Нас ведь осталось только двое во всём мире. Надеюсь и хочу увидеть тебя. Любящая тебя дочь.}
{5802}{}{[…надо же. Написано просто кровью сердца. Вы еще раз  перечитываете  письмо, и  оно остается у вас в памяти].}

# Квест "Свет мой, зеркальце", ГУ, Доктор Хелен Трой. vcity_common.fos
{5805}{}{Ну и заумь. Совершенно ничего непонятно.}
{5806}{}{Да тут не так уж и сложно всё. Любой осёл разберется. Вы запоминаете содержимое.}

#Квест "Рога Изобилия", БХ, Начальник фабрики. broken_common.fos
{5900}{}{Убито саботажников по заданию АХС-7: @lex dead@ из 40.}
{5901}{}{В глазах рябит от формул и чертежей. Пускай специалисты разбираются.}
{5902}{}{Описание технологии обогащения, изложенное четким  языком, со множеством прекрасных чертежей. Вы с удовольствием вникаете в суть дела.}

#Квест "Возвращение ребенка"
{5905}{}{Проваливай отсюда, извращенец.@@Посмотрите на эту мразь! Он набрался наглости вернуться сюда!@@таким как ты в польше химическую кастрацию делают, @Иди в жопу извращенец!@И откуда вы, мрази, беретесь.@@Охотники уже идут за тобой. Ты сдохнешь!}

# Квест "Гвардия Города-Убежища. Испытание первое". fighter_quest.fos
{5910}{}{Начат поединок c @lex npcname@. Удачи!}
{5911}{}{Вы победили в поединке с @lex npcname@. Поздравляем. Прекратите атаку, иначе вас не поймут окружающие.}
{5912}{}{Удача была не на вашей стороне. Вы проиграли поединок с @lex npcname@.}
{5913}{}{В результате поединка ваш противник был убит.}
{5914}{}{Жулик! Договаривались без оружия!}

#Квест "Гвардия Города-Убежища. Испытание третье". vc_guardsman.fos
{5915}{}{Вы в правильной позиции. Оставайтесь на месте до первой команды. Равнение на середину!}
{5916}{}{Да сколько можно? Стать в строй, черт тебя дери! Иначе отправлю к мамочке!}
{5917}{}{Вы что-то сделали не так. Задание провалено.}


#Монологи-песни Илая. eli.fos
#4
{5960}{}{Да, сегодня позволено все,}
{5961}{}{Что крушишь себя так увлеченно.}
{5962}{}{Видишь, я над тобою кружу.}
{5963}{}{Это я фиолетово-черный.}
{5964}{}{Если можешь, беги, рассекая круги,}
{5965}{}{Только чувствуй себя обреченной.}
{5966}{}{Стоит солнцу зайти, вот и я}
{5967}{}{Стану вмиг фиолетово-черным.}

#Квест "Ночь нежна." Модок. map_modoc.fos
{5970}{}{От зараза, охранника поставили. Надо сваливать от греха…}
{5971}{}{Отличное место для наблюдений. Осталось дождаться ночи и выяснить, что происходит с браминами.}
{5972}{}{Не стреляй, человек. Давай поговорим!}

#Монологи-песни Илая. eli.fos
#1
{5973}{}{Я сам себе и небо и луна}
{5974}{}{Голая, довольная луна}
{5975}{}{Долгая дорога, да и то не моя.}
{5976}{}{За мною зажигали города}
{5977}{}{Глупые чужие города}
{5978}{}{Там меня любили, только это не я.}
#2
{5980}{}{Мертвая змея не шипит}
{5981}{}{Не щебечет дохлый щегол}
{5982}{}{Мертвый негр не идет играть в баскетбол...}
{5983}{}{Только мертвый негр не идет играть в баскетбол...}
{5984}{}{Ай-я-я-я-я-я-яй убили негра, убили негра, убили...}
{5985}{}{Ай-я-я-я-я-яй ни за что ни про что...суки замочили...}
{5986}{}{Ай-я-я-я-я-я-яй убили негра, убили негра, убили...}
{5987}{}{Ай-я-я-я-я-яй ни за что ни про что...суки замочили...}
#3
{5988}{}{Я на чердаке лежу у себя на дому.}
{5989}{}{Мне скучно до зарезу Бог знает почему.} 
{5990}{}{Вдруг слышу за собою совы нежные "У-юй" -}
{5991}{}{У меня на душе стало веселее,}
{5992}{}{А-лай-лай-лай, стало веселее.} 
{5993}{}{Я по дороге иду к другу-разбойнику,} 
{5994}{}{Мне тоскливо одному в незнакомом краю.} 
{5995}{}{Вдруг слышу за собою совы нежные "У-юй" -}
{5996}{}{У меня на душе стало веселее,}
{5997}{}{А-лай-лай-лай, стало веселее.}


# Основной сюжетный квест. Резерв 6000...7000
{6000}{}{В вашем ПипБое записана важная информация.}

# Сражения, поединки. battle_info.fos
{7001}{}{Невозможно использовать. Возможно, нужно дождаться следующего этапа сражения.}
{7002}{}{Невозможно использовать. Доступ только для участников сражения.}
{7003}{}{Невозможно использовать. Доступ только для победителей.}

# ГУ, квестовая линия поддержки Линетт. vc_lynett.fos
{7100}{}{Вот сука черномазая, говорила – легкая мишень… }
{7101}{}{Ха, как эта черная сука и обещала – раз плюнуть…}

# q_silo.fos
{7110}{}{Эту дверь заклинило. Никакая сила не поможет ее открыть.}

# game_event_caches.fos
{7115}{}{Это место очень похоже на то, что указано в карте наемника.}


# purgatory.fos

{7120}{}{Внимание! Открыт набор участников для Испытания в Чистилище. Для того, чтобы подать заявку найдите Экзекутора на входе любого города Пустоши.}
{7121}{}{Мощный электрически разряд из пипбоя отправляет вас на небеса. Правда, вам показалось, что удар был нанесен в шею, откуда-то сзади.}
{7122}{}{Вещи, которые были на вас в момент смерти, вы сможете забрать в банке хабологов в любое удобное для вас время.}
{7123}{}{Вы приняли участие в Испытании хабологов. 
Ваша команда должна уничтожить представителей других команд. 
После этого вы сможете получить заслуженную награду и покинуть территорию Чистилища. 
За каждого убитого противника вы получаете премию на репликационный счет: 300 монет. 
За убитого союзника назначается штраф: 1000 монет. Сумма штрафа будет вычтена с репликационного счета.}
{7124}{}{В Чистилище хабологи устраивают гладиаторские бои между реплицированными.}
{7125}{}{|@lex teamColor@ Команда @lex team@ |@lex baseColor@: К сражению присоединяется |@lex teamColor@ @lex name@. }
{7126}{}{Участник сражения |@lex team2Color@ @lex killer@ |@lex baseColor@ убивает |@lex team1Color@ @lex dead@ |@lex baseColor@ !!}
{7127}{}{Пока никто не записался...}
{7128}{}{Испытание закончено. Все зрители и участники покидают Чистилище.}
{7129}{}{Вы убили представителя своей команды. С репликационного счета снят штраф 1000 монет.}
{7130}{}{Вы убили представителя вражеской команды. На репликационный счет начислено 300 монет. Опыта получено @lex xp@.}
{7131}{}{Испытание завершено! Победила команда репликационной станции @lex team@!}
{7132}{}{Внимание! Испытание началось! Двери боксов распечатаны. Удачи всем участникам сражения!}


# Реплики для нпц, защищающих свой город. npc_revenge.fos
# предположительно райты
{7200}{}{Жители города! Все идите сюда! Мы должны положить конец этим убийствам!}
{7200}{}{Все сюда! Я буду говорить!}
{7200}{}{Хватит! Мы должны все вместе бросить вызов этим подонкам. Приходите, мы придумаем как быть!}
{7201}{}{Черт, как невовремя...}
{7201}{}{Как скажешь.}
{7201}{}{Как меня это достало, черт подери.}
{7201}{}{Иду, иду.}
{7201}{}{Да, они совсем оборзели!}
{7202}{}{Вы все сами все видите. Мне незачем рассказывать, что у нас здесь происходит. Наша проблема - гопота}
{7203}{}{Они убивают нас, наших детей, наших друзей. Они уничтожают наш город. Эти подонки в синих трико, они хотят стереть нас с лица земли!}
{7204}{}{Мы пережили войну, радиацию, песчаные бури и даже произвол Избранного! Мы должны сами справиться с новой угрозой.}
{7205}{}{Ни один гопник не должен уйти безнаказанно! Они все одинаковые! Мочи всех живых!}
{7206}{}{Никому не верьте! Увидел на спине цифру, видишь гопа-репликанта, убей! Иначе через минуту погибнешь сам!}
{7207}{}{Вперед! Пока мы вместе, мы сила!}
{7208}{}{Все правильно сказал. Гопы задолбали.}
{7208}{}{Гребаные гопники.}
{7208}{}{Они не имеют права на жизнь.}
{7208}{}{МЕСТЬ! МЕСТЬ! МЕСТЬ!}
{7208}{}{В точку!}
{7208}{}{Да! Нужно убивать их сразу, как только увидим!}
{7209}{}{Сдохни, проклятый гоп!}
{7209}{}{Получил, гопяра?}
{7209}{}{ХА! Слился! Одним гопом меньше!}
{7209}{}{Ууууу, скотина репликантская. Мы тебе припомним. Только сунься сюда еще раз.}
{7209}{}{Умри! Умри! Умри! Гопы должны страдать!}
{7210}{}{Оп-па. Гопы в городе. ТРЕВОГА!!!}
{7210}{}{Мочи репликантскую сволочь!}
{7210}{}{Гопники прут! Нападаем!}
{7210}{}{Вижу гопа. Все сюда.}

# npc_dialog.fos. Строки для диалогов
# Диалог хономера и охранника. q_hub_lab.fos
{8000}{}{Кто такие?}
{8001}{}{Программист, по запросу АХС-7, для восстановления работоспособности системы авторизации.}
{8002}{}{Брат Хономер? Отлично, вас давно ждут. Можете пройти. А это кто с вами?}
{8003}{}{Мой эскорт. [Поворачивается к вам] АХС-7, ваша задача выполнена. Вы свободны.}
# Диалог двух лаборантов
{8010}{}{Эх...}
{8011}{}{А что за посетители сегодня, не знаешь? }
{8012}{}{Да программер, систему авторизации чинить пришел...}
{8013}{}{Зачем нам чужой программер? И где наш раздолбай?}
{8014}{}{Нашего расстреляли...}
{8015}{}{Ого! За что?}
{8016}{}{Да к начальнику комиссия приехала, с АХС-7 во главе. Шеф комиссию повел по лаборатории. }
{8017}{}{Идут, шеф рассказывает, что да как, знакомит проверяющего с персоналом, тот вопросы задает. Ну и заходят в серверную.}
{8018}{}{И чо?}
{8019}{}{Ну и все. Заходят, наш админ, бухой в стельку, спит на сервере, на мониторе - косынка, музло играет... Бардак в общем. Шеф как увидел, аж позеленел от злости.}
{8020}{}{Звездец...}
{8021}{}{Угу. Комиссия шефу вставила большой пистон, уехали, а он вызвал этих, с поверхности. Те админа к стенке, и очередью. Как он орал...}
{8022}{}{И что теперь?}
{8023}{}{Ну че, как отреплицируется, вернется. Шеф увольнять не хочет, другого хрен найдешь. А пока вызвал из Фриско кодера, починить кое-что. Система авторизации сдохла.}
{8024}{}{Вот оно что... И чего, без авторизации в сеть сейчас как входить?}
{8025}{}{Тупо, без пароля. Сейчас даже логин не нужен - система лежит. }
{8026}{}{Опасно.}
{8027}{}{Ну да. Но, этот, вроде, дело знает. Посмотрим.}
{8028}{}{Угу...}
# HРемонт
{8029}{}{Не понимаю, что это вообще означает?}
{8029}{}{Комментарии для слабых, понятно.}
{8029}{}{Переменные нормально назвать ну никак, да.}
{8029}{}{В рот ебал польскую нотацию...}
{8029}{}{Аффтар, поначитался книжек, а головой думать нет?}
{8029}{}{Буфер кто за тебя чистить будет, дядя федор?}
{8029}{}{Ебалайка, еще больше бы трай кетчей поставил...}
{8029}{}{Почитаем комментарии... "TODO: Исправить это." Исправить что, мля?}
{8029}{}{Что здесь... "дефайн тру равно фолс".  И комментарий... "Удачного дебага, сука". Ух, блин.}
{8029}{}{Откуда среди наших столько быдлокодеров?}
{8029}{}{Во блин, разве так сработает? Ну-ка... МЛЯ! Не сработало...}
{8029}{}{О, йоба, это мне на месяц работы...}
{8029}{}{Не, ну это надо, накосячить так. Это талант.}
{8029}{}{Компилятор без молитвы не запускается... Отче наш, драть тебя за ухо! Не помогло. С молитвой тоже не запустился.}
{8029}{}{Оригинальный ход... Для идиота. Гарбадж коллектор такой же идиот писал, 100%.}
{8029}{}{2 + 2 = -6.5?! Какого...}
{8029}{}{Найти бы аффтара, да спросить, что все это значит, и почему он такой придурок.}
{8029}{}{Не могу понять, как такое криворукое чмо дослужилось до АХС-4. }
{8029}{}{Ему не кодить, ему в клоуны пора... }
{8029}{}{Ох, за что мне это все?}
{8029}{}{Что это за язык вообще? Императивный Haskell? Как так?!}
# Диалог между посетителями бара в ГУ
{8032}{}{Передайте, пожалуйста, соль.}
{8033}{}{Пожалуйста.}
{8034}{}{Спасибо.}
{8035}{}{Пожалуйста.}
{8036}{}{Не подъёбывай.}
{8037}{}{Пошел на х$@!!!}

# Специальные Энкаунтеры. 70000...70100
# Переводчику: большую часть английских текстов для них можно скопировать из оригинала. Т.е. нужно.

# Портал Хранителя
{70000}{}{Вы сломали водяной чип в убежище. Вам почему-то кажется что в течении 100-150ти дней в убежище кончится вся вода. Скорее всего жители убежища будут обеспокоены этим.}
{70001}{}{*Биип*@@*Бип* Би-оп*@@*Биоп*}

#Говорящая голова.
{70002}{}{Чо--?}
{70003}{}{УБЕРИ СВОИ ГРЯЗНЫЕ РУКИ ОТ МЕНЯ!}
{70004}{}{*Гм*}
{70005}{}{КТО ПОЗВОЛЯЛ ПРИБЛИЖАТСЯ К СВЯЩЕННОЙ ГОЛОВЕ ЖИТЕЛЯ УБЕЖИЩА?!}
{70006}{}{Ммм... Я спаситель мира! Я найду Избранного!} 
{70007}{}{ХА-ХА-ХА-ХА-ХА}
{70008}{}{*Ты*!? Спаситель мира?}
{70009}{}{ТЫ НЕ БОЛЬШЕ ЧЕМ МОЙ ПАЛЕЦ!}
{70010}{}{ТЫ *НЕ* СПАСИТЕЛЬ МИРА!}
{70011}{}{Да, я спаситель мира.}
{70012}{}{Нет.}
{70013}{}{Да.}
{70014}{}{УХ-УХ.}
{70015}{}{УХ-ХУХ.}
{70016}{}{УХ-УХ.}
{70017}{}{УХ-ХУХ.}
# Спустя 12 часов.
{70018}{}{УХ...УХ...}
{70019}{}{УХ...ХУХ...}
{70020}{}{УХ...ХВАТИТ ЭТОГО!}
{70021}{}{ОЧЕНЬ ХОРОШО, ТЫ ДОКАЗАЛ ЭТО!}
{70022}{}{ТЫ *ДЕЙСТВИТЕЛЬНО* СПАСИТЕЛЬ МИРА!}
{70023}{}{ВОЗЬМИ ЭТО.}
{70024}{}{ТЕПЕРЬ ОСТАВЬ МЕНЯ В ПОКОЕ.}
{70025}{}{Спасибо!}
{70026}{}{ДА, ЧТО УГОДНО.А ТЕПЕРЬ УБИРАЙСЯ!}
{70027}{}{ПРОКЛЯТЫЕ ТУРИСТЫ!}
{70028}{}{Спустя 12 часов}
{70029}{}{!!!ЧТО?! УКРАСТЬ У МЕНЯ!? И ТЫ ЭТО СДЕЛАЕШЬ?!!!} 

# Железный дровосек
{70050}{}{Масло.} 

# Склад пончиков
{70060}{}{Эту стелу воздвигли друзья и знакомые Пончика в знак любви и уважения. Ниже нацарапано гвоздем: враки, это он сам сделал (друзья и знакомые).} 
{70061}{}{Вы съели столько пончиков, что почуствовали себя немного сильнее. Переносимый вес увеличен на +1 фунт.}
